'use strict';
const M=MusicCore,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let score=M.blank(),selected=null,activeVoice='v1',currentMeasure=0,mode='edit';
const selectedToneIndices=new Map();let menuArmPoint=null;
const selectedNotes=new Set(),selectedMeasures=new Set(),selectedMeasureVoices=new Map(),selectedSymbols=new Map();
let defaults={duration:4,dots:0,triplet:false,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false};
let undoStack=[],redoStack=[],geometry=[],notePositions=new Map(),playSession=null,audioContext=null,buffers=new Map(),pendingConfirm=null,pendingScope=null,symbolTool=null,symbolStart=null,menuTarget=null,hideMenuTimer=null,lyricEditBefore=null;
try{const saved=localStorage.getItem('puji-score-v3')||localStorage.getItem('puji-score-v2')||localStorage.getItem('puji-score-v1');if(saved)score=M.sanitize(JSON.parse(saved));}catch{setTimeout(()=>toast('自动保存不可用，请导出备份作品。'),500);}activeVoice=score.voices[0].id;
const part=()=>score.voices.find(v=>v.id===activeVoice)||score.voices[0];
const config=(mi=currentMeasure,vid=activeVoice)=>M.settings(score,mi,vid);
const escapeXml=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const timeText=seconds=>{const n=Math.max(0,Math.round(seconds));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;};
const glyph=(char,x,y,size=48,cls='music-text',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" class="${cls}" ${extra}>${char}</text>`;
const line=(x1,y1,x2,y2,cls='staff-line',extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}" ${extra}/>`;
const beatKey=n=>n.toFixed(6);
const dynamics=['pppp','ppp','pp','p','mp','mf','f','ff','fff','ffff','sf','sfz','fp','rfz'];
const articulations=[['staccato','·'],['staccatissimo','▾'],['accent','›'],['marcato','∧'],['tenuto','—'],['fermata','𝄐'],['breath','ʹ'],['legato','⌒'],['portato','— ·'],['pizzicato','pizz.'],['arco','arco']];
const navNames={segno:'𝄋 Segno',coda:'𝄌 Coda','to-coda':'To Coda',fine:'Fine','dc-fine':'D.C. al Fine','ds-fine':'D.S. al Fine','dc-coda':'D.C. al Coda','ds-coda':'D.S. al Coda'};
const clefNames={treble:'高音谱号',bass:'低音谱号',treble8vb:'高音谱号 · 低八度',treble8va:'高音谱号 · 高八度'};
const meterValues=[...new Set(['4/4','3/4','2/4','6/8','9/8','12/8','2/2','3/8','5/4','7/8',...[2,4,8,16].flatMap(d=>Array.from({length:12},(_,i)=>`${i+1}/${d}`))])];
$('meter').innerHTML=meterValues.map(v=>`<option>${v}</option>`).join('');
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
const snapshot=()=>JSON.stringify(score);
function save(){try{localStorage.setItem('puji-score-v3',snapshot());$('saveState').textContent='已保存到本机';}catch{$('saveState').textContent='请导出备份';}}
function clearSelection(){selected=null;selectedNotes.clear();selectedToneIndices.clear();selectedMeasures.clear();selectedMeasureVoices.clear();selectedSymbols.clear();hideMenu();}
function commit(fn){stop();const prev=snapshot();if(mode==='edit')hideMenu();try{fn();finishCompleteMeasures();}catch(e){score=JSON.parse(prev);toast(e.message);render();return;}if(snapshot()!==prev){undoStack.push(prev);if(undoStack.length>120)undoStack.shift();redoStack=[];}render();save();}
function findNote(id){for(let mi=0;mi<score.measures.length;mi++){const ei=score.measures[mi].events.findIndex(e=>e.id===id);if(ei>=0)return {e:score.measures[mi].events[ei],mi,ei};}return null;}
const getSelected=()=>findNote(selected);
const selectedList=()=>score.measures.flatMap(m=>m.events).filter(e=>selectedNotes.has(e.id));
function select(id,add=false,toneIndex=0){if(!add)clearSelection();if(add&&selectedNotes.has(id)){selectedNotes.delete(id);selectedToneIndices.delete(id);}else{selectedNotes.add(id);selectedToneIndices.set(id,toneIndex);}selected=selectedNotes.has(id)?id:[...selectedNotes].at(-1)||null;const f=getSelected();if(f){focusMeasure(f.mi,f.e.voice);defaults.duration=f.e.duration;defaults.dots=M.dots(f.e);if(f.e.tuplet){$('tupletCount').value=f.e.tuplet.count;$('tupletRange').value=f.e.tuplet.count;$('tupletTotal').value=f.e.tuplet.total;}}render();}
function selectMeasure(mi,vid=activeVoice,add=false){if(!add)clearSelection();const id=score.measures[mi].id,parts=selectedMeasureVoices.get(id)||new Set();if(add&&parts.has(vid))parts.delete(vid);else parts.add(vid);if(parts.size){selectedMeasureVoices.set(id,parts);selectedMeasures.add(id);}else{selectedMeasureVoices.delete(id);selectedMeasures.delete(id);}focusMeasure(mi,vid);render();}
const symbolKey=t=>`${t.kind}:${score.measures[t.mi]?.id}:${t.id||''}`;
function selectSymbol(t,add=false){if(!add)clearSelection();const key=symbolKey(t);if(add&&selectedSymbols.has(key))selectedSymbols.delete(key);else selectedSymbols.set(key,t);currentMeasure=t.mi;if(t.kind==='measureOctave'||t.kind==='measureHairpin')activeVoice=t.id;else if(t.id){const f=findNote(t.id);if(f)activeVoice=f.e.voice;}render();}
function setProp(k,v){if(['duration','dots'].includes(k))defaults[k]=v;if(mode==='edit'&&['duration','dots'].includes(k)){syncTools();return;}const list=selectedList();if(!list.length){syncTools();return;}commit(()=>list.forEach(e=>{const tone=selectedToneIndices.get(e.id)||0;if(k==='accidental'&&tone&&e.chord?.[tone-1])e.chord[tone-1].accidental=v;else e[k]=v;if(['duration','dots'].includes(k)){e.tuplet=null;e.triplet=false;e.exactTicks=null;}}));}
function syncSettings(){
  if(!score.voices.some(v=>v.id===activeVoice))activeVoice=score.voices[0].id;currentMeasure=Math.max(0,Math.min(currentMeasure,score.measures.length-1));
  const c=config();$('title').value=score.title;$('mode').value=c.mode;$('key').innerHTML=(c.mode==='minor'?M.MINOR:M.MAJOR).map((n,i)=>`<option value="${i-7}">${n} ${c.mode==='minor'?'小调':'大调'}</option>`).join('');$('key').value=c.key;$('clef').value=c.clef;$('meter').value=c.meter.join('/');$('bpm').value=c.bpm;
  $('keySummary').textContent=c.key===0?'无升降号':(c.key>0?M.SHARPS:M.FLATS).slice(0,Math.abs(c.key)).map(l=>l+(c.key>0?'♯':'♭')).join('  ');
  $('voice').innerHTML=score.voices.map(v=>`<option value="${v.id}">${escapeXml(v.name)}${v.muted?' · 静音':''}</option>`).join('');$('voice').value=activeVoice;$('voiceName').value=part().name;$('muteVoice').checked=part().muted;$('removeVoice').disabled=score.voices.length===1;$('voiceSummary').textContent=`${score.voices.length} 个声部`;
  const bits=[];if(selectedNotes.size)bits.push(`${selectedNotes.size} 个音符／休止符`);if(selectedMeasures.size)bits.push(`${selectedMeasures.size} 个小节`);if(selectedSymbols.size)bits.push(`${selectedSymbols.size} 个符号`);$('selectionSummary').textContent=bits.length?'已选 '+bits.join('、'):`${part().name} · 第 ${currentMeasure+1} 小节`;
}
function syncTuplet(){const count=Math.max(2,Math.min(32,Math.round(Number($('tupletCount').value)||3))),total=Math.max(.125,Math.min(32,Number($('tupletTotal').value)||1));$('tupletSummary').textContent=`${count} 个音均分 ${M.fmt(total)} 拍 · 每音 ${M.fmt(total/count)} 拍`;}
function syncTools(){document.querySelectorAll('[data-duration]').forEach(b=>b.classList.toggle('active',+b.dataset.duration===defaults.duration));$('dots').value=defaults.dots;$('modeToggle').textContent=mode==='edit'?'编辑模式 · Tab':'选择模式 · Tab';$('modeToggle').classList.toggle('active',mode==='edit');$('score').dataset.mode=mode;$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;syncTuplet();$('cancelSymbol').hidden=!symbolTool;document.querySelectorAll('[data-symbol]').forEach(b=>b.classList.toggle('active',symbolTool?.kind===b.dataset.symbol&&String(symbolTool.value)===b.dataset.value));$('symbolStatus').textContent=symbolTool?(symbolStart?'已放置起点，再点终点；Esc 结束':'点击谱面放置 '+symbolTool.label):'';}
function render(){if(mode==='edit')hideMenu();syncSettings();syncTools();renderScore();renderStats();renderIssues();if(menuTarget&&!$('contextMenu').hidden)buildMenu();}
function renderStats(){const s=M.stats(score);$('noteCount').textContent=s.count;$('highest').textContent=s.highest;$('lowest').textContent=s.lowest;$('duration').textContent=timeText(s.seconds);$('durationExact').textContent=`（${s.seconds.toFixed(2)} 秒 · 含反复）`;}
function renderIssues(){const issues=M.validate(score);$('validationTitle').textContent=issues.length?'输入错误提示':'✓ 输入提示';$('validationSummary').textContent=issues.length?`${issues.length} 项待处理`:'暂无错误';$('fixAll').disabled=!issues.length;
  $('issues').innerHTML=issues.map((i,index)=>`<div class="issue"><span>${escapeXml(i.text)}</span><button data-locate="${index}">定位</button><button data-fix="${index}">修正</button></div>`).join('');
  document.querySelectorAll('[data-locate]').forEach(b=>b.onclick=()=>{const i=issues[+b.dataset.locate];mode='select';if(i.voice)activeVoice=i.voice;currentMeasure=i.mi;if(i.id)select(i.id);else selectMeasure(i.mi);$('score').querySelector(`[data-measure="${i.mi}"][data-part="${activeVoice}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});});
  document.querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>{const i=issues[+b.dataset.fix];offerFix(i.kind,i.id);});
}
function symbolAttrs(kind,mi,id=''){const t={kind,mi,id};return `class="score-symbol${selectedSymbols.has(symbolKey(t))?' selected-symbol':''}" data-symbol-kind="${kind}" data-symbol-mi="${mi}" data-symbol-id="${id}"`;}

function signatureWidth(mi){if(!mi)return 0;const a=config(mi-1),b=config(mi);return (a.key!==b.key?16+13*(Math.abs(a.key)+Math.abs(b.key)):0)+(a.meter.join('/')!==b.meter.join('/')?32:0)+(score.voices.some(v=>config(mi-1,v.id).clef!==config(mi,v.id).clef)?38:0);}
function measureLayout(m,mi){
  const map=new Map();
  score.voices.forEach(v=>{let beat=0;const es=M.events(score,m,v.id),complete=M.close(es.reduce((a,e)=>a+M.ticks(e),0),M.capacity(score,mi));es.forEach(e=>{const key=beatKey(beat),left=16+(e.accidental!==null||e.chord?.some(t=>t.accidental!==null)?22:0)+(e.graceNotes?.length||0)*18+(e.arpeggio?12:0),right=Math.max(21+M.dots(e)*7,12+(e.lyric?.length||0)*7),width=Math.max(38,left+right),anchor=complete?null:e.positionRatio??null;
    if(!map.has(key))map.set(key,{beat,width,left,right,anchor});else{const p=map.get(key);p.left=Math.max(p.left,left);p.right=Math.max(p.right,right);p.width=p.left+p.right;if(p.anchor===null)p.anchor=anchor;}beat+=M.ticks(e);});});
  const points=[...map.values()].sort((a,b)=>a.beat-b.beat),header=signatureWidth(mi);points.forEach((p,i)=>p.weight=Math.sqrt(Math.max(6,(points[i+1]?.beat??M.capacity(score,mi))-p.beat)/48));
  return {points,header,min:Math.max(220,header+56+points.reduce((a,p)=>a+p.width,0))};
}
function signature(key,oldKey,x,yFor,clef,cancel=false){let out='',count=0;const bass=clef==='bass'?14:0,sharp=[38,35,39,36,33,37,34],flat=[34,37,33,36,32,35,31];if(cancel&&oldKey!==key){const oldMap=M.keyMap(oldKey),newMap=M.keyMap(key),positions=oldKey>0?sharp:flat;(oldKey>0?M.SHARPS:M.FLATS).slice(0,Math.abs(oldKey)).forEach((l,i)=>{if(oldMap[l]!==newMap[l]){out+=glyph('\uE261',x+count*13,yFor(positions[i]-bass));count++;}});if(count)count++;}const positions=key>=0?sharp:flat;positions.slice(0,Math.abs(key)).forEach(p=>{out+=glyph(key>=0?'\uE262':'\uE260',x+count*13,yFor(p-bass));count++;});return {html:out,width:count*13};}
function drawClef(clef,x,base,bottomPitch){const y=p=>base-(p-bottomPitch)*6;return glyph(clef==='bass'?'\uE062':'\uE050',x,clef==='bass'?y(24):y(32))+(clef==='treble8vb'||clef==='treble8va'?`<text x="${x+14}" y="${clef==='treble8vb'?base+30:base-86}" text-anchor="middle" font-size="11">8</text>`:'');}
function drawMeter(meter,x,top){return `<text x="${x}" y="${top+19}" text-anchor="middle" font-family="Georgia" font-weight="bold" font-size="23">${meter[0]}</text><text x="${x}" y="${top+43}" text-anchor="middle" font-family="Georgia" font-weight="bold" font-size="23">${meter[1]}</text>`;}
function headPitchList(e){return M.tones(e).map(t=>t.pitch);}
function prepareStems(positions,meter){
  positions.forEach(p=>{
    p.headYs=headPitchList(p.e).map(pitch=>p.base-(pitch-p.bottomPitch)*6);if(!p.headYs.length)p.headYs=[p.y];
    const pitches=headPitchList(p.e),mid=p.bottomPitch+4;p.down=pitches.length?Math.max(...pitches)-mid>=mid-Math.min(...pitches):false;
    p.stemX=p.down?p.x+.6:p.x+13.6;p.stemStart=p.down?Math.min(...p.headYs):Math.max(...p.headYs);
    const extension=36+Math.max(0,Math.log2(p.e.duration)-5)*4;p.stemEnd=p.down?Math.max(...p.headYs)+extension:Math.min(...p.headYs)-extension;p.beamed=false;
  });
  const byId=new Map(positions.map(p=>[p.e.id,p])),groups=M.beamGroups(positions.map(p=>p.e),meter).map(g=>g.map(e=>byId.get(e.id)));
  groups.forEach(group=>{
    const pitches=group.flatMap(p=>headPitchList(p.e)),mid=group[0].bottomPitch+4,down=Math.max(...pitches)-mid>=mid-Math.min(...pitches),a=group[0],b=group.at(-1);
    group.forEach(p=>{p.down=down;p.stemX=down?p.x+.6:p.x+13.6;p.stemStart=down?Math.min(...p.headYs):Math.max(...p.headYs);});
    const edge=p=>down?Math.max(...p.headYs)+36+Math.max(0,...group.map(q=>Math.log2(q.e.duration)-5))*6:Math.min(...p.headYs)-36-Math.max(0,...group.map(q=>Math.log2(q.e.duration)-5))*6,slope=Math.max(-.14,Math.min(.14,(edge(b)-edge(a))/Math.max(1,b.stemX-a.stemX))),origin=down?Math.max(...group.map(p=>edge(p)-slope*(p.stemX-a.stemX))):Math.min(...group.map(p=>edge(p)-slope*(p.stemX-a.stemX)));
    group.forEach(p=>{p.stemEnd=origin+slope*(p.stemX-a.stemX);p.beamed=true;});
  });return groups;
}
function beamPolygon(a,b,level,down){const toward=down?-1:1,offset=(level-1)*7*toward,y1=a.stemEnd+offset,y2=b.stemEnd+offset;return `<path class="beam-ink" d="M ${a.stemX} ${y1} L ${b.stemX} ${y2} L ${b.stemX} ${y2+5*toward} L ${a.stemX} ${y1+5*toward} Z"/>`;}
function drawBeams(groups,out){groups.forEach(group=>{const down=group[0].down;out.push('<g class="beam-group" pointer-events="none">',beamPolygon(group[0],group.at(-1),1,down));const levels=p=>Math.log2(p.e.duration)-2;
  for(let level=2;level<=Math.max(...group.map(levels));level++){let run=[];const flush=()=>{if(!run.length)return;if(run.length>1)out.push(beamPolygon(run[0],run.at(-1),level,down));else{const p=run[0],idx=group.indexOf(p),neighbor=group[idx+1]||group[idx-1],dx=Math.sign(neighbor.stemX-p.stemX)*Math.min(13,Math.abs(neighbor.stemX-p.stemX)*.4),q={stemX:p.stemX+dx,stemEnd:p.stemEnd+(neighbor.stemEnd-p.stemEnd)*dx/(neighbor.stemX-p.stemX)};out.push(beamPolygon(p,q,level,down));}run=[];};group.forEach(p=>{if(levels(p)>=level)run.push(p);else flush();});flush();}out.push('</g>');});}
function renderScore(){
  const prefix=164+Math.max(...score.measures.map((m,mi)=>Math.abs(config(mi).key)))*13,layouts=score.measures.map(measureLayout),w=Math.max(660,$('score').clientWidth,...layouts.map(l=>l.min+prefix+22)),rows=[];let row=[],occupied=prefix+22;
  layouts.forEach((layout,mi)=>{if(row.length&&occupied+layout.min>w){rows.push(row);row=[];occupied=prefix+22;}row.push({mi,layout});occupied+=layout.min;});if(row.length)rows.push(row);
  const resolved=new Map(M.resolved(score).map(n=>[n.e.id,n]));geometry=[];notePositions=new Map();let out=[],offset=0;
  rows.forEach((row,ri)=>{const extra=(w-prefix-22-row.reduce((a,p)=>a+p.layout.min,0))/row.length;let mx=prefix;
    const bars=row.map((p,bi)=>{const width=p.layout.min+extra,start=mx,end=mx+width,header=bi===0?0:p.layout.header,xmap=new Map(),points=p.layout.points,space=width-header-46-points.reduce((a,p)=>a+p.width,0),weights=points.reduce((a,p)=>a+p.weight,0)||1;let x=start+header+23;
      points.forEach(p=>{xmap.set(beatKey(p.beat),p.anchor!==null?start+header+26+p.anchor*Math.max(0,width-header-58):x+p.left);x+=p.width+space*p.weight/weights;});mx=end;return {...p,start,end,width,header,xmap};});
    let systemTop=null,lastBase=offset+45;
    score.voices.forEach(v=>{
      const list=row.flatMap(({mi})=>M.events(score,score.measures[mi],v.id).map(e=>({e,mi}))),notes=list.flatMap(p=>[...M.tones(p.e),...(p.e.graceNotes||[])].map(t=>({pitch:t.pitch,mi:p.mi}))),bottomFor=mi=>config(mi,v.id).clef==='bass'?18:30,maxLedger=Math.max(0,...notes.map(p=>p.pitch-bottomFor(p.mi)-8)),minLedger=Math.max(0,...notes.map(p=>bottomFor(p.mi)-p.pitch));
      const upOct=list.some(p=>p.e.ottava>0)||row.some(p=>score.measures[p.mi].octaves?.[v.id]>0),downOct=list.some(p=>p.e.ottava<0)||row.some(p=>score.measures[p.mi].octaves?.[v.id]<0),tuplet=list.some(p=>p.e.tuplet||p.e.triplet),expression=list.some(p=>p.e.expression),hasSlur=list.some(p=>p.e.slur),base=offset+100+maxLedger*6+(upOct?24:0)+(tuplet?18:0)+(expression?18:0)+(hasSlur?12:0),top=base-48,annotationY=base+Math.max(43,minLedger*6+37),lyricY=annotationY+30,rowEnd=lyricY+23+(downOct?24:0);
      if(systemTop===null)systemTop=top;const labelColor=v.id===activeVoice?'#38624f':'#7a8178';out.push(`<g data-voice="${v.id}" class="voice-label"><title>${escapeXml(v.name)}</title><text x="66" y="${top+28}" text-anchor="end" font-size="12" fill="${labelColor}" font-weight="${v.id===activeVoice?'650':'400'}">${escapeXml(v.name.length>6?v.name.slice(0,6)+'…':v.name)}</text></g>`);
      for(let l=0;l<5;l++)out.push(line(78,top+l*12,w-18,top+l*12));out.push(line(78,top,78,base,'barline'));
      const first=config(row[0].mi,v.id),firstBottom=bottomFor(row[0].mi),firstY=p=>base-(p-firstBottom)*6;out.push(drawClef(first.clef,87,base,firstBottom),signature(first.key,0,122,firstY,first.clef).html,drawMeter(first.meter,prefix-19,top));const voicePositions=[];
      bars.forEach((bar,bi)=>{const {mi,start,end,width,header,xmap}=bar,m=score.measures[mi],c=config(mi,v.id),prev=mi?config(mi-1,v.id):c,bottomPitch=bottomFor(mi),yFor=p=>base-(p-bottomPitch)*6;let beat=0;
        const positions=M.events(score,m,v.id).map((e,ei)=>{const p={e,x:xmap.get(beatKey(beat)),y:e.type==='rest'?top+24:yFor(e.pitch),beat,mi,ei,voice:v.id,base,top,annotationY,lyricY,ri,offset,end,start,bottomPitch,downOct,rowEnd,header};beat+=M.ticks(e);return p;}),beams=prepareStems(positions,c.meter);
        geometry.push({mi,voice:v.id,start,end,header,top,base,offset,rowEnd,positions,bottomPitch});
        out.push(`<g class="measure${mi===currentMeasure&&v.id===activeVoice?' current-measure':''}${selectedMeasureVoices.get(m.id)?.has(v.id)?' selected-measure':''}" data-measure="${mi}" data-part="${v.id}"><rect class="measure-click" data-mi="${mi}" data-voice="${v.id}" x="${start}" y="${offset+4}" width="${width}" height="${rowEnd-offset-8}"/>`);
        if(bi>0){let hx=start+7;if(prev.clef!==c.clef){out.push(drawClef(c.clef,hx,base,bottomPitch));hx+=38;}if(prev.key!==c.key){const sig=signature(c.key,prev.key,hx,yFor,c.clef,true);out.push(sig.html);hx+=sig.width+10;}if(prev.meter.join('/')!==c.meter.join('/'))out.push(drawMeter(c.meter,hx+12,top));}
        if(v===score.voices[0]){out.push(`<text class="measure-number" x="${start+4}" y="${top-20}">${mi+1}</text>`);if(!mi||prev.bpm!==c.bpm)out.push(`<text x="${start+28}" y="${offset+30}" font-size="11" fill="#686f65">♩ = ${c.bpm}</text>`);
          const labels=[m.expression,m.dynamic,{trill:'tr',mordent:'𝆝',turn:'𝆗'}[m.ornament]].filter(Boolean).join(' · ');if(labels)out.push(`<text x="${start+28}" y="${offset+49}" class="expression-label">${escapeXml(labels)}</text>`);out.push(drawArticulationSymbol(m.articulation,start+28+(labels?labels.length*7+16:0),offset+49));
          if(m.ending)out.push(`<g ${symbolAttrs('ending',mi)}><path d="M ${start+3} ${offset+18} V ${offset+5} H ${end-3} V ${offset+18}" fill="none" stroke="#5c635d"/><path class="symbol-hit" d="M ${start+3} ${offset+5} H ${end-3}"/><text x="${start+9}" y="${offset+18}" font-size="11">${escapeXml(m.ending)}.</text></g>`);
          if(m.navigation)out.push(`<g ${symbolAttrs('navigation',mi)}><text x="${end-7}" y="${offset+13}" text-anchor="end" font-family="Georgia,Segoe UI Symbol" font-size="${m.navigation==='segno'||m.navigation==='coda'?24:12}" font-style="italic">${navNames[m.navigation]}</text></g>`);
        }
        if(m.repeatStart){out.push(`<g ${symbolAttrs('repeatStart',mi)}><rect class="symbol-hit-box" x="${start}" y="${top-3}" width="22" height="54"/>`,line(start+3,top,start+3,base,'barline','stroke-width="3"'),line(start+9,top,start+9,base,'barline'));[top+18,top+30].forEach(y=>out.push(`<circle cx="${start+16}" cy="${y}" r="2" fill="#404940"/>`));out.push('</g>');}
        if(!M.close(beat,M.capacity(score,mi)))out.push(`<text class="measure-status" x="${end-5}" y="${lyricY+16}" text-anchor="end">${M.fmt(beat/48)} / ${M.fmt(M.capacity(score,mi)/48)} 拍</text>`);
        positions.forEach(p=>{notePositions.set(p.e.id,p);voicePositions.push(p);out.push(drawNote(p,resolved.get(p.e.id)));});drawBeams(beams,out);
        if(m.hairpins?.[v.id])out.push(`<g ${symbolAttrs('measureHairpin',mi,v.id)}>${wedgePath(start+32,end-24,annotationY+13,m.hairpins[v.id].kind)}</g>`);
        if(m.octaves?.[v.id]){const value=m.octaves[v.id],oy=value>0?offset+15:lyricY+21,label={1:'8va','-1':'8vb',2:'15ma','-2':'15mb'}[value];out.push(`<g ${symbolAttrs('measureOctave',mi,v.id)}><text x="${start+30}" y="${oy}" font-size="12" font-style="italic">${label}</text><path d="M ${start+68} ${oy-4} H ${end-14} V ${oy+(value>0?3:-11)}" fill="none" stroke="#65725f" stroke-dasharray="4 3"/><path class="symbol-hit" d="M ${start+30} ${oy-4} H ${end-14}"/></g>`);}
        out.push(line(end,top,end,base,'barline'));if(m.repeatEnd){out.push(`<g ${symbolAttrs('repeatEnd',mi)}><rect class="symbol-hit-box" x="${end-24}" y="${top-6}" width="29" height="58"/>`,line(end-6,top,end-6,base,'barline'),line(end,top,end,base,'barline','stroke-width="3"'));[top+18,top+30].forEach(y=>out.push(`<circle cx="${end-14}" cy="${y}" r="2" fill="#404940"/>`));if(v===score.voices[0]&&m.repeatEnd>2)out.push(`<text x="${end-20}" y="${top-8}" text-anchor="end" font-size="10">×${m.repeatEnd}</text>`);out.push('</g>');}else if(mi===score.measures.length-1)out.push(line(end-5,top,end-5,base,'barline'),line(end,top,end,base,'barline','stroke-width="3"'));out.push('</g>');
      });drawGroups(voicePositions,out,ri,prefix,w);lastBase=base;offset=rowEnd;
    });if(score.voices.length>1)out.push(line(74,systemTop,74,lastBase,'barline','stroke-width="2"'),`<path d="M 70 ${systemTop-4} H 65 V ${lastBase+4} H 70" fill="none" stroke="#5c635d" stroke-width="2"/>`);offset+=22;
  });drawSpans(out,prefix,w,resolved);
  $('score').innerHTML=`<svg xmlns="${NS}" style="width:${w}px;max-width:none" viewBox="0 0 ${w} ${Math.max(230,offset)}" role="img" aria-label="${escapeXml(score.title)} · ${score.voices.length} 声部">${out.join('')}<g id="ghost" class="ghost"></g></svg>`;
}
function curvePath(points,x1,x2,side,small=false){
  const a=points[0],b=points.at(-1),edge=p=>side<0?Math.min(...p.headYs)-9:Math.max(...p.headYs)+9,y1=edge(a),y2=edge(b),span=Math.max(1,x2-x1);let h=small?9:Math.min(26,10+span*.035);
  points.slice(1,-1).forEach(p=>{const t=(p.x+7-x1)/span;if(t<=.05||t>=.95)return;const bound=side<0?Math.min(...p.headYs,p.down?Infinity:p.stemEnd)-7:Math.max(...p.headYs,p.down?p.stemEnd:-Infinity)+7,linear=y1+(y2-y1)*t;h=Math.max(h,(bound-linear)*side/(3*t*(1-t)));});
  const d=`M ${x1} ${y1} C ${x1+span/3} ${y1+(y2-y1)/3+side*h} ${x1+span*2/3} ${y1+(y2-y1)*2/3+side*h} ${x2} ${y2}`;
  return `<path class="phrasing-line" data-side="${side<0?'above':'below'}" d="${d}" fill="none" stroke="#465c4b" stroke-width="1.4"/><path class="symbol-hit" d="${d}"/>`;
}
function wedgePath(x1,x2,y,kind,progress1=0,progress2=1){const opening=t=>kind==='crescendo'?t*6:(1-t)*6,a=opening(progress1),b=opening(progress2),d=`M ${x1} ${y-a} L ${x2} ${y-b} M ${x1} ${y+a} L ${x2} ${y+b}`;return `<path class="hairpin-line" d="${d}" fill="none" stroke="#333" stroke-width="1.2"/><path class="symbol-hit" d="M ${x1} ${y} H ${x2}"/>`;}
function spanParts(list){const parts=[];list.forEach(p=>{if(parts.at(-1)?.[0].ri===p.ri)parts.at(-1).push(p);else parts.push([p]);});return parts;}
function drawSpans(out,prefix,w,resolved){
  const arpeggios=new Map();notePositions.forEach(p=>{if(p.e.arpeggio&&p.e.arpeggioGroup){if(!arpeggios.has(p.e.arpeggioGroup))arpeggios.set(p.e.arpeggioGroup,[]);arpeggios.get(p.e.arpeggioGroup).push(p);}});arpeggios.forEach(g=>{const a=g[0],ax=Math.min(...g.map(p=>p.x))-50,y1=Math.min(...g.flatMap(p=>p.headYs))-9,y2=Math.max(...g.flatMap(p=>p.headYs))+9;if(g.some(p=>p.ri!==a.ri||Math.abs(p.x-a.x)>1))return;let d='M '+ax+' '+y1;for(let y=y1+2;y<=y2;y+=2)d+=' L '+(ax+Math.sin((y-y1)*Math.PI/5)*2.2)+' '+y;const arrow=a.e.arpeggio==='up'?'<path d="M '+(ax-3)+' '+(y1+3)+' L '+ax+' '+(y1-3)+' L '+(ax+3)+' '+(y1+3)+'" fill="none" stroke="#333"/>':a.e.arpeggio==='down'?'<path d="M '+(ax-3)+' '+(y2-3)+' L '+ax+' '+(y2+3)+' L '+(ax+3)+' '+(y2-3)+'" fill="none" stroke="#333"/>':'';out.push('<g '+symbolAttrs('arpeggio',a.mi,a.e.id)+'><path class="cross-staff-arpeggio" d="'+d+'" fill="none" stroke="#333"/><path class="symbol-hit" d="M '+ax+' '+y1+' V '+y2+'"/>'+arrow+'</g>');});
  score.voices.forEach(v=>{const all=score.measures.flatMap(m=>M.events(score,m,v.id)),slurs=new Map();all.forEach(e=>{if(e.slur){if(!slurs.has(e.slur))slurs.set(e.slur,[]);slurs.get(e.slur).push(notePositions.get(e.id));}});
    slurs.forEach(list=>{const points=list.filter(Boolean),side=points.filter(p=>p.down).length>=points.length/2?-1:1;spanParts(points).forEach((part,i,parts)=>{const a=part[0],b=part.at(-1),x1=i===0?a.x+7:prefix,x2=i===parts.length-1?b.x+7:w-22;out.push(`<g ${symbolAttrs('slur',a.mi,a.e.id)}>${curvePath(part,x1,x2>x1?x2:x1+18,side)}</g>`);});});
    all.forEach((e,i)=>{const a=notePositions.get(e.id),next=all[i+1],b=notePositions.get(next?.id);if(!a)return;
      if(e.tie){const side=a.down?-1:1,color=resolved.get(e.id)?.midi===resolved.get(next?.id)?.midi?'#465c4b':'#ab4137';const parts=b?spanParts([a,b]):[[a]];out.push(`<g ${symbolAttrs('tie',a.mi,e.id)} style="color:${color}">`);parts.forEach((part,j)=>{const x1=j===0?a.x+12:prefix,x2=b&&j===parts.length-1?b.x+2:w-22;out.push(curvePath(part,x1,Math.max(x1+14,x2),side,true));});out.push('</g>');}
      for(const kind of ['hairpin','glissando']){if(!e[kind])continue;const targetId=e[kind==='hairpin'?'hairpinTo':'glissTo'],endIndex=targetId?all.findIndex(n=>n.id===targetId):i+1,target=notePositions.get(all[endIndex]?.id);if(!target||endIndex<=i)continue;const ps=all.slice(i,endIndex+1).map(n=>notePositions.get(n.id)).filter(Boolean);out.push(`<g ${symbolAttrs(kind,a.mi,e.id)}>`);spanParts(ps).forEach((part,j,parts)=>{const p=part[0],q=part.at(-1),x1=j===0?p.x+22:prefix,x2=j===parts.length-1?q.x-8:w-22;if(x2<=x1)return;if(kind==='hairpin')out.push(wedgePath(x1,x2,p.annotationY+13,e.hairpin,j/parts.length,(j+1)/parts.length));else{const y1=p.y-2,y2=q.y-2;let d=`M ${x1} ${y1}`;if(e.glissando==='wavy'){const steps=Math.ceil((x2-x1)/3);for(let k=1;k<=steps;k++){const t=k/steps;d+=` L ${x1+(x2-x1)*t} ${y1+(y2-y1)*t+Math.sin(t*(x2-x1)*Math.PI/5)*2}`;}}else d+=` L ${x2} ${y2}`;out.push(`<path class="glissando-line" d="${d}" fill="none" stroke="#333" stroke-width="1.1"/><path class="symbol-hit" d="${d}"/>`);}});out.push('</g>');}
    });
  });
}
function drawGroups(pos,out){
  const groups=new Map();pos.forEach(p=>{if(p.e.tuplet){if(!groups.has(p.e.tuplet.id))groups.set(p.e.tuplet.id,[]);groups.get(p.e.tuplet.id).push(p);}});
  groups.forEach(g=>{const t=g[0].e.tuplet,down=g.every(p=>p.down),y=down?Math.max(...g.map(p=>p.stemEnd))+14:Math.min(...g.map(p=>p.stemEnd))-13,x1=g[0].x-3,x2=g.at(-1).x+17,mid=(x1+x2)/2,hook=down?-5:5;out.push(`<g ${symbolAttrs('tuplet',g[0].mi,g[0].e.id)}><title>${t.count} 个音均分 ${t.total} 个四分拍</title><path d="M ${x1} ${y+hook} V ${y} H ${mid-10} M ${mid+10} ${y} H ${x2} V ${y+hook}" fill="none" stroke="#454c46"/><path class="symbol-hit" d="M ${x1} ${y} H ${x2}"/><text x="${mid}" y="${y+4}" text-anchor="middle" font-size="12" font-style="italic">${t.count}</text></g>`);});
  for(let i=0;i<pos.length;i++){const p=pos[i];if(p.e.triplet&&!p.e.tuplet){let end=i;while(end+1<pos.length&&pos[end+1].e.triplet&&end-i<2)end++;out.push(`<text x="${(p.x+pos[end].x)/2}" y="${Math.min(...pos.slice(i,end+1).map(p=>p.stemEnd))-12}" font-size="12">3</text>`);i=end;}if(!p.e.ottava)continue;let end=i;while(end+1<pos.length&&pos[end+1].e.ottava===p.e.ottava)end++;const label={1:'8va','-1':'8vb',2:'15ma','-2':'15mb'}[p.e.ottava],y=p.e.ottava>0?p.offset+15:p.lyricY+21,x1=p.x-9,x2=pos[end].x+23;out.push(`<g ${symbolAttrs('ottava',p.mi,p.e.id)}><text x="${x1}" y="${y}" font-size="12" font-style="italic">${label}</text><path d="M ${x1+32} ${y-4} H ${x2} V ${y+(p.e.ottava>0?3:-11)}" fill="none" stroke="#65725f" stroke-dasharray="4 3"/><path class="symbol-hit" d="M ${x1} ${y-4} H ${x2}"/></g>`);i=end;}
}

function drawArticulationSymbol(kind,x,y){let mark='';if(kind==='staccato')mark=`<circle cx="${x+7}" cy="${y-4}" r="2" fill="#333"/>`;if(kind==='staccatissimo')mark=`<path d="M ${x+3} ${y-9} L ${x+11} ${y-9} L ${x+7} ${y} Z" fill="#333"/>`;if(kind==='accent')mark=`<path d="M ${x+1} ${y-8} L ${x+14} ${y-4} L ${x+1} ${y}" fill="none" stroke="#333"/>`;if(kind==='marcato')mark=`<path d="M ${x+1} ${y} L ${x+7} ${y-9} L ${x+14} ${y}" fill="none" stroke="#333"/>`;if(kind==='tenuto'||kind==='portato')mark=line(x,y-4,x+14,y-4,'staff-line','stroke-width="2"');if(kind==='portato')mark+=`<circle cx="${x+7}" cy="${y+2}" r="1.8" fill="#333"/>`;if(kind==='fermata')mark=glyph('\uE4C0',x,y,38);if(kind==='breath')mark=glyph('\uE4CE',x,y,32);if(kind==='legato')mark=`<path d="M ${x} ${y} Q ${x+12} ${y-12} ${x+24} ${y}" fill="none" stroke="#333" stroke-width="1.4"/>`;if(kind==='pizzicato'||kind==='arco')mark=`<text x="${x}" y="${y}" class="expression-label">${kind==='pizzicato'?'pizz.':'arco'}</text>`;return mark?`<g class="articulation-symbol" data-articulation="${kind}">${mark}</g>`:'';}
function drawNote(p,n){
  const {e,x,y,base,top,annotationY,lyricY}=p,name=n.tones.map(t=>t.name).join('、')||'休止符';let out=`<g class="note-group ${selectedNotes.has(e.id)?'selected':''}" data-id="${e.id}" data-note-voice="${e.voice}" role="button" aria-label="${escapeXml(name)}，${M.fmt(M.ticks(e)/48)} 拍"><title>${escapeXml(n.voiceName+' · '+name)} · ${M.fmt(M.ticks(e)/48)} 拍</title><rect class="note-halo" x="${x-14}" y="${Math.min(...p.headYs)-12}" width="42" height="${Math.max(...p.headYs)-Math.min(...p.headYs)+24}" rx="6"/>`;p.headBoxes=[];
  if(e.type==='rest'){const ry=e.duration===1?top+12:top+24;out+=glyph(String.fromCodePoint(0xE4E3+Math.log2(e.duration)),x-6,ry,48,'music-text note-ink');p.headBoxes.push({x:x+7,y:ry,toneIndex:0,rest:true});}
  else{
    const sorted=M.tones(e).map((t,toneIndex)=>({...t,toneIndex,y:base-(t.pitch-p.bottomPitch)*6})).sort((a,b)=>a.pitch-b.pitch);let shifted=false;
    sorted.forEach((t,i)=>{shifted=i>0&&t.pitch-sorted[i-1].pitch===1?!shifted:false;const hx=x+(shifted?(p.down?-12:12):0),hy=t.y;p.headBoxes.push({x:hx+7,y:hy,pitch:t.pitch,toneIndex:t.toneIndex});
      if(hy>base)for(let ly=base+12;ly<=hy+1;ly+=12)out+=line(hx-4,ly,hx+19,ly,'note-ink');if(hy<top)for(let ly=top-12;ly>=hy-1;ly-=12)out+=line(hx-4,ly,hx+19,ly,'note-ink');
      if(t.accidental!==null)out+=glyph({'-2':'\uE264','-1':'\uE260','0':'\uE261','1':'\uE262','2':'\uE263'}[t.accidental],x-22-(i%2)*10,hy,48,'music-text note-ink');
      out+=`<g class="note-head" data-tone-index="${t.toneIndex}">${glyph(e.duration===1?'\uE0A2':e.duration===2?'\uE0A3':'\uE0A4',hx,hy,48,'music-text note-ink')}<ellipse class="note-head-hit" cx="${hx+7}" cy="${hy}" rx="8" ry="5.5"/></g>`;
      for(let dot=0;dot<M.dots(e);dot++)out+=`<circle class="augmentation-dot note-ink" cx="${x+24+dot*7+(shifted&&!p.down?12:0)}" cy="${(hy-base)%12===0?hy-6:hy}" r="1.9"/>`;
    });
    if(e.duration!==1){out+=line(p.stemX,p.stemStart,p.stemX,p.stemEnd,'note-ink note-stem','stroke-width="1.3"');if(e.duration>=8&&!p.beamed)out+=glyph(String.fromCodePoint(0xE240+2*(Math.log2(e.duration)-3)+(p.down?1:0)),p.stemX,p.stemEnd,48,'music-text note-ink');}
    const ay=p.down?Math.min(...p.headYs)-18:Math.max(...p.headYs)+20;out+=drawArticulationSymbol(e.articulation,x,ay+4);
    if(e.ornament)out+=glyph({trill:'\uE566',mordent:'\uE56D',turn:'\uE567'}[e.ornament],x-3,Math.min(...p.headYs)-33,35);
    if(e.arpeggio&&!e.arpeggioGroup){const ax=x-35-(e.accidental!==null?15:0),a=Math.min(...p.headYs)-9,b=Math.max(...p.headYs)+9;let d=`M ${ax} ${a}`;for(let yy=a+2;yy<=b;yy+=2)d+=` L ${ax+Math.sin((yy-a)*Math.PI/5)*2.2} ${yy}`;out+=`<g ${symbolAttrs('arpeggio',p.mi,e.id)}><path d="${d}" fill="none" stroke="#333" stroke-width="1.2"/><path class="symbol-hit" d="M ${ax} ${a} V ${b}"/>${e.arpeggio==='up'?`<path d="M ${ax-3} ${a+3} L ${ax} ${a-3} L ${ax+3} ${a+3}" fill="none" stroke="#333"/>`:e.arpeggio==='down'?`<path d="M ${ax-3} ${b-3} L ${ax} ${b+3} L ${ax+3} ${b-3}" fill="none" stroke="#333"/>`:''}</g>`;}
    if(e.graceNotes?.length){out+=`<g ${symbolAttrs('grace',p.mi,e.id)}>`;e.graceNotes.forEach((g,i)=>{const gx=x-8-(e.graceNotes.length-i)*18,gy=base-(g.pitch-p.bottomPitch)*6,sx=gx+8.5,sy=gy-25;
      if(gy>base)for(let ly=base+12;ly<=gy+1;ly+=12)out+=line(gx-3,ly,gx+13,ly,'note-ink');if(gy<top)for(let ly=top-12;ly>=gy-1;ly-=12)out+=line(gx-3,ly,gx+13,ly,'note-ink');if(g.accidental!==null)out+=glyph({'-2':'\uE264','-1':'\uE260','0':'\uE261','1':'\uE262','2':'\uE263'}[g.accidental],gx-10,gy,28,'music-text note-ink');out+=glyph('\uE0A4',gx,gy,30,'music-text note-ink')+line(sx,gy,sx,sy,'note-ink','stroke-width="1"');
      if(e.graceNotes.length===1)out+=glyph(String.fromCodePoint(0xE240+2*(Math.log2(g.duration)-3)),sx,sy,30,'music-text note-ink');else if(i<e.graceNotes.length-1){const next=e.graceNotes[i+1],ny=base-(next.pitch-p.bottomPitch)*6-25;out+=`<path class="beam-ink" d="M ${sx} ${sy} L ${sx+18} ${ny} L ${sx+18} ${ny+3} L ${sx} ${sy+3} Z"/>`;}if(g.slash)out+=line(sx-4,sy+11,sx+8,sy+4,'note-ink','stroke-width="1"');});out+='</g>';}
  }
  if(e.type==='rest')for(let dot=0;dot<M.dots(e);dot++)out+=`<circle class="note-ink" cx="${x+21+dot*7}" cy="${y}" r="1.9"/>`;
  if(e.exactTicks!==null&&e.exactTicks!==undefined)out+=`<text x="${x+7}" y="${annotationY-14}" text-anchor="middle" font-size="8" fill="#7f887a">${M.fmt(M.ticks(e)/48)}拍</text>`;
  if(e.dynamic)out+=`<text x="${x+7}" y="${annotationY}" text-anchor="middle" class="notation-label">${escapeXml(e.dynamic)}</text>`;
  if(e.expression)out+=`<text x="${x+7}" y="${Math.min(...p.headYs,top)-43}" text-anchor="middle" class="expression-label">${escapeXml({crescendo:'cresc.',diminuendo:'dim.'}[e.expression]||e.expression)}</text>`;
  if(e.lyric&&e.type==='note')out+=`<text x="${x+7}" y="${lyricY}" text-anchor="middle" class="lyrics">${escapeXml(e.lyric)}</text>`;return out+'</g>';
}
function hideMenu(){clearTimeout(hideMenuTimer);hideMenuTimer=null;finishLyricEdit();$('contextMenu').hidden=true;menuTarget=null;}
function cancelHideMenu(){clearTimeout(hideMenuTimer);hideMenuTimer=null;}
function scheduleHideMenu(){if($('contextMenu').hidden||hideMenuTimer!==null)return;hideMenuTimer=setTimeout(()=>{hideMenuTimer=null;if(!$('contextMenu').matches(':hover'))hideMenu();},120);}
function isSelectedTarget(t){return t?.type==='note'?selectedNotes.has(t.id):t?.type==='measure'?!!selectedMeasureVoices.get(score.measures[t.mi]?.id)?.has(t.voice):t?.type==='symbol'?selectedSymbols.has(symbolKey(t)):false;}
function targetAt(element){const sym=element.closest('[data-symbol-kind]');if(sym)return {type:'symbol',kind:sym.dataset.symbolKind,mi:+sym.dataset.symbolMi,id:sym.dataset.symbolId||''};const note=element.closest('[data-id]');if(note){const f=findNote(note.dataset.id);return f?{type:'note',id:f.e.id,mi:f.mi}:null;}const bar=element.closest('.measure-click');return bar?{type:'measure',mi:+bar.dataset.mi,voice:bar.dataset.voice}:null;}
function hoverTargetAt(event){if(mode!=='select'||symbolTool)return null;const t=targetAt(event.target);if(t?.type==='note'){const p=notePositions.get(t.id),point=coordinates(event);if(!p||!point)return null;const ys=[...p.headYs];if(p.e.duration!==1&&p.e.type==='note')ys.push(p.stemEnd);if(point.x<p.x-26||point.x>p.x+35||point.y<Math.min(...ys)-12||point.y>Math.max(...ys)+12)return null;}return t;}
function showMenu(t,x,y){if(mode!=='select'||symbolTool){hideMenu();return;}if(!isSelectedTarget(t)){scheduleHideMenu();return;}cancelHideMenu();const key=t.type==='symbol'?symbolKey(t):t.type+':'+(t.id||t.mi)+':'+(t.voice||''),old=menuTarget;menuTarget=t;menuTarget._key=key;const menu=$('contextMenu');if(menu.hidden||old?._key!==key){buildMenu();menu.hidden=false;const width=menu.offsetWidth,left=x+12+width<=window.innerWidth-8?x+12:x-width-12;menu.style.left=Math.max(8,Math.min(left,window.innerWidth-width-8))+'px';menu.style.top=Math.max(8,Math.min(y+8,window.innerHeight-menu.offsetHeight-84))+'px';}}
function menuChoice(label,attr,value,active=false){return `<button class="menu-choice${active?' active':''}" ${attr}="${escapeXml(JSON.stringify(value))}">${escapeXml(label)}</button>`;}
const propChoice=(k,v,label)=>menuChoice(label,`data-prop="${k}" data-value`,v);
const settingChoice=(k,v,label)=>menuChoice(label,`data-setting="${k}" data-value`,v);
const actionChoice=(action,label)=>`<button class="menu-choice" data-action="${action}">${escapeXml(label)}</button>`;
function category(label,html){return `<div class="menu-category"><button class="menu-category-title" aria-expanded="false">${escapeXml(label)}<span aria-hidden="true">›</span></button><div class="submenu">${html}</div></div>`;}
function buildMenu(){if(!menuTarget||!isSelectedTarget(menuTarget)){hideMenu();return;}const notes=selectedList(),bars=score.measures.filter(m=>selectedMeasures.has(m.id)),f=getSelected(),c=config();let out='';
  if(notes.length)out+=category('升降记号',[[null,'由调号与小节决定'],[1,'♯ 升'],[-1,'♭ 降'],[0,'♮ 还原'],[2,'𝄪 重升'],[-2,'𝄫 重降']].map(([v,l])=>propChoice('accidental',v,l)).join(''));
  if(notes.length)out+=category('时值',[1,2,4,8,16,32,64,128].map(d=>propChoice('duration',d,`${d} 分音符`)).join('')+'<div class="menu-divider"></div>'+[0,1,2,3].map(d=>propChoice('dots',d,['无附点','附点 ·','复附点 ··','三附点 ···'][d])).join(''));
  if(bars.length){out+=category('调号',(c.mode==='minor'?M.MINOR:M.MAJOR).map((n,i)=>settingChoice('key',i-7,n+(c.mode==='minor'?' 小调':' 大调'))).join(''));out+=category('调式',settingChoice('mode','major','大调')+settingChoice('mode','minor','小调'));out+=category('拍号／节奏',meterValues.map(v=>settingChoice('meter',v.split('/').map(Number),v)).join(''));out+=category('速度',`<label class="menu-field">♩ / 分钟<input id="menuBpm" type="number" min="30" max="240" value="${c.bpm}"></label>`+actionChoice('setBpm','设置速度…'));out+=category('当前声部谱号',Object.entries(clefNames).map(([v,l])=>settingChoice('clef',v,l)).join(''));}
  if(notes.length||bars.length){out+=category('力度',propChoice('dynamic','','取消力度')+dynamics.map(v=>propChoice('dynamic',v,v)).join(''));out+=category('表情',propChoice('expression','','取消表情')+M.EXPRESSIONS.map(([v,l])=>propChoice('expression',v,`${v} · ${l}`)).join(''));out+=category('奏法',propChoice('articulation','','取消奏法')+articulations.map(([v,l])=>propChoice('articulation',v,l)).join(''));out+=category('装饰音',propChoice('ornament','','取消装饰音')+[['trill','tr · 颤音'],['mordent','波音'],['turn','回音']].map(([v,l])=>propChoice('ornament',v,l)).join(''));out+=category('八度线',[[0,'取消八度线'],[1,'8va · 高八度'],[-1,'8vb · 低八度'],[2,'15ma · 高两八度'],[-2,'15mb · 低两八度']].map(([v,l])=>menuChoice(l,'data-menu-symbol="ottava" data-value',v)).join(''));}
  if(notes.length){out+=category('连线',menuChoice('添加延音线','data-menu-symbol="tie" data-value',true)+propChoice('tie',false,'取消延音线')+menuChoice('添加圆滑线','data-menu-symbol="slur" data-value','add')+actionChoice('removeSlur','取消圆滑线'));out+=category('音高',actionChoice('pitchUp','↑ 上移一个谱位')+actionChoice('pitchDown','↓ 下移一个谱位'));const lyric=notes.find(e=>e.id===selected&&e.type==='note')||notes.find(e=>e.type==='note');if(lyric)out+=category('歌词',`<label class="menu-field">歌词<input id="menuLyric" data-lyric-id="${lyric.id}" value="${escapeXml(lyric.lyric)}" maxlength="80" placeholder="输入歌词，Enter 保存"></label>`+actionChoice('saveLyric','保存歌词'));}
  if(bars.length)out+=category('反复／返回',menuChoice('𝄆 反复起点','data-menu-symbol="repeatStart" data-value',true)+menuChoice('取消反复起点','data-menu-symbol="repeatStart" data-value',false)+[0,2,3,4,5,6,7,8].map(v=>menuChoice(v?`𝄇 共 ${v} 遍`:'取消反复终点','data-menu-symbol="repeatEnd" data-value',v)).join('')+['','1','2','3','1,2','2,3'].map(v=>menuChoice(v?`${v}. 结尾`:'取消结尾','data-menu-symbol="ending" data-value',v)).join('')+Object.entries(navNames).map(([v,l])=>menuChoice(l,'data-menu-symbol="navigation" data-value',v)).join('')+menuChoice('取消返回标记','data-menu-symbol="navigation" data-value',''));
  if(notes.length||bars.length)out+=category('渐强／渐弱',menuChoice('＜','data-menu-symbol="hairpin" data-value','crescendo')+menuChoice('＞','data-menu-symbol="hairpin" data-value','diminuendo')+propChoice('expression','cresc.','cresc.')+propChoice('expression','dim.','dim.')+actionChoice('clearHairpins','取消渐强／渐弱线'));
  if(notes.length){out+=category('琶音',menuChoice('𝆃','data-menu-symbol="arpeggio" data-value','plain')+menuChoice('𝆃 ↑','data-menu-symbol="arpeggio" data-value','up')+menuChoice('𝆃 ↓','data-menu-symbol="arpeggio" data-value','down')+propChoice('arpeggio','','取消琶音'));out+=category('滑音',menuChoice('╱','data-menu-symbol="glissando" data-value','straight')+menuChoice('∿','data-menu-symbol="glissando" data-value','wavy')+propChoice('glissando','','取消滑音'));out+=category('符梁',actionChoice('beamAuto','按拍自动连接')+actionChoice('beamJoin','连接所选连续音符')+actionChoice('beamBreak','断开所选符梁'));if(f?.e.chord?.length)out+=category('和弦',actionChoice('removeChordTone','删除所点的和弦音'));if(notes.some(e=>e.graceNotes?.length))out+=category('倚音',actionChoice('removeGraces','删除所选音符的倚音'));}
  if(selectedSymbols.size){const t=[...selectedSymbols.values()].at(-1);let html='';if(t.kind==='hairpin'||t.kind==='measureHairpin')html=['crescendo','diminuendo'].map((v,i)=>menuChoice(i?'＞':'＜','data-symbol-value',v)).join('');else if(t.kind==='glissando')html=['straight','wavy'].map((v,i)=>menuChoice(i?'∿':'╱','data-symbol-value',v)).join('');else if(t.kind==='arpeggio')html=['plain','up','down'].map((v,i)=>menuChoice(['𝆃','𝆃 ↑','𝆃 ↓'][i],'data-symbol-value',v)).join('');else if(t.kind==='ottava'||t.kind==='measureOctave')html=[[0,'取消八度线'],[1,'8va'],[-1,'8vb'],[2,'15ma'],[-2,'15mb']].map(([v,l])=>menuChoice(l,'data-symbol-value',v)).join('');else if(t.kind==='repeatEnd')html=[2,3,4,5,6,7,8].map(v=>menuChoice(`共 ${v} 遍`,'data-symbol-value',v)).join('');else if(t.kind==='ending')html=['1','2','3','1,2','2,3'].map(v=>menuChoice(`${v}. 结尾`,'data-symbol-value',v)).join('');else if(t.kind==='navigation')html=Object.entries(navNames).map(([v,l])=>menuChoice(l,'data-symbol-value',v)).join('');else if(t.kind==='tuplet'){const e=findNote(t.id)?.e;html=`<label class="menu-field">连音数量<input id="menuTupletCount" type="number" min="2" max="32" value="${e?.tuplet?.count||3}"></label><label class="menu-field">总时值（四分拍）<input id="menuTupletTotal" type="number" min="0.125" max="32" step="0.125" value="${e?.tuplet?.total||1}"></label>`+actionChoice('updateTuplet','修改连音组');}out+=category('所选符号',html+actionChoice('removeSymbols','删除所选符号'));}
  out+=category('删除',actionChoice('delete','删除所选对象'));$('contextMenu').innerHTML=out;
}
function openCategory(cat){const menu=$('contextMenu');menu.querySelectorAll('.menu-category').forEach(e=>{e.classList.toggle('open',e===cat);e.querySelector('.menu-category-title').setAttribute('aria-expanded',String(e===cat));});const sub=cat.querySelector('.submenu'),r=cat.getBoundingClientRect(),mr=menu.getBoundingClientRect();sub.style.left=Math.max(8,Math.min(mr.right-1,window.innerWidth-sub.offsetWidth-8))+'px';sub.style.top=Math.max(8,Math.min(r.top,window.innerHeight-sub.offsetHeight-82))+'px';}
$('contextMenu').addEventListener('pointerover',e=>{cancelHideMenu();const cat=e.target.closest('.menu-category');if(cat&&!cat.classList.contains('open'))openCategory(cat);});$('contextMenu').addEventListener('pointerleave',scheduleHideMenu);
document.addEventListener('pointerover',e=>{if(!$('score').contains(e.target)&&!$('contextMenu').contains(e.target))hideMenu();});window.addEventListener('blur',hideMenu);
function setAnnotation(k,v){if(['dynamic','expression','articulation','ornament'].includes(k))commit(()=>{selectedList().forEach(e=>e[k]=v);score.measures.filter(m=>selectedMeasures.has(m.id)).forEach(m=>m[k]=v);});else setProp(k,v);}
function saveLyric(){const input=$('menuLyric');if(!input)return;const f=findNote(input.dataset.lyricId),value=input.value;if(f)commit(()=>f.e.lyric=value);}
function finishLyricEdit(){if(lyricEditBefore!==null&&lyricEditBefore!==snapshot()){undoStack.push(lyricEditBefore);if(undoStack.length>120)undoStack.shift();redoStack=[];}lyricEditBefore=null;}
$('contextMenu').addEventListener('focusin',e=>{if(e.target.id==='menuLyric')lyricEditBefore=snapshot();});
$('contextMenu').addEventListener('input',e=>{if(e.target.id!=='menuLyric')return;const f=findNote(e.target.dataset.lyricId);if(f){f.e.lyric=e.target.value;renderScore();save();}});
$('contextMenu').addEventListener('focusout',e=>{if(e.target.id==='menuLyric'){finishLyricEdit();syncTools();}});
$('contextMenu').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.classList.contains('menu-category-title')){openCategory(b.parentElement);return;}if(b.dataset.setting){requestSetting(b.dataset.setting,JSON.parse(b.dataset.value));return;}if(b.dataset.prop){setAnnotation(b.dataset.prop,JSON.parse(b.dataset.value));return;}if(b.dataset.menuSymbol){useSymbol(b.dataset.menuSymbol,JSON.parse(b.dataset.value),b.textContent);return;}if(b.hasAttribute('data-symbol-value')){editSymbols(JSON.parse(b.dataset.symbolValue));return;}const action=b.dataset.action;if(action==='beamAuto')setBeaming('auto');if(action==='beamJoin')setBeaming('join');if(action==='beamBreak')setBeaming('break');if(action==='removeChordTone')removeChordTone();if(action==='removeGraces')commit(()=>selectedList().forEach(e=>e.graceNotes=[]));if(action==='clearHairpins')commit(()=>{selectedList().forEach(e=>{e.hairpin='';e.hairpinTo='';});score.measures.filter(m=>selectedMeasures.has(m.id)).forEach(m=>selectedMeasureVoices.get(m.id)?.forEach(v=>delete m.hairpins?.[v]));});if(action==='delete')deleteSelected();if(action==='pitchUp')movePitch(1);if(action==='pitchDown')movePitch(-1);if(action==='setBpm')requestSetting('bpm',Number($('menuBpm').value));if(action==='saveLyric')saveLyric();if(action==='removeSlur')commit(()=>{const ids=new Set(selectedList().map(e=>e.slur).filter(Boolean));score.measures.flatMap(m=>m.events).filter(e=>ids.has(e.slur)).forEach(e=>e.slur='');});if(action==='removeSymbols')commit(()=>{selectedSymbols.forEach(removeSymbol);selectedSymbols.clear();hideMenu();});if(action==='updateTuplet')updateTupletSymbols();});
$('contextMenu').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='menuLyric'){e.preventDefault();saveLyric();}});
$('contextMenu').addEventListener('change',e=>{if(e.target.id==='menuLyric')saveLyric();});
function requestSetting(k,value){if(k==='bpm'&&(!Number.isFinite(value)||value<30||value>240)){toast('速度应在 30–240 之间。');syncSettings();return;}hideMenu();const chosen=score.measures.map((m,i)=>selectedMeasures.has(m.id)?i:-1).filter(i=>i>=0),indices=chosen.length?chosen:[currentMeasure],start=Math.min(...indices);pendingScope={k,value,indices,start,voice:activeVoice};$('scopeDescription').textContent=`${{key:'调号',mode:'调式',meter:'拍号',bpm:'速度',clef:'谱号'}[k]}修改 · 第 ${start+1} 小节${indices.length>1?'；“当前小节”会修改全部选中的小节':''}`;$('scopeDialog').showModal();}
function applyScope(following){const p=pendingScope;pendingScope=null;$('scopeDialog').close();if(!p)return;commit(()=>{const indices=following?score.measures.map((m,i)=>i).filter(i=>i>=p.start):p.indices;indices.forEach(mi=>{const m=score.measures[mi];if(p.k==='clef'){m.clefs??={};m.clefs[p.voice]=p.value;}else m[p.k]=Array.isArray(p.value)?[...p.value]:p.value;});});}
$('scopeCurrent').onclick=()=>applyScope(false);$('scopeFollowing').onclick=()=>applyScope(true);$('cancelScope').onclick=()=>{pendingScope=null;$('scopeDialog').close();syncSettings();};$('scopeDialog').addEventListener('cancel',()=>{pendingScope=null;syncSettings();});

function finishMeasure(mi=currentMeasure,vid=activeVoice){const m=score.measures[mi];if(m)M.events(score,m,vid).forEach(e=>e.positionRatio=null);}
function finishCompleteMeasures(){score.measures.forEach((m,mi)=>score.voices.forEach(v=>{const es=M.events(score,m,v.id);if(M.close(es.reduce((a,e)=>a+M.ticks(e),0),M.capacity(score,mi)))es.forEach(e=>e.positionRatio=null);}));}
function focusMeasure(mi,vid){if(currentMeasure!==mi||activeVoice!==vid)finishMeasure();currentMeasure=mi;activeVoice=vid;}
function inputDefaults(){return {duration:defaults.duration,dots:defaults.dots,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false,triplet:false};}
function addChordTone(id,pitch){const f=findNote(id);if(!f)return;focusMeasure(f.mi,f.e.voice);clearSelection();commit(()=>{if(f.e.type==='rest'){f.e.type='note';f.e.pitch=pitch;f.e.chord=[];f.e.placeholder=false;}else{if(M.tones(f.e).some(t=>t.pitch===pitch))return;f.e.chord??=[];if(f.e.chord.length>=31)throw Error('单个和弦最多 32 个音。');f.e.chord.push({pitch,accidental:null});}selected=f.e.id;selectedNotes.add(f.e.id);});}
function addGraceAt(g,point,t){const anchor=t?.type==='note'?notePositions.get(t.id):g.positions.filter(p=>p.e.type==='note').sort((a,b)=>Math.abs(a.x-point.x)-Math.abs(b.x-point.x))[0];if(!anchor||anchor.e.type!=='note'){toast('请先输入主音，再选择倚音并点击主音左侧的谱位。');return;}const pitch=Math.max(0,Math.min(66,g.bottomPitch+Math.round((g.base-point.y)/6)));commit(()=>{anchor.e.graceNotes??=[];if(anchor.e.graceNotes.length>=16)throw Error('每个主音最多 16 个倚音。');anchor.e.graceNotes.push({id:M.id(),pitch,accidental:null,duration:[8,16,32].includes(defaults.duration)?defaults.duration:8,slash:$('graceInput').value==='slashed'});});}
function headHit(p,point){return p?.headBoxes?.find(h=>Math.abs(h.x-point.x)<=8.5&&Math.abs(h.y-point.y)<=(h.rest?13:5.5));}
function scoreClick(e){
  hideMenu();menuArmPoint={x:e.clientX,y:e.clientY};const t=targetAt(e.target),add=e.ctrlKey||e.metaKey,point=coordinates(e);
  if(symbolTool&&t){placeSymbol(t);return;}
  const label=e.target.closest('.voice-label');if(label){finishMeasure();activeVoice=label.dataset.voice;clearSelection();stop();render();return;}
  if(!point)return;
  if(mode==='select'||add){if(t?.type==='symbol')selectSymbol(t,add);else if(t?.type==='note')select(t.id,add,headHit(notePositions.get(t.id),point)?.toneIndex||0);else if(t?.type==='measure')selectMeasure(t.mi,t.voice,add);$('score').focus({preventScroll:true});return;}
  if(t?.type==='symbol'){selectSymbol(t,add);return;}
  const g=t?.type==='note'?geometry.find(g=>g.mi===t.mi&&g.voice===findNote(t.id)?.e.voice):t?.type==='measure'?geometry.find(g=>g.mi===t.mi&&g.voice===t.voice):null;if(!g)return;focusMeasure(g.mi,g.voice);
  if($('graceInput').value){addGraceAt(g,point,t);return;}
  const pitch=Math.max(0,Math.min(66,g.bottomPitch+Math.round((g.base-point.y)/6)));
  if(t.type==='note'){const p=notePositions.get(t.id);if(headHit(p,point))cycleNote(t.id);else if(point.y>=g.top-72&&point.y<=g.base+72)addChordTone(t.id,pitch);$('score').focus({preventScroll:true});return;}
  const at=g.positions.find(p=>!p.e.placeholder&&(headHit(p,point)||Math.abs(p.x+7-point.x)<=17));if(at){if(headHit(at,point))cycleNote(at.e.id);else addChordTone(at.e.id,pitch);return;}
  const following=g.positions.find(n=>point.x<n.x&&!n.e.placeholder),n=M.event(pitch,{...inputDefaults(),voice:activeVoice,type:'note',entryAnchor:true,positionRatio:positionRatio(g,point.x)});clearSelection();commit(()=>{clearPlaceholders(currentMeasure,activeVoice);const arr=score.measures[currentMeasure].events,idx=following?arr.findIndex(e=>e.id===following.e.id):arr.length;arr.splice(idx,0,n);selected=n.id;selectedNotes.add(n.id);});$('score').focus({preventScroll:true});
}
function setBeaming(action){commit(()=>{const list=selectedList(),gid=action==='join'?M.id():'';list.forEach(e=>{e.beamGroup=gid;e.beamBreak=action==='break';});});}
function removeChordTone(){const f=getSelected();if(!f||!f.e.chord?.length)return;const index=selectedToneIndices.get(f.e.id)||0;commit(()=>{if(index)f.e.chord.splice(index-1,1);else{const next=f.e.chord.shift();f.e.pitch=next.pitch;f.e.accidental=next.accidental;}selectedToneIndices.set(f.e.id,0);});}
function playbackNotes(t){return t.notes.flatMap(n=>{if(n.midi===null)return [n];const gs=n.graces||[],steal=Math.min(n.seconds*(gs.some(g=>!g.slash)?.5:.25),gs.length*.09),per=gs.length?steal/gs.length:0,graces=gs.map((g,i)=>({...n,...g,start:n.start+i*per,seconds:per,validTie:false,continuation:false,articulation:'',grace:true})),tones=n.tones.map((tone,i)=>{const rank=[...n.tones].sort((a,b)=>a.midi-b.midi).findIndex(p=>p.toneIndex===tone.toneIndex),delay=n.e.arpeggio?Math.min(n.seconds*.15,.025*(n.e.arpeggio==='down'?n.tones.length-1-rank:rank)):0;return {...n,...tone,start:n.start+steal+delay,seconds:Math.max(.015,n.seconds-steal-delay)};});return [...graces,...tones];});}
function coordinates(event){const svg=$('score').querySelector('svg');if(!svg)return null;const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function clearPlaceholders(mi,voice){score.measures[mi].events=score.measures[mi].events.filter(e=>!(e.voice===voice&&e.placeholder));}
function positionRatio(g,x){return Math.max(0,Math.min(1,(x-g.start-g.header-26)/Math.max(1,g.end-g.start-g.header-58)));}
function cycleNote(id){const f=findNote(id);if(!f)return;focusMeasure(f.mi,f.e.voice);const pos=notePositions.get(id),g=geometry.find(g=>g.mi===f.mi&&g.voice===f.e.voice);clearSelection();commit(()=>{if(f.e.type==='note'){Object.assign(f.e,{type:'rest',chord:[],graceNotes:[],accidental:null,arpeggio:'',arpeggioGroup:'',glissando:'',glissTo:'',hairpin:'',hairpinTo:'',slur:'',tie:false,dynamic:'',expression:'',articulation:'',ornament:'',entryAnchor:true});if(g&&pos)f.e.positionRatio=positionRatio(g,pos.x);selected=id;selectedNotes.add(id);}else score.measures[f.mi].events.splice(f.ei,1);});}
function betweenNotes(a,b){if(a.voice!==b.voice)return [a,b];const all=score.measures.flatMap(m=>M.events(score,m,a.voice)),i=all.indexOf(a),j=all.indexOf(b);return all.slice(Math.min(i,j),Math.max(i,j)+1);}
const measureSymbolKinds=['repeatStart','repeatEnd','ending','navigation'];
function applySymbolTo(kind,value,list,mis=[]){
  if(measureSymbolKinds.includes(kind)){mis.forEach(mi=>score.measures[mi][kind]=value);return;}
  if(kind==='ottava'){list.forEach(e=>e.ottava=Number(value));mis.forEach(mi=>{score.measures[mi].octaves??={};score.measures[mi].octaves[activeVoice]=Number(value);});}
  if(kind==='tie')list.forEach(e=>e.tie=!!value);
  if(kind==='slur'){const gid=M.id();list.forEach(e=>e.slur=value==='add'?gid:'');}
  if(kind==='arpeggio'){const groups=new Map(),ids=new Set(list.map(e=>e.id));M.resolved(score).filter(n=>ids.has(n.e.id)).forEach(n=>{const key=n.mi+':'+beatKey(n.beat);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(n);});groups.forEach(g=>{const gid=new Set(g.map(n=>n.voice)).size>1?M.id():'';g.forEach(n=>{n.e.arpeggio=value;n.e.arpeggioGroup=gid;});});}
  if(['hairpin','glissando'].includes(kind)){
    score.voices.forEach(v=>{const all=score.measures.flatMap(m=>M.events(score,m,v.id)),ids=new Set(list.filter(e=>e.voice===v.id).map(e=>e.id)),chosen=all.filter(e=>ids.has(e.id));if(chosen.length){const a=chosen[0],b=chosen.at(-1);a[kind]=value;a[kind==='hairpin'?'hairpinTo':'glissTo']=a===b?'':b.id;}});
    if(kind==='hairpin')mis.forEach(mi=>{const m=score.measures[mi];m.hairpins??={};const vids=selectedMeasureVoices.get(m.id)||new Set([activeVoice]);vids.forEach(vid=>m.hairpins[vid]={id:M.id(),kind:value});});
  }
}
function useSymbol(kind,value,label){hideMenu();const notes=selectedList(),mis=score.measures.map((m,i)=>selectedMeasures.has(m.id)?i:-1).filter(i=>i>=0);if((measureSymbolKinds.includes(kind)&&mis.length)||(!measureSymbolKinds.includes(kind)&&(notes.length||mis.length))){commit(()=>{if(['slur','tie','arpeggio','glissando'].includes(kind))mis.forEach(mi=>notes.push(...M.events(score,score.measures[mi],activeVoice)));applySymbolTo(kind,value,notes,mis);});symbolTool=null;symbolStart=null;syncTools();return;}symbolTool={kind,value,label};symbolStart=null;syncTools();}
function placeSymbol(t){const {kind,value}=symbolTool;if(measureSymbolKinds.includes(kind)){commit(()=>applySymbolTo(kind,value,[],[t.mi]));return;}if(t.type!=='note'){if(['ottava','hairpin'].includes(kind)&&t.type==='measure'){activeVoice=t.voice||activeVoice;commit(()=>applySymbolTo(kind,value,[],[t.mi]));return;}toast('请点击音符确定符号的位置。');return;}const f=findNote(t.id);if(!f)return;focusMeasure(f.mi,f.e.voice);
  if(['ottava','slur','hairpin','glissando'].includes(kind)){if(!symbolStart){symbolStart={id:f.e.id,gid:M.id()};if(['slur','ottava'].includes(kind))commit(()=>{if(kind==='slur')f.e.slur=symbolStart.gid;else f.e.ottava=Number(value);});}else{const a=findNote(symbolStart.id)?.e,gid=symbolStart.gid;if(a)commit(()=>{if(kind==='slur')betweenNotes(a,f.e).forEach(e=>e.slur=gid);else if(kind==='ottava')applySymbolTo(kind,value,betweenNotes(a,f.e));else{a[kind]=value;a[kind==='hairpin'?'hairpinTo':'glissTo']=f.e.id;}});symbolStart=null;}syncTools();}else commit(()=>applySymbolTo(kind,value,[f.e]));
}
function octaveGroup(t){const f=findNote(t.id);if(!f)return [];const all=score.measures.flatMap(m=>M.events(score,m,f.e.voice)),idx=all.indexOf(f.e),value=f.e.ottava;let a=idx,b=idx;while(a>0&&all[a-1].ottava===value)a--;while(b+1<all.length&&all[b+1].ottava===value)b++;return all.slice(a,b+1);}
function removeSymbol(t){const m=score.measures[t.mi],f=findNote(t.id);if(!m)return;if(t.kind==='measureHairpin'){delete m.hairpins?.[t.id];return;}if(t.kind==='measureOctave'){if(m.octaves)delete m.octaves[t.id];return;}if(measureSymbolKinds.includes(t.kind)){m[t.kind]=t.kind==='repeatStart'?false:t.kind==='repeatEnd'?0:'';return;}if(!f)return;if(['hairpin','glissando','arpeggio'].includes(t.kind)){if(t.kind==='arpeggio'&&f.e.arpeggioGroup)score.measures.flatMap(m=>m.events).filter(e=>e.arpeggioGroup===f.e.arpeggioGroup).forEach(e=>{e.arpeggio='';e.arpeggioGroup='';});f.e[t.kind]='';f.e[t.kind==='hairpin'?'hairpinTo':'glissTo']='';return;}if(t.kind==='grace'){f.e.graceNotes=[];return;}if(t.kind==='ottava')octaveGroup(t).forEach(e=>e.ottava=0);if(t.kind==='tie')f.e.tie=false;if(t.kind==='slur'){const id=f.e.slur;score.measures.flatMap(m=>m.events).filter(e=>e.slur===id).forEach(e=>e.slur='');}if(t.kind==='tuplet'){const gid=f.e.tuplet?.id;if(gid)score.measures.flatMap(m=>m.events).filter(e=>e.tuplet?.id===gid).forEach(e=>{e.tuplet=null;e.exactTicks=null;});}}
function editSymbols(value){commit(()=>selectedSymbols.forEach(t=>{if(t.kind==='measureHairpin'){score.measures[t.mi].hairpins[t.id].kind=value;return;}if(['hairpin','glissando','arpeggio'].includes(t.kind)){const f=findNote(t.id);if(f)f.e[t.kind]=value;return;}if(t.kind==='measureOctave'){score.measures[t.mi].octaves[t.id]=Number(value);return;}if(measureSymbolKinds.includes(t.kind))score.measures[t.mi][t.kind]=value;else if(t.kind==='ottava')octaveGroup(t).forEach(e=>e.ottava=Number(value));}));}
function updateTupletSymbols(){const count=Number($('menuTupletCount').value),total=Number($('menuTupletTotal').value);commit(()=>{if(!Number.isInteger(count)||count<2||count>32||!Number.isFinite(total)||total<.125||total>32)throw new Error('连音数量为 2–32，总时值为 0.125–32 拍。');selectedSymbols.forEach(t=>{if(t.kind!=='tuplet')return;const gid=findNote(t.id)?.e.tuplet?.id,group=score.measures.flatMap(m=>m.events).filter(e=>e.tuplet?.id===gid);M.setTuplet(group,count,total);});});}
$('score').addEventListener('click',scoreClick);

$('score').addEventListener('pointermove',e=>{const t=targetAt(e.target);if(menuArmPoint&&Math.hypot(e.clientX-menuArmPoint.x,e.clientY-menuArmPoint.y)>5)menuArmPoint=null;const hover=menuArmPoint?null:hoverTargetAt(e);if(mode==='select'&&isSelectedTarget(hover))showMenu(hover,e.clientX,e.clientY);else scheduleHideMenu();const p=coordinates(e),ghost=$('ghost');if(!p||!ghost)return;const g=geometry.find(g=>p.x>=g.start&&p.x<g.end&&p.y>=g.offset+4&&p.y<g.rowEnd-4);if(!g||mode!=='edit'||symbolTool||t?.type!=='measure'){ghost.innerHTML='';return;}const pitch=Math.max(0,Math.min(66,g.bottomPitch+Math.round((g.base-p.y)/6))),y=g.base-(pitch-g.bottomPitch)*6;ghost.innerHTML=glyph('\uE0A4',p.x,y)+`<text x="${p.x+20}" y="${y-8}" font-size="10" fill="#38624f">${M.pitchName(pitch,M.keyMap(config(g.mi,g.voice).key)[M.letter(pitch)]||0)}</text>`;});$('score').addEventListener('pointerleave',()=>{if($('ghost'))$('ghost').innerHTML='';scheduleHideMenu();});
function deleteSelected(){const ids=new Set(selectedNotes),bars=new Set(selectedMeasures),symbols=[...selectedSymbols.values()];if(!ids.size&&!bars.size&&!symbols.length)return;const remove=()=>commit(()=>{symbols.forEach(removeSymbol);score.measures.forEach(m=>m.events=m.events.filter(e=>!ids.has(e.id)));score.measures=score.measures.filter(m=>!bars.has(m.id));if(!score.measures.length)score.measures=[M.measure()];clearSelection();});if(bars.size)confirmAction('删除小节',`将删除选中的 ${bars.size} 个小节及其所有声部内容，可撤销。`,remove);else remove();}
function movePitch(dir){const list=selectedList().filter(e=>e.type==='note');if(list.length)commit(()=>list.forEach(e=>e.pitch=Math.max(0,Math.min(66,e.pitch+dir))));}
function navigate(dir){const notes=score.measures.flatMap(m=>M.events(score,m,activeVoice)),i=notes.findIndex(e=>e.id===selected),next=notes[i+dir];if(next)select(next.id);}
function toggleMode(){if(document.activeElement?.matches('input,select,textarea'))document.activeElement.blur();finishMeasure();mode=mode==='edit'?'select':'edit';symbolTool=null;symbolStart=null;hideMenu();syncTools();$('score').focus({preventScroll:true});}
$('modeToggle').onclick=toggleMode;
function confirmAction(title,text,fn){hideMenu();$('confirmTitle').textContent=title;$('confirmText').textContent=text;pendingConfirm=fn;$('confirmDialog').showModal();}$('cancelConfirm').onclick=()=>{$('confirmDialog').close();pendingConfirm=null;};$('acceptConfirm').onclick=()=>{const fn=pendingConfirm;pendingConfirm=null;$('confirmDialog').close();fn?.();};$('confirmDialog').addEventListener('cancel',()=>pendingConfirm=null);
function offerFix(kind='all',id=null){try{const fixed=M.repair(score,kind,id);commit(()=>{score=fixed;clearSelection();});toast('已修正，可撤销。');}catch(e){toast(e.message);}}$('fixAll').onclick=()=>offerFix();
['mode','key','clef','meter','bpm'].forEach(k=>$(k).onchange=e=>requestSetting(k,k==='meter'?e.target.value.split('/').map(Number):['key','bpm'].includes(k)?Number(e.target.value):e.target.value));$('title').onchange=e=>commit(()=>score.title=e.target.value.trim()||'未命名作品');
$('voice').onchange=e=>{stop();finishMeasure();activeVoice=e.target.value;clearSelection();render();};$('voiceName').onchange=e=>commit(()=>part().name=e.target.value.trim()||'声部');$('muteVoice').onchange=e=>commit(()=>part().muted=e.target.checked);$('solo').onchange=stop;
function addVoice(name=null,clef='treble'){if(score.voices.length>=16)throw new Error('最多 16 个声部。');const v={id:M.id(),name:name||`声部 ${score.voices.length+1}`,clef,muted:false};score.voices.push(v);score.measures.forEach((m,mi)=>m.events.push(...M.restPieces(M.capacity(score,mi),v.id).map(e=>({...e,placeholder:true}))));return v;}
$('addVoice').onclick=()=>commit(()=>{activeVoice=addVoice().id;clearSelection();});$('removeVoice').onclick=()=>{if(score.voices.length===1)return;const v=part();confirmAction('删除声部',`将删除“${v.name}”及其音符和歌词，可撤销。`,()=>commit(()=>{score.voices=score.voices.filter(x=>x.id!==v.id);score.measures.forEach(m=>{m.events=m.events.filter(e=>e.voice!==v.id);delete m.clefs?.[v.id];delete m.octaves?.[v.id];});activeVoice=score.voices[0].id;clearSelection();}));};
document.querySelectorAll('[data-duration]').forEach(b=>b.onclick=()=>setProp('duration',+b.dataset.duration));$('dots').onchange=e=>setProp('dots',+e.target.value);
document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>useSymbol(b.dataset.symbol,b.dataset.symbol==='slur'?b.dataset.value:b.dataset.symbol==='repeatEnd'?Math.max(2,Math.min(8,Math.round(Number($('repeatTimes').value)||2))):JSON.parse(b.dataset.value),b.textContent));$('endingTool').onchange=e=>{if(e.target.value)useSymbol('ending',e.target.value==='clear'?'':e.target.value,e.target.selectedOptions[0].textContent);e.target.value='';};$('navigationTool').onchange=e=>{if(e.target.value)useSymbol('navigation',e.target.value==='clear'?'':e.target.value,e.target.selectedOptions[0].textContent);e.target.value='';};$('cancelSymbol').onclick=()=>{symbolTool=null;symbolStart=null;syncTools();};
$('tupletsToggle').onclick=()=>{$('advanced').hidden=!$('advanced').hidden;$('tupletsToggle').classList.toggle('active',!$('advanced').hidden);};$('tupletCount').oninput=e=>{$('tupletRange').value=Math.max(2,Math.min(32,+e.target.value||3));syncTuplet();};$('tupletCount').onchange=e=>{e.target.value=Math.max(2,Math.min(32,Math.round(+e.target.value)||3));syncTuplet();};$('tupletRange').oninput=e=>{$('tupletCount').value=e.target.value;syncTuplet();};$('tupletTotal').oninput=syncTuplet;
function tupletParams(){const count=Math.round(+$('tupletCount').value),total=+$('tupletTotal').value;if(count<2||count>32||!Number.isFinite(total)||total<.125||total>32)throw new Error('连音数量为 2–32，总时值为 0.125–32 个四分拍。');return {count,total};}
$('insertTuplet').onclick=()=>commit(()=>{const {count,total}=tupletParams(),f=getSelected(),v=activeVoice,pitch=f?.e.type==='note'?f.e.pitch:(config().clef==='bass'?22:34);clearPlaceholders(currentMeasure,v);const arr=score.measures[currentMeasure].events,idx=f?arr.findIndex(e=>e.id===f.e.id)+1:arr.length,list=Array.from({length:count},()=>M.event(pitch,{voice:v}));M.setTuplet(list,count,total);arr.splice(idx,0,...list);clearSelection();list.forEach(e=>selectedNotes.add(e.id));selected=list[0].id;defaults.duration=list[0].duration;defaults.dots=list[0].dots;});
$('applyTuplet').onclick=()=>commit(()=>{const f=getSelected();if(!f)throw new Error('请选中音符或休止符。');const {count,total}=tupletParams(),all=score.measures.flatMap(m=>M.events(score,m,activeVoice)),idx=all.findIndex(e=>e.id===f.e.id);let list;if(selectedNotes.size>1){list=all.filter(e=>selectedNotes.has(e.id));if(list.length!==selectedNotes.size)throw new Error('连音组应属于同一声部。');if(list.some((e,i)=>i&&all.indexOf(e)!==all.indexOf(list[i-1])+1))throw new Error('连音组应选择连续的音符或休止符。');}else if(f.e.tuplet)list=all.filter(e=>e.tuplet?.id===f.e.tuplet.id);else list=all.slice(idx,idx+count);M.setTuplet(list,count,total);defaults.duration=list[0].duration;defaults.dots=list[0].dots;});
$('removeTuplet').onclick=()=>commit(()=>{const gids=new Set(selectedList().map(e=>e.tuplet?.id).filter(Boolean));score.measures.flatMap(m=>m.events).filter(e=>gids.has(e.tuplet?.id)).forEach(e=>{e.tuplet=null;e.exactTicks=null;});selectedSymbols.forEach(t=>{if(t.kind==='tuplet')removeSymbol(t);});});
$('addMeasure').onclick=()=>commit(()=>{if(score.measures.length>=300)throw new Error('最多 300 小节。');const c=config(score.measures.length-1),clefs={};score.voices.forEach(v=>clefs[v.id]=config(score.measures.length-1,v.id).clef);finishMeasure();score.measures.push(M.measure({key:c.key,mode:c.mode,meter:[...c.meter],bpm:c.bpm,clefs}));currentMeasure=score.measures.length-1;clearSelection();});
function history(dir){stop();const src=dir<0?undoStack:redoStack,dest=dir<0?redoStack:undoStack;if(!src.length)return;dest.push(snapshot());score=JSON.parse(src.pop());clearSelection();render();save();}$('undo').onclick=()=>history(-1);$('redo').onclick=()=>history(1);
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Tab'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();toggleMode();return;}if(e.key==='Escape'){e.preventDefault();symbolTool=null;symbolStart=null;clearSelection();render();return;}if(e.target.matches('input,select,textarea'))return;if(e.ctrlKey||e.metaKey){if(e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?1:-1);}if(e.key.toLowerCase()==='y'){e.preventDefault();history(1);}return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelected();}if(e.key==='ArrowUp'){e.preventDefault();movePitch(1);}if(e.key==='ArrowDown'){e.preventDefault();movePitch(-1);}if(e.key==='ArrowRight'){e.preventDefault();navigate(1);}if(e.key==='ArrowLeft'){e.preventDefault();navigate(-1);}if(e.code==='Space'){e.preventDefault();playSession?stop():play();}});
$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('print').onclick=()=>window.print();
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(score,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=score.title.replace(/[\\/:*?"<>|]/g,'_')+'.score.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已导出全部声部、歌词、小节设置和符号。');};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>8e6)throw new Error('文件过大。');const imported=M.sanitize(JSON.parse(await f.text()));confirmAction('打开乐谱','当前内容可撤销恢复。',()=>commit(()=>{score=imported;activeVoice=score.voices[0].id;currentMeasure=0;clearSelection();}));}catch(err){toast(err.message||'无法读取乐谱。');}e.target.value='';};
$('new').onclick=()=>confirmAction('新建乐谱','当前作品可先导出备份。新建后可撤销恢复。',()=>commit(()=>{score=M.blank();activeVoice=score.voices[0].id;currentMeasure=0;clearSelection();defaults={duration:4,dots:0,triplet:false,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false};}));
['highest','lowest'].forEach(k=>$(k+'Button').onclick=()=>{const id=M.stats(score)[k+'Id'];if(id){mode='select';select(id);$('score').querySelector(`[data-id="${id}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});}});

const sampleMidi=name=>{const m=name.match(/^(C|Ds|Fs|A)(\d)$/);return (+m[2]+1)*12+({C:0,Ds:3,Fs:6,A:9}[m[1]]);};
async function pianoBuffer(midi){const name=Object.keys(PIANO_SAMPLES).reduce((best,n)=>Math.abs(sampleMidi(n)-midi)<Math.abs(sampleMidi(best)-midi)?n:best);if(!buffers.has(name)){const bytes=Uint8Array.from(atob(PIANO_SAMPLES[name]),c=>c.charCodeAt(0));buffers.set(name,audioContext.decodeAudioData(bytes.buffer));}return {buffer:await buffers.get(name),base:sampleMidi(name)};}
function stop(){if(playSession){playSession.cancelled=true;playSession.sources.forEach(s=>{try{s.stop();}catch{}});cancelAnimationFrame(playSession.raf);playSession=null;}$('play').disabled=false;$('play').textContent='▶ 播放';$('stop').disabled=true;$('playTime').textContent='0:00';document.querySelectorAll('.playing').forEach(e=>e.classList.remove('playing'));}
async function play(){if(playSession)return;const t=M.timeline(score);t.notes=playbackNotes(t);if(!t.notes.length){toast('请先输入乐谱。');return;}if(t.warnings.length){toast('请先修正反复与返回标记。');return;}
  try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();const session={sources:[],cancelled:false};playSession=session;$('play').disabled=true;$('play').textContent='加载钢琴…';$('stop').disabled=false;
    const audible=score.voices.filter(v=>!v.muted&&(!$('solo').checked||v.id===activeVoice)).map(v=>v.id),samples=new Map();await Promise.all(t.notes.filter(n=>n.midi!==null&&audible.includes(n.voice)).map(async n=>{if(!samples.has(n.midi))samples.set(n.midi,pianoBuffer(n.midi));}));await Promise.all(samples.values());if(session.cancelled)return;
    const start=audioContext.currentTime+.12;session.start=start;const mix=.85/Math.sqrt(Math.max(1,audible.length));
    for(const n of t.notes){if(n.midi===null||n.continuation||!audible.includes(n.voice))continue;const sample=await samples.get(n.midi),source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=sample.buffer;source.playbackRate.value=Math.pow(2,(n.midi-sample.base)/12);let length=n.seconds,last=n;while(last.validTie){last=last.next;length+=last.seconds;}const art=last.articulation,gate=art==='staccatissimo'?.25:art==='staccato'?.48:art==='tenuto'||art==='legato'?1:.93,on=start+n.start,off=on+Math.max(.012,length*gate),level=Math.max(.01,n.volume*(['accent','marcato'].includes(n.articulation)?1.18:1)*mix);gain.gain.setValueAtTime(0,on);gain.gain.linearRampToValueAtTime(level,on+.004);gain.gain.setValueAtTime(level,Math.max(on+.004,off-.01));gain.gain.exponentialRampToValueAtTime(.001,off+.08);source.connect(gain).connect(audioContext.destination);source.start(on);source.stop(off+.1);session.sources.push(source);}
    $('play').textContent='正在播放…';function tick(){if(session.cancelled)return;const elapsed=Math.max(0,audioContext.currentTime-start);$('playTime').textContent=timeText(elapsed);document.querySelectorAll('.playing').forEach(e=>e.classList.remove('playing'));const sounding=t.notes.filter(n=>elapsed>=n.start&&elapsed<n.start+n.seconds&&audible.includes(n.voice));sounding.forEach(n=>$('score').querySelector(`[data-id="${n.e.id}"]`)?.classList.add('playing'));if(elapsed>=t.seconds+.12){stop();return;}session.raf=requestAnimationFrame(tick);}tick();
  }catch(e){stop();toast('音频启动失败：'+e.message);}
}
$('play').onclick=play;$('stop').onclick=stop;new ResizeObserver(()=>{clearTimeout(renderScore.timer);renderScore.timer=setTimeout(renderScore,80);}).observe($('score'));document.fonts.ready.then(renderScore);window.addEventListener('beforeunload',save);render();
