'use strict';
const M=MusicCore,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let score=M.blank(),selected=null,activeVoice='v1',currentMeasure=0,mode='edit';
const selectedNotes=new Set(),selectedMeasures=new Set(),selectedMeasureVoices=new Map(),selectedSymbols=new Map();
let defaults={duration:4,dots:0,triplet:false,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false};
let undoStack=[],redoStack=[],geometry=[],notePositions=new Map(),playSession=null,audioContext=null,buffers=new Map(),pendingConfirm=null,pendingScope=null,symbolTool=null,symbolStart=null,menuTarget=null,hideMenuTimer=null,lyricEditBefore=null;
try{const saved=localStorage.getItem('puji-score-v3')||localStorage.getItem('puji-score-v2')||localStorage.getItem('puji-score-v1');if(saved)score=M.sanitize(JSON.parse(saved));}catch{setTimeout(()=>toast('自动保存不可用，请导出备份作品。'),500);}activeVoice=score.voices[0].id;
const part=()=>score.voices.find(v=>v.id===activeVoice)||score.voices[0];
const config=(mi=currentMeasure,vid=activeVoice)=>M.settings(score,mi,vid);
const escapeXml=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const timeText=seconds=>{const n=Math.max(0,Math.round(seconds));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;};
const glyph=(char,x,y,size=48,cls='music-text',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" class="${cls}" ${extra}>${char}</text>`;
const line=(x1,y1,x2,y2,cls='staff-line',extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}" ${extra}/>`;
const beatKey=n=>n.toFixed(6);
const dynamics=['pppp','ppp','pp','p','mp','mf','f','ff','fff','ffff','sf','sfz','fp','rfz'];
const articulations=[['staccato','·'],['staccatissimo','▾'],['accent','›'],['marcato','∧'],['tenuto','—'],['fermata','𝄐'],['breath','ʹ'],['legato','⌒'],['portato','— ·'],['pizzicato','pizz.'],['arco','arco']];
const navNames={segno:'𝄋 Segno',coda:'𝄌 Coda','to-coda':'To Coda',fine:'Fine','dc-fine':'D.C. al Fine','ds-fine':'D.S. al Fine','dc-coda':'D.C. al Coda','ds-coda':'D.S. al Coda'};
const clefNames={treble:'高音谱号',bass:'低音谱号',treble8vb:'高音谱号 · 低八度',treble8va:'高音谱号 · 高八度'};
const meterValues=[...new Set(['4/4','3/4','2/4','6/8','9/8','12/8','2/2','3/8','5/4','7/8',...[2,4,8,16].flatMap(d=>Array.from({length:12},(_,i)=>`${i+1}/${d}`))])];
$('meter').innerHTML=meterValues.map(v=>`<option>${v}</option>`).join('');
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
const snapshot=()=>JSON.stringify(score);
function save(){try{localStorage.setItem('puji-score-v3',snapshot());$('saveState').textContent='已保存到本机';}catch{$('saveState').textContent='请导出备份';}}
function clearSelection(){selected=null;selectedNotes.clear();selectedMeasures.clear();selectedMeasureVoices.clear();selectedSymbols.clear();hideMenu();}
function commit(fn){stop();const prev=snapshot();try{fn();}catch(e){score=JSON.parse(prev);toast(e.message);render();return;}if(snapshot()!==prev){undoStack.push(prev);if(undoStack.length>120)undoStack.shift();redoStack=[];}render();save();}
function findNote(id){for(let mi=0;mi<score.measures.length;mi++){const ei=score.measures[mi].events.findIndex(e=>e.id===id);if(ei>=0)return {e:score.measures[mi].events[ei],mi,ei};}return null;}
const getSelected=()=>findNote(selected);
const selectedList=()=>score.measures.flatMap(m=>m.events).filter(e=>selectedNotes.has(e.id));
function select(id,add=false){if(!add)clearSelection();if(add&&selectedNotes.has(id))selectedNotes.delete(id);else selectedNotes.add(id);selected=selectedNotes.has(id)?id:[...selectedNotes].at(-1)||null;const f=getSelected();if(f){activeVoice=f.e.voice;currentMeasure=f.mi;Object.keys(defaults).forEach(k=>defaults[k]=f.e[k]);if(f.e.tuplet){$('tupletCount').value=f.e.tuplet.count;$('tupletRange').value=f.e.tuplet.count;$('tupletTotal').value=f.e.tuplet.total;}}render();}
function selectMeasure(mi,vid=activeVoice,add=false){if(!add)clearSelection();const id=score.measures[mi].id,parts=selectedMeasureVoices.get(id)||new Set();if(add&&parts.has(vid))parts.delete(vid);else parts.add(vid);if(parts.size){selectedMeasureVoices.set(id,parts);selectedMeasures.add(id);}else{selectedMeasureVoices.delete(id);selectedMeasures.delete(id);}currentMeasure=mi;activeVoice=vid;render();}
const symbolKey=t=>`${t.kind}:${score.measures[t.mi]?.id}:${t.id||''}`;
function selectSymbol(t,add=false){if(!add)clearSelection();const key=symbolKey(t);if(add&&selectedSymbols.has(key))selectedSymbols.delete(key);else selectedSymbols.set(key,t);currentMeasure=t.mi;if(t.kind==='measureOctave')activeVoice=t.id;else if(t.id){const f=findNote(t.id);if(f)activeVoice=f.e.voice;}render();}
function setProp(k,v){defaults[k]=v;const list=selectedList();if(!list.length){syncTools();return;}commit(()=>list.forEach(e=>{e[k]=v;if(['duration','dots'].includes(k)){e.tuplet=null;e.triplet=false;e.exactTicks=null;}}));}
function syncSettings(){
  if(!score.voices.some(v=>v.id===activeVoice))activeVoice=score.voices[0].id;currentMeasure=Math.max(0,Math.min(currentMeasure,score.measures.length-1));
  const c=config();$('title').value=score.title;$('mode').value=c.mode;$('key').innerHTML=(c.mode==='minor'?M.MINOR:M.MAJOR).map((n,i)=>`<option value="${i-7}">${n} ${c.mode==='minor'?'小调':'大调'}</option>`).join('');$('key').value=c.key;$('clef').value=c.clef;$('meter').value=c.meter.join('/');$('bpm').value=c.bpm;
  $('keySummary').textContent=c.key===0?'无升降号':(c.key>0?M.SHARPS:M.FLATS).slice(0,Math.abs(c.key)).map(l=>l+(c.key>0?'♯':'♭')).join('  ');
  $('voice').innerHTML=score.voices.map(v=>`<option value="${v.id}">${escapeXml(v.name)}${v.muted?' · 静音':''}</option>`).join('');$('voice').value=activeVoice;$('voiceName').value=part().name;$('muteVoice').checked=part().muted;$('removeVoice').disabled=score.voices.length===1;$('voiceSummary').textContent=`${score.voices.length} 个声部`;
  const bits=[];if(selectedNotes.size)bits.push(`${selectedNotes.size} 个音符／休止符`);if(selectedMeasures.size)bits.push(`${selectedMeasures.size} 个小节`);if(selectedSymbols.size)bits.push(`${selectedSymbols.size} 个符号`);$('selectionSummary').textContent=bits.length?'已选 '+bits.join('、'):`${part().name} · 第 ${currentMeasure+1} 小节`;
}
function syncTuplet(){const count=Math.max(2,Math.min(32,Math.round(Number($('tupletCount').value)||3))),total=Math.max(.125,Math.min(32,Number($('tupletTotal').value)||1));$('tupletSummary').textContent=`${count} 个音均分 ${M.fmt(total)} 拍 · 每音 ${M.fmt(total/count)} 拍`;}
function syncTools(){document.querySelectorAll('[data-duration]').forEach(b=>b.classList.toggle('active',+b.dataset.duration===defaults.duration));$('dots').value=defaults.dots;$('modeToggle').textContent=mode==='edit'?'编辑模式 · Tab':'选择模式 · Tab';$('modeToggle').classList.toggle('active',mode==='edit');$('score').dataset.mode=mode;$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;syncTuplet();$('cancelSymbol').hidden=!symbolTool;document.querySelectorAll('[data-symbol]').forEach(b=>b.classList.toggle('active',symbolTool?.kind===b.dataset.symbol&&String(symbolTool.value)===b.dataset.value));$('symbolStatus').textContent=symbolTool?(symbolStart?'已放置起点，再点终点；Esc 结束':'点击谱面放置 '+symbolTool.label):'';}
function render(){syncSettings();syncTools();renderScore();renderStats();renderIssues();if(menuTarget&&!$('contextMenu').hidden)buildMenu();}
function renderStats(){const s=M.stats(score);$('noteCount').textContent=s.count;$('highest').textContent=s.highest;$('lowest').textContent=s.lowest;$('duration').textContent=timeText(s.seconds);$('durationExact').textContent=`（${s.seconds.toFixed(2)} 秒 · 含反复）`;}
function renderIssues(){const issues=M.validate(score);$('validationTitle').textContent=issues.length?'输入错误提示':'✓ 输入提示';$('validationSummary').textContent=issues.length?`${issues.length} 项待处理`:'暂无错误';$('fixAll').disabled=!issues.length;
  $('issues').innerHTML=issues.map((i,index)=>`<div class="issue"><span>${escapeXml(i.text)}</span><button data-locate="${index}">定位</button><button data-fix="${index}">修正</button></div>`).join('');
  document.querySelectorAll('[data-locate]').forEach(b=>b.onclick=()=>{const i=issues[+b.dataset.locate];mode='select';if(i.voice)activeVoice=i.voice;currentMeasure=i.mi;if(i.id)select(i.id);else selectMeasure(i.mi);$('score').querySelector(`[data-measure="${i.mi}"][data-part="${activeVoice}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});});
  document.querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>{const i=issues[+b.dataset.fix];offerFix(i.kind,i.id);});
}
function symbolAttrs(kind,mi,id=''){const t={kind,mi,id};return `class="score-symbol${selectedSymbols.has(symbolKey(t))?' selected-symbol':''}" data-symbol-kind="${kind}" data-symbol-mi="${mi}" data-symbol-id="${id}"`;}

function signatureWidth(mi){if(!mi)return 0;const a=config(mi-1),b=config(mi);return (a.key!==b.key?16+13*(Math.abs(a.key)+Math.abs(b.key)):0)+(a.meter.join('/')!==b.meter.join('/')?32:0)+(score.voices.some(v=>config(mi-1,v.id).clef!==config(mi,v.id).clef)?38:0);}
function measureLayout(m,mi){const map=new Map();score.voices.forEach(v=>{let beat=0;M.events(score,m,v.id).forEach(e=>{const k=beatKey(beat),width=Math.max(37,20+(e.lyric?.length||0)*12,e.accidental!==null?53:0,e.expression?Math.min(165,e.expression.length*6):0);if(!map.has(k))map.set(k,{beat,width,anchor:e.positionRatio??null});else{map.get(k).width=Math.max(map.get(k).width,width);if(map.get(k).anchor===null)map.get(k).anchor=e.positionRatio??null;}beat+=M.ticks(e);});});const points=[...map.values()].sort((a,b)=>a.beat-b.beat),header=signatureWidth(mi);return {points,header,min:Math.max(240,header+56+points.reduce((a,p)=>a+p.width,0))};}
function signature(key,oldKey,x,yFor,clef,cancel=false){let out='',count=0;const bass=clef==='bass'?14:0,sharp=[38,35,39,36,33,37,34],flat=[34,37,33,36,32,35,31];if(cancel&&oldKey!==key){const oldMap=M.keyMap(oldKey),newMap=M.keyMap(key),positions=oldKey>0?sharp:flat;(oldKey>0?M.SHARPS:M.FLATS).slice(0,Math.abs(oldKey)).forEach((l,i)=>{if(oldMap[l]!==newMap[l]){out+=glyph('\uE261',x+count*13,yFor(positions[i]-bass));count++;}});if(count)count++;}const positions=key>=0?sharp:flat;positions.slice(0,Math.abs(key)).forEach(p=>{out+=glyph(key>=0?'\uE262':'\uE260',x+count*13,yFor(p-bass));count++;});return {html:out,width:count*13};}
function drawClef(clef,x,base,bottomPitch){const y=p=>base-(p-bottomPitch)*6;return glyph(clef==='bass'?'\uE062':'\uE050',x,clef==='bass'?y(24):y(32))+(clef==='treble8vb'||clef==='treble8va'?`<text x="${x+14}" y="${clef==='treble8vb'?base+30:base-86}" text-anchor="middle" font-size="11">8</text>`:'');}
function drawMeter(meter,x,top){return `<text x="${x}" y="${top+19}" text-anchor="middle" font-family="Georgia" font-weight="bold" font-size="23">${meter[0]}</text><text x="${x}" y="${top+43}" text-anchor="middle" font-family="Georgia" font-weight="bold" font-size="23">${meter[1]}</text>`;}
function renderScore(){
  const prefix=164+Math.max(...score.measures.map((m,mi)=>Math.abs(config(mi).key)))*13,layouts=score.measures.map(measureLayout),w=Math.max(660,$('score').clientWidth,...layouts.map(l=>l.min+prefix+22)),rows=[];let row=[],occupied=prefix+22;
  layouts.forEach((layout,mi)=>{if(row.length&&occupied+layout.min>w){rows.push(row);row=[];occupied=prefix+22;}row.push({mi,layout});occupied+=layout.min;});if(row.length)rows.push(row);
  const resolved=new Map(M.resolved(score).map(n=>[n.e.id,n]));geometry=[];notePositions=new Map();let out=[],offset=0;
  rows.forEach((row,ri)=>{const extra=(w-prefix-22-row.reduce((a,p)=>a+p.layout.min,0))/row.length;let mx=prefix;const bars=row.map((p,bi)=>{const width=p.layout.min+extra,start=mx,end=mx+width,header=bi===0?0:p.layout.header,xmap=new Map(),points=p.layout.points;let x=start+header+23;const gap=(width-header-46-points.reduce((a,p)=>a+p.width,0))/Math.max(1,points.length);points.forEach(p=>{xmap.set(beatKey(p.beat),p.anchor!==null?start+header+26+p.anchor*Math.max(0,width-header-58):x+p.width/2);x+=p.width+gap;});mx=end;return {...p,start,end,width,header,xmap};});
    let systemTop=null,lastBase=offset+45;
    score.voices.forEach((v,vi)=>{const list=row.flatMap(({mi})=>M.events(score,score.measures[mi],v.id).map(e=>({e,mi}))),notes=list.filter(p=>p.e.type==='note'||p.e.entryAnchor),bottomFor=mi=>config(mi,v.id).clef==='bass'?18:30,maxLedger=Math.max(0,...notes.map(p=>p.e.pitch-bottomFor(p.mi)-8)),minLedger=Math.max(0,...notes.map(p=>bottomFor(p.mi)-p.e.pitch));
      const upOct=list.some(p=>p.e.ottava>0)||row.some(p=>score.measures[p.mi].octaves?.[v.id]>0),downOct=list.some(p=>p.e.ottava<0)||row.some(p=>score.measures[p.mi].octaves?.[v.id]<0),tuplet=list.some(p=>p.e.tuplet||p.e.triplet),expression=list.some(p=>p.e.expression&&!['crescendo','diminuendo'].includes(p.e.expression));
      const base=offset+108+maxLedger*6+(upOct?24:0)+(tuplet?18:0)+(expression?14:0),top=base-48,annotationY=base+Math.max(30,minLedger*6+24),lyricY=annotationY+24,rowEnd=lyricY+24+(downOct?24:0);
      if(systemTop===null)systemTop=top;const labelColor=v.id===activeVoice?'#38624f':'#7a8178';out.push(`<g data-voice="${v.id}" class="voice-label"><title>${escapeXml(v.name)}${v.muted?'（静音）':''}</title><text x="66" y="${top+28}" text-anchor="end" font-size="12" fill="${labelColor}" font-weight="${v.id===activeVoice?'650':'400'}">${escapeXml(v.name.length>6?v.name.slice(0,6)+'…':v.name)}</text></g>`);
      for(let l=0;l<5;l++)out.push(line(78,top+l*12,w-18,top+l*12));out.push(line(78,top,78,base,'barline'));
      const first=config(row[0].mi,v.id),firstBottom=bottomFor(row[0].mi),firstY=p=>base-(p-firstBottom)*6;out.push(drawClef(first.clef,87,base,firstBottom),signature(first.key,0,122,firstY,first.clef).html,drawMeter(first.meter,prefix-19,top));
      const voicePositions=[];
      bars.forEach((bar,bi)=>{const {mi,start,end,width,header,xmap}=bar,m=score.measures[mi],c=config(mi,v.id),prev=mi?config(mi-1,v.id):c,bottomPitch=bottomFor(mi),midPitch=bottomPitch+4,yFor=p=>base-(p-bottomPitch)*6;let beat=0;
        const positions=M.events(score,m,v.id).map((e,ei)=>{const p={e,x:xmap.get(beatKey(beat)),y:e.type==='rest'?top+24:yFor(e.pitch),mi,ei,voice:v.id,base,top,annotationY,lyricY,ri,offset,end,start,bottomPitch,downOct,rowEnd,header};beat+=M.ticks(e);return p;});
        geometry.push({mi,voice:v.id,start,end,header,top,base,offset,rowEnd,positions,bottomPitch});
        out.push(`<g class="measure${mi===currentMeasure&&v.id===activeVoice?' current-measure':''}${selectedMeasureVoices.get(m.id)?.has(v.id)?' selected-measure':''}" data-measure="${mi}" data-part="${v.id}"><rect class="measure-click" data-mi="${mi}" data-voice="${v.id}" x="${start}" y="${offset+4}" width="${width}" height="${rowEnd-offset-8}"/>`);
        if(bi>0){let hx=start+7;if(prev.clef!==c.clef){out.push(drawClef(c.clef,hx,base,bottomPitch));hx+=38;}if(prev.key!==c.key){const sig=signature(c.key,prev.key,hx,yFor,c.clef,true);out.push(sig.html);hx+=sig.width+10;}if(prev.meter.join('/')!==c.meter.join('/'))out.push(drawMeter(c.meter,hx+12,top));}
        if(vi===0){out.push(`<text class="measure-number" x="${start+4}" y="${top-20}">${mi+1}</text>`);
          if(!mi||prev.bpm!==c.bpm)out.push(`<text x="${start+28}" y="${offset+43}" font-size="11" fill="#686f65">♩ = ${c.bpm}</text>`);
          if(m.expression||m.dynamic||m.articulation||m.ornament){const labels=[m.expression,m.dynamic,{trill:'tr',mordent:'波音',turn:'回音'}[m.ornament]].filter(Boolean).join(' · ');if(labels)out.push(`<text x="${start+28}" y="${offset+60}" class="expression-label">${escapeXml(labels)}</text>`);out.push(drawArticulationSymbol(m.articulation,start+28+(labels?labels.length*7+16:0),offset+60));}
          if(m.ending)out.push(`<g ${symbolAttrs('ending',mi)}><path d="M ${start+3} ${offset+29} V ${offset+16} H ${end-3} V ${offset+29}" fill="none" stroke="#5c635d"/><path class="symbol-hit" d="M ${start+3} ${offset+16} H ${end-3}"/><text x="${start+9}" y="${offset+29}" font-size="11">${escapeXml(m.ending)}.</text></g>`);
          if(m.navigation)out.push(`<g ${symbolAttrs('navigation',mi)}><text x="${end-7}" y="${offset+13}" text-anchor="end" font-family="Georgia,Segoe UI Symbol" font-size="${m.navigation==='segno'||m.navigation==='coda'?24:12}" font-style="italic">${navNames[m.navigation]}</text></g>`);
        }
        if(m.repeatStart){out.push(`<g ${symbolAttrs('repeatStart',mi)}><rect class="symbol-hit-box" x="${start}" y="${top-3}" width="22" height="54"/>`,line(start+3,top,start+3,base,'barline','stroke-width="3"'),line(start+9,top,start+9,base,'barline'));[top+18,top+30].forEach(y=>out.push(`<circle cx="${start+16}" cy="${y}" r="2" fill="#404940"/>`));out.push('</g>');}
        const total=positions.reduce((a,p)=>a+M.ticks(p.e),0);if(!M.close(total,M.capacity(score,mi)))out.push(`<text class="measure-status" x="${end-5}" y="${lyricY+18}" text-anchor="end">${M.fmt(total/48)} / ${M.fmt(M.capacity(score,mi)/48)} 拍</text>`);
        positions.forEach(p=>{notePositions.set(p.e.id,p);voicePositions.push(p);out.push(drawNote(p,resolved.get(p.e.id),midPitch));});
        if(m.octaves?.[v.id]){const value=m.octaves[v.id],oy=value>0?offset+15:lyricY+21,label={1:'8va','-1':'8vb',2:'15ma','-2':'15mb'}[value];out.push(`<g ${symbolAttrs('measureOctave',mi,v.id)}><text x="${start+30}" y="${oy}" font-size="12" font-style="italic">${label}</text><path d="M ${start+68} ${oy-4} H ${end-14} V ${oy+(value>0?3:-11)}" fill="none" stroke="#65725f" stroke-dasharray="4 3"/><path class="symbol-hit" d="M ${start+30} ${oy-4} H ${end-14}"/></g>`);}
        out.push(line(end,top,end,base,'barline'));
        if(m.repeatEnd){out.push(`<g ${symbolAttrs('repeatEnd',mi)}><rect class="symbol-hit-box" x="${end-24}" y="${top-6}" width="29" height="58"/>`,line(end-6,top,end-6,base,'barline'),line(end,top,end,base,'barline','stroke-width="3"'));[top+18,top+30].forEach(y=>out.push(`<circle cx="${end-14}" cy="${y}" r="2" fill="#404940"/>`));if(vi===0&&m.repeatEnd>2)out.push(`<text x="${end-20}" y="${top-8}" text-anchor="end" font-size="10">×${m.repeatEnd}</text>`);out.push('</g>');}else if(mi===score.measures.length-1){out.push(line(end-5,top,end-5,base,'barline'),line(end,top,end,base,'barline','stroke-width="3"'));}out.push('</g>');
      });
      drawGroups(voicePositions,out,ri,prefix,w);lastBase=base;offset=rowEnd;
    });if(score.voices.length>1){out.push(line(74,systemTop,74,lastBase,'barline','stroke-width="2"'));out.push(`<path d="M 70 ${systemTop-4} H 65 V ${lastBase+4} H 70" fill="none" stroke="#5c635d" stroke-width="2"/>`);}offset+=22;
  });
  score.voices.forEach(v=>{const notes=score.measures.flatMap(m=>M.events(score,m,v.id));notes.forEach((e,i)=>{if(!e.tie)return;const a=notePositions.get(e.id),b=notePositions.get(notes[i+1]?.id);if(!a)return;const color=resolved.get(e.id)?.midi===resolved.get(notes[i+1]?.id)?.midi?'#465c4b':'#ab4137';out.push(`<g ${symbolAttrs('tie',a.mi,e.id)}>${curve(a,b,prefix,w,color,16)}</g>`);});});
  $('score').innerHTML=`<svg xmlns="${NS}" style="width:${w}px;max-width:none" viewBox="0 0 ${w} ${Math.max(230,offset)}" role="img" aria-label="${escapeXml(score.title)} · ${score.voices.length} 声部">${out.join('')}<g id="ghost" class="ghost"></g></svg>`;
}

function curve(a,b,prefix,w,color,dy=16){const y=a.y+dy;let out='';if(b&&a.ri===b.ri)out=`<path d="M ${a.x+10} ${y} Q ${(a.x+b.x)/2} ${Math.max(y,b.y+dy)+20} ${b.x+2} ${b.y+dy}" fill="none" stroke="${color}" stroke-width="1.4"/>`;else{out=`<path d="M ${a.x+10} ${y} Q ${(a.x+w)/2} ${y+18} ${w-20} ${y}" fill="none" stroke="${color}" stroke-width="1.4"/>`;if(b)out+=`<path d="M ${prefix} ${b.y+dy} Q ${(prefix+b.x)/2} ${b.y+dy+18} ${b.x+2} ${b.y+dy}" fill="none" stroke="${color}" stroke-width="1.4"/>`;}return out+out.replace(/stroke="[^"]*"/g,'stroke="transparent"').replace(/stroke-width="1.4"/g,'stroke-width="12"');}
function drawGroups(pos,out,ri,prefix,w){
  const groups=new Map();pos.forEach(p=>{if(p.e.tuplet){const id=p.e.tuplet.id;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(p);}});
  groups.forEach(g=>{const t=g[0].e.tuplet,x1=g[0].x-5,x2=g.at(-1).x+18,y=Math.min(...g.map(p=>Math.min(p.top-12,p.y-49))),mid=(x1+x2)/2;out.push(`<g ${symbolAttrs('tuplet',g[0].mi,g[0].e.id)}><title>${t.count} 个音均分 ${t.total} 个四分拍</title><path d="M ${x1} ${y+5} V ${y} H ${mid-10} M ${mid+10} ${y} H ${x2} V ${y+5}" fill="none" stroke="#454c46"/><path class="symbol-hit" d="M ${x1} ${y} H ${x2}"/><text x="${mid}" y="${y+4}" text-anchor="middle" font-size="12" font-style="italic">${t.count}</text><text x="${mid}" y="${y-11}" text-anchor="middle" font-size="9" fill="#8a9386">共 ${M.fmt(t.total)} 拍</text></g>`);});
  for(let i=0;i<pos.length;i++){const p=pos[i];if(p.e.triplet&&!p.e.tuplet){let end=i;while(end+1<pos.length&&pos[end+1].e.triplet&&end-i<2)end++;out.push(`<text x="${(p.x+pos[end].x)/2}" y="${Math.min(...pos.slice(i,end+1).map(p=>p.y-50))}" font-size="12">3</text>`);i=end;}}
  for(let i=0;i<pos.length;i++){const p=pos[i];if(!p.e.ottava)continue;let end=i;while(end+1<pos.length&&pos[end+1].e.ottava===p.e.ottava)end++;const label={1:'8va','-1':'8vb',2:'15ma','-2':'15mb'}[p.e.ottava],y=p.e.ottava>0?p.offset+15:p.lyricY+21,x1=p.x-9,x2=pos[end].x+23;out.push(`<g ${symbolAttrs('ottava',p.mi,p.e.id)}><text class="octave-label" x="${x1}" y="${y}" font-size="12" font-style="italic">${label}</text><path class="octave-line" d="M ${x1+32} ${y-4} H ${x2} V ${y+(p.e.ottava>0?3:-11)}" fill="none" stroke="#65725f" stroke-dasharray="4 3"/><path class="symbol-hit" d="M ${x1} ${y-4} H ${x2}"/></g>`);i=end;}
  const slurs=new Map();pos.filter(p=>p.e.slur).forEach(p=>{if(!slurs.has(p.e.slur))slurs.set(p.e.slur,[]);slurs.get(p.e.slur).push(p);});slurs.forEach(g=>{const a=g[0],b=g.at(-1),all=score.measures.flatMap(m=>M.events(score,m,a.voice)).filter(e=>e.slur===a.e.slur),start=all[0].id===a.e.id,end=all.at(-1).id===b.e.id,x1=start?a.x+10:prefix,x2=end?b.x+2:w-20,y1=a.y+23,y2=b.y+23;if(x2>x1){const d=`M ${x1} ${y1} Q ${(x1+x2)/2} ${Math.max(y1,y2)+20} ${x2} ${y2}`;out.push(`<g ${symbolAttrs('slur',a.mi,a.e.id)}><path d="${d}" fill="none" stroke="#465c4b" stroke-width="1.4"/><path class="symbol-hit" d="${d}"/></g>`);}else out.push(`<g ${symbolAttrs('slur',a.mi,a.e.id)}><text x="${a.x+8}" y="${a.y+30}" font-size="16">⌒</text></g>`);});
}

function drawArticulationSymbol(kind,x,y){let mark='';if(kind==='staccato')mark=`<circle cx="${x+7}" cy="${y-4}" r="2" fill="#333"/>`;if(kind==='staccatissimo')mark=`<path d="M ${x+3} ${y-9} L ${x+11} ${y-9} L ${x+7} ${y} Z" fill="#333"/>`;if(kind==='accent')mark=`<path d="M ${x+1} ${y-8} L ${x+14} ${y-4} L ${x+1} ${y}" fill="none" stroke="#333"/>`;if(kind==='marcato')mark=`<path d="M ${x+1} ${y} L ${x+7} ${y-9} L ${x+14} ${y}" fill="none" stroke="#333"/>`;if(kind==='tenuto'||kind==='portato')mark=line(x,y-4,x+14,y-4,'staff-line','stroke-width="2"');if(kind==='portato')mark+=`<circle cx="${x+7}" cy="${y+2}" r="1.8" fill="#333"/>`;if(kind==='fermata')mark=glyph('\uE4C0',x,y,38);if(kind==='breath')mark=glyph('\uE4CE',x,y,32);if(kind==='legato')mark=`<path d="M ${x} ${y} Q ${x+12} ${y-12} ${x+24} ${y}" fill="none" stroke="#333" stroke-width="1.4"/>`;if(kind==='pizzicato'||kind==='arco')mark=`<text x="${x}" y="${y}" class="expression-label">${kind==='pizzicato'?'pizz.':'arco'}</text>`;return mark?`<g class="articulation-symbol" data-articulation="${kind}">${mark}</g>`:'';}
function drawNote(p,n,mid){const {e,x,y,base,top,annotationY,lyricY}=p;let out=`<g class="note-group ${selectedNotes.has(e.id)?'selected':''}" data-id="${e.id}" data-note-voice="${e.voice}" role="button" aria-label="${escapeXml(n.name)}，${M.fmt(M.ticks(e)/48)} 拍"><title>${escapeXml(n.voiceName+' · '+n.name)} · ${M.fmt(M.ticks(e)/48)} 拍${e.lyric?' · '+escapeXml(e.lyric):''}</title><rect class="note-halo" x="${x-16}" y="${Math.min(y-16,base-(e.pitch-p.bottomPitch)*6-16,top-9)}" width="35" height="${Math.max(base+36-Math.min(y-16,base-(e.pitch-p.bottomPitch)*6-16,top-9),35)}" rx="7"/>`;
  if(e.type==='rest')out+=glyph(String.fromCodePoint(0xE4E3+Math.log2(e.duration)),x-6,e.duration===1?top+12:top+24,48,'music-text note-ink');
  else{if(y>base)for(let ly=base+12;ly<=y+1;ly+=12)out+=line(x-4,ly,x+19,ly,'note-ink');if(y<top)for(let ly=top-12;ly>=y-1;ly-=12)out+=line(x-4,ly,x+19,ly,'note-ink');
    if(e.accidental!==null)out+=glyph({'-2':'\uE264','-1':'\uE260','0':'\uE261','1':'\uE262','2':'\uE263'}[e.accidental],x-20,y,48,'music-text note-ink');out+=glyph(e.duration===1?'\uE0A2':e.duration===2?'\uE0A3':'\uE0A4',x,y,48,'music-text note-ink');
    const down=e.pitch>=mid;if(e.duration!==1){const sx=down?x+.6:x+13.6,sy=y+(down?36:-36);out+=line(sx,y,sx,sy,'note-ink','stroke-width="1.3"');if(e.duration>=8)out+=glyph(String.fromCodePoint(0xE240+2*(Math.log2(e.duration)-3)+(down?1:0)),sx,sy,48,'music-text note-ink');}
    const ay=down?Math.min(y-18,top-13):Math.max(y+20,base+16);if(e.articulation==='staccato')out+=`<circle cx="${x+7}" cy="${ay}" r="2" class="note-ink"/>`;if(e.articulation==='accent')out+=`<path d="M ${x+1} ${ay-4} L ${x+14} ${ay} L ${x+1} ${ay+4}" fill="none" stroke="#333"/>`;if(e.articulation==='tenuto')out+=line(x,ay,x+14,ay,'note-ink','stroke-width="2"');if(e.articulation==='fermata')out+=glyph('\uE4C0',x-3,Math.min(y-29,top-14),42);if(e.articulation==='breath')out+=glyph('\uE4CE',x+22,top-8,35);
    if(e.articulation==='staccatissimo')out+=`<path d="M ${x+3} ${ay-5} L ${x+11} ${ay-5} L ${x+7} ${ay+4} Z" class="note-ink"/>`;
    if(e.articulation==='marcato')out+=`<path d="M ${x+1} ${ay+4} L ${x+7} ${ay-5} L ${x+14} ${ay+4}" fill="none" stroke="#333"/>`;
    if(e.articulation==='portato')out+=line(x,ay-3,x+14,ay-3,'note-ink')+`<circle cx="${x+7}" cy="${ay+3}" r="1.8" class="note-ink"/>`;
    if(e.articulation==='legato')out+=drawArticulationSymbol('legato',x-4,Math.min(y-28,top-18));
    if(['pizzicato','arco'].includes(e.articulation))out+=`<text x="${x+7}" y="${Math.min(y-28,top-18)}" text-anchor="middle" class="expression-label">${e.articulation==='pizzicato'?'pizz.':e.articulation}</text>`;
    if(e.ornament)out+=glyph({trill:'\uE566',mordent:'\uE56D',turn:'\uE567'}[e.ornament],x-3,Math.min(y-48,top-28),35);
  }
  for(let dot=0;dot<M.dots(e);dot++)out+=`<circle class="augmentation-dot note-ink" cx="${x+21+dot*7}" cy="${e.type==='note'&&(y-base)%12===0?y-6:y}" r="1.9"/>`;
  if(e.exactTicks!==null&&e.exactTicks!==undefined)out+=`<text x="${x+7}" y="${Math.max(y+26,base+18)}" text-anchor="middle" font-size="8" fill="#7f887a">${M.fmt(M.ticks(e)/48)}拍</text>`;
  if(e.dynamic)out+=`<text x="${x+7}" y="${annotationY}" text-anchor="middle" class="notation-label">${e.dynamic}</text>`;
  if(e.expression){if(['crescendo','diminuendo'].includes(e.expression)){const wide=e.expression==='crescendo';out+=`<path d="M ${x-12} ${annotationY+(wide?0:-5)} L ${x+25} ${annotationY+(wide?-5:0)} M ${x-12} ${annotationY+(wide?0:5)} L ${x+25} ${annotationY+(wide?5:0)}" stroke="#333" fill="none"/>`;}else out+=`<text x="${x+7}" y="${Math.min(y-57,top-38)}" text-anchor="middle" class="expression-label">${e.expression}</text>`;}
  if(e.lyric&&e.type==='note')out+=`<text x="${x+7}" y="${lyricY}" text-anchor="middle" class="lyrics">${escapeXml(e.lyric)}</text>`;return out+'</g>';
}

function hideMenu(){clearTimeout(hideMenuTimer);hideMenuTimer=null;finishLyricEdit();$('contextMenu').hidden=true;menuTarget=null;}
function cancelHideMenu(){clearTimeout(hideMenuTimer);hideMenuTimer=null;}
function scheduleHideMenu(){if($('contextMenu').hidden||hideMenuTimer!==null)return;hideMenuTimer=setTimeout(()=>{hideMenuTimer=null;if(!$('contextMenu').matches(':hover'))hideMenu();},120);}
function isSelectedTarget(t){return t?.type==='note'?selectedNotes.has(t.id):t?.type==='measure'?!!selectedMeasureVoices.get(score.measures[t.mi]?.id)?.has(t.voice):t?.type==='symbol'?selectedSymbols.has(symbolKey(t)):false;}
function targetAt(element){const sym=element.closest('[data-symbol-kind]');if(sym)return {type:'symbol',kind:sym.dataset.symbolKind,mi:+sym.dataset.symbolMi,id:sym.dataset.symbolId||''};const note=element.closest('[data-id]');if(note){const f=findNote(note.dataset.id);return f?{type:'note',id:f.e.id,mi:f.mi}:null;}const bar=element.closest('.measure-click');return bar?{type:'measure',mi:+bar.dataset.mi,voice:bar.dataset.voice}:null;}
function hoverTargetAt(event){if(mode!=='select'||symbolTool)return null;const t=targetAt(event.target);if(t?.type==='note'){const p=notePositions.get(t.id),point=coordinates(event);if(!p||!point)return null;const rest=p.e.type==='rest',down=p.e.pitch>=p.bottomPitch+4,stem=!rest&&p.e.duration!==1,centerY=rest&&p.e.duration===1?p.top+12:p.y,above=rest?22:stem&&!down?44:14,below=rest?22:stem&&down?44:14;if(point.x<p.x-24||point.x>p.x+32||point.y<centerY-above||point.y>centerY+below)return null;}return t;}
function showMenu(t,x,y){if(mode!=='select'||symbolTool){hideMenu();return;}if(!isSelectedTarget(t)){scheduleHideMenu();return;}cancelHideMenu();const key=t.type==='symbol'?symbolKey(t):t.type+':'+(t.id||t.mi)+':'+(t.voice||''),old=menuTarget;menuTarget=t;menuTarget._key=key;const menu=$('contextMenu');if(menu.hidden||old?._key!==key){buildMenu();menu.hidden=false;const width=menu.offsetWidth,left=x+12+width<=window.innerWidth-8?x+12:x-width-12;menu.style.left=Math.max(8,Math.min(left,window.innerWidth-width-8))+'px';menu.style.top=Math.max(8,Math.min(y+8,window.innerHeight-menu.offsetHeight-84))+'px';}}
function menuChoice(label,attr,value,active=false){return `<button class="menu-choice${active?' active':''}" ${attr}="${escapeXml(JSON.stringify(value))}">${escapeXml(label)}</button>`;}
const propChoice=(k,v,label)=>menuChoice(label,`data-prop="${k}" data-value`,v);
const settingChoice=(k,v,label)=>menuChoice(label,`data-setting="${k}" data-value`,v);
const actionChoice=(action,label)=>`<button class="menu-choice" data-action="${action}">${escapeXml(label)}</button>`;
function category(label,html){return `<div class="menu-category"><button class="menu-category-title" aria-expanded="false">${escapeXml(label)}<span aria-hidden="true">›</span></button><div class="submenu">${html}</div></div>`;}
function buildMenu(){if(!menuTarget||!isSelectedTarget(menuTarget)){hideMenu();return;}const notes=selectedList(),bars=score.measures.filter(m=>selectedMeasures.has(m.id)),f=getSelected(),c=config();let out='';
  if(notes.length)out+=category('升降记号',[[null,'自动／沿用'],[1,'♯ 升'],[-1,'♭ 降'],[0,'♮ 还原'],[2,'𝄪 重升'],[-2,'𝄫 重降']].map(([v,l])=>propChoice('accidental',v,l)).join(''));
  if(notes.length)out+=category('时值',[1,2,4,8,16,32,64,128].map(d=>propChoice('duration',d,`${d} 分音符`)).join('')+'<div class="menu-divider"></div>'+[0,1,2,3].map(d=>propChoice('dots',d,['无附点','附点 ·','复附点 ··','三附点 ···'][d])).join(''));
  if(bars.length){out+=category('调号',(c.mode==='minor'?M.MINOR:M.MAJOR).map((n,i)=>settingChoice('key',i-7,n+(c.mode==='minor'?' 小调':' 大调'))).join(''));out+=category('调式',settingChoice('mode','major','大调')+settingChoice('mode','minor','小调'));out+=category('拍号／节奏',meterValues.map(v=>settingChoice('meter',v.split('/').map(Number),v)).join(''));out+=category('速度',`<label class="menu-field">♩ / 分钟<input id="menuBpm" type="number" min="30" max="240" value="${c.bpm}"></label>`+actionChoice('setBpm','设置速度…'));out+=category('当前声部谱号',Object.entries(clefNames).map(([v,l])=>settingChoice('clef',v,l)).join(''));}
  if(notes.length||bars.length){out+=category('力度',propChoice('dynamic','','取消力度')+dynamics.map(v=>propChoice('dynamic',v,v)).join(''));out+=category('表情',propChoice('expression','','取消表情')+M.EXPRESSIONS.map(([v,l])=>propChoice('expression',v,`${v} · ${l}`)).join(''));out+=category('奏法',propChoice('articulation','','取消奏法')+articulations.map(([v,l])=>propChoice('articulation',v,l)).join(''));out+=category('装饰音',propChoice('ornament','','取消装饰音')+[['trill','tr · 颤音'],['mordent','波音'],['turn','回音']].map(([v,l])=>propChoice('ornament',v,l)).join(''));out+=category('八度线',[[0,'取消八度线'],[1,'8va · 高八度'],[-1,'8vb · 低八度'],[2,'15ma · 高两八度'],[-2,'15mb · 低两八度']].map(([v,l])=>menuChoice(l,'data-menu-symbol="ottava" data-value',v)).join(''));}
  if(notes.length){out+=category('连线',menuChoice('添加延音线','data-menu-symbol="tie" data-value',true)+propChoice('tie',false,'取消延音线')+menuChoice('添加圆滑线','data-menu-symbol="slur" data-value','add')+actionChoice('removeSlur','取消圆滑线'));out+=category('音高',actionChoice('pitchUp','↑ 上移一个谱位')+actionChoice('pitchDown','↓ 下移一个谱位'));const lyric=notes.find(e=>e.id===selected&&e.type==='note')||notes.find(e=>e.type==='note');if(lyric)out+=category('歌词',`<label class="menu-field">歌词<input id="menuLyric" data-lyric-id="${lyric.id}" value="${escapeXml(lyric.lyric)}" maxlength="80" placeholder="输入歌词，Enter 保存"></label>`+actionChoice('saveLyric','保存歌词'));}
  if(bars.length)out+=category('反复／返回',menuChoice('𝄆 反复起点','data-menu-symbol="repeatStart" data-value',true)+menuChoice('取消反复起点','data-menu-symbol="repeatStart" data-value',false)+[0,2,3,4,5,6,7,8].map(v=>menuChoice(v?`𝄇 共 ${v} 遍`:'取消反复终点','data-menu-symbol="repeatEnd" data-value',v)).join('')+['','1','2','3','1,2','2,3'].map(v=>menuChoice(v?`${v}. 结尾`:'取消结尾','data-menu-symbol="ending" data-value',v)).join('')+Object.entries(navNames).map(([v,l])=>menuChoice(l,'data-menu-symbol="navigation" data-value',v)).join('')+menuChoice('取消返回标记','data-menu-symbol="navigation" data-value',''));
  if(selectedSymbols.size){const t=[...selectedSymbols.values()].at(-1);let html='';if(t.kind==='ottava'||t.kind==='measureOctave')html=[[0,'取消八度线'],[1,'8va'],[-1,'8vb'],[2,'15ma'],[-2,'15mb']].map(([v,l])=>menuChoice(l,'data-symbol-value',v)).join('');else if(t.kind==='repeatEnd')html=[2,3,4,5,6,7,8].map(v=>menuChoice(`共 ${v} 遍`,'data-symbol-value',v)).join('');else if(t.kind==='ending')html=['1','2','3','1,2','2,3'].map(v=>menuChoice(`${v}. 结尾`,'data-symbol-value',v)).join('');else if(t.kind==='navigation')html=Object.entries(navNames).map(([v,l])=>menuChoice(l,'data-symbol-value',v)).join('');else if(t.kind==='tuplet'){const e=findNote(t.id)?.e;html=`<label class="menu-field">连音数量<input id="menuTupletCount" type="number" min="2" max="32" value="${e?.tuplet?.count||3}"></label><label class="menu-field">总时值（四分拍）<input id="menuTupletTotal" type="number" min="0.125" max="32" step="0.125" value="${e?.tuplet?.total||1}"></label>`+actionChoice('updateTuplet','修改连音组');}out+=category('所选符号',html+actionChoice('removeSymbols','删除所选符号'));}
  out+=category('删除',actionChoice('delete','删除所选对象'));$('contextMenu').innerHTML=out;
}
function openCategory(cat){const menu=$('contextMenu');menu.querySelectorAll('.menu-category').forEach(e=>{e.classList.toggle('open',e===cat);e.querySelector('.menu-category-title').setAttribute('aria-expanded',String(e===cat));});const sub=cat.querySelector('.submenu'),r=cat.getBoundingClientRect(),mr=menu.getBoundingClientRect();sub.style.left=Math.max(8,Math.min(mr.right-1,window.innerWidth-sub.offsetWidth-8))+'px';sub.style.top=Math.max(8,Math.min(r.top,window.innerHeight-sub.offsetHeight-82))+'px';}
$('contextMenu').addEventListener('pointerover',e=>{cancelHideMenu();const cat=e.target.closest('.menu-category');if(cat&&!cat.classList.contains('open'))openCategory(cat);});$('contextMenu').addEventListener('pointerleave',scheduleHideMenu);
document.addEventListener('pointerover',e=>{if(!$('score').contains(e.target)&&!$('contextMenu').contains(e.target))hideMenu();});window.addEventListener('blur',hideMenu);
function setAnnotation(k,v){if(['dynamic','expression','articulation','ornament'].includes(k)){commit(()=>{selectedList().forEach(e=>e[k]=v);score.measures.filter(m=>selectedMeasures.has(m.id)).forEach(m=>m[k]=v);});defaults[k]=v;}else setProp(k,v);}
function saveLyric(){const input=$('menuLyric');if(!input)return;const f=findNote(input.dataset.lyricId),value=input.value;if(f)commit(()=>f.e.lyric=value);}
function finishLyricEdit(){if(lyricEditBefore!==null&&lyricEditBefore!==snapshot()){undoStack.push(lyricEditBefore);if(undoStack.length>120)undoStack.shift();redoStack=[];}lyricEditBefore=null;}
$('contextMenu').addEventListener('focusin',e=>{if(e.target.id==='menuLyric')lyricEditBefore=snapshot();});
$('contextMenu').addEventListener('input',e=>{if(e.target.id!=='menuLyric')return;const f=findNote(e.target.dataset.lyricId);if(f){f.e.lyric=e.target.value;renderScore();save();}});
$('contextMenu').addEventListener('focusout',e=>{if(e.target.id==='menuLyric'){finishLyricEdit();syncTools();}});
$('contextMenu').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.classList.contains('menu-category-title')){openCategory(b.parentElement);return;}if(b.dataset.setting){requestSetting(b.dataset.setting,JSON.parse(b.dataset.value));return;}if(b.dataset.prop){setAnnotation(b.dataset.prop,JSON.parse(b.dataset.value));return;}if(b.dataset.menuSymbol){useSymbol(b.dataset.menuSymbol,JSON.parse(b.dataset.value),b.textContent);return;}if(b.hasAttribute('data-symbol-value')){editSymbols(JSON.parse(b.dataset.symbolValue));return;}const action=b.dataset.action;if(action==='delete')deleteSelected();if(action==='pitchUp')movePitch(1);if(action==='pitchDown')movePitch(-1);if(action==='setBpm')requestSetting('bpm',Number($('menuBpm').value));if(action==='saveLyric')saveLyric();if(action==='removeSlur')commit(()=>{const ids=new Set(selectedList().map(e=>e.slur).filter(Boolean));score.measures.flatMap(m=>m.events).filter(e=>ids.has(e.slur)).forEach(e=>e.slur='');});if(action==='removeSymbols')commit(()=>{selectedSymbols.forEach(removeSymbol);selectedSymbols.clear();hideMenu();});if(action==='updateTuplet')updateTupletSymbols();});
$('contextMenu').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='menuLyric'){e.preventDefault();saveLyric();}});
$('contextMenu').addEventListener('change',e=>{if(e.target.id==='menuLyric')saveLyric();});
function requestSetting(k,value){if(k==='bpm'&&(!Number.isFinite(value)||value<30||value>240)){toast('速度应在 30–240 之间。');syncSettings();return;}hideMenu();const chosen=score.measures.map((m,i)=>selectedMeasures.has(m.id)?i:-1).filter(i=>i>=0),indices=chosen.length?chosen:[currentMeasure],start=Math.min(...indices);pendingScope={k,value,indices,start,voice:activeVoice};$('scopeDescription').textContent=`${{key:'调号',mode:'调式',meter:'拍号',bpm:'速度',clef:'谱号'}[k]}修改 · 第 ${start+1} 小节${indices.length>1?'；“当前小节”会修改全部选中的小节':''}`;$('scopeDialog').showModal();}
function applyScope(following){const p=pendingScope;pendingScope=null;$('scopeDialog').close();if(!p)return;commit(()=>{const indices=following?score.measures.map((m,i)=>i).filter(i=>i>=p.start):p.indices;indices.forEach(mi=>{const m=score.measures[mi];if(p.k==='clef'){m.clefs??={};m.clefs[p.voice]=p.value;}else m[p.k]=Array.isArray(p.value)?[...p.value]:p.value;});});}
$('scopeCurrent').onclick=()=>applyScope(false);$('scopeFollowing').onclick=()=>applyScope(true);$('cancelScope').onclick=()=>{pendingScope=null;$('scopeDialog').close();syncSettings();};$('scopeDialog').addEventListener('cancel',()=>{pendingScope=null;syncSettings();});

function coordinates(event){const svg=$('score').querySelector('svg');if(!svg)return null;const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function clearPlaceholders(mi,voice){score.measures[mi].events=score.measures[mi].events.filter(e=>!(e.voice===voice&&e.placeholder));}
function positionRatio(g,x){return Math.max(0,Math.min(1,(x-g.start-g.header-26)/Math.max(1,g.end-g.start-g.header-58)));}
function cycleNote(id){const f=findNote(id);if(!f)return;activeVoice=f.e.voice;currentMeasure=f.mi;const pos=notePositions.get(id),g=geometry.find(g=>g.mi===f.mi&&g.voice===f.e.voice);clearSelection();commit(()=>{if(f.e.type==='note'){f.e.type='rest';f.e.entryAnchor=true;if(g&&pos)f.e.positionRatio=positionRatio(g,pos.x);f.e.tie=false;selected=id;selectedNotes.add(id);}else{score.measures[f.mi].events.splice(f.ei,1);}});}
function betweenNotes(a,b){if(a.voice!==b.voice)return [a,b];const all=score.measures.flatMap(m=>M.events(score,m,a.voice)),i=all.indexOf(a),j=all.indexOf(b);return all.slice(Math.min(i,j),Math.max(i,j)+1);}
const measureSymbolKinds=['repeatStart','repeatEnd','ending','navigation'];
function applySymbolTo(kind,value,list,mis=[]){if(measureSymbolKinds.includes(kind)){mis.forEach(mi=>score.measures[mi][kind]=value);return;}if(kind==='ottava'){list.forEach(e=>e.ottava=Number(value));mis.forEach(mi=>{score.measures[mi].octaves??={};score.measures[mi].octaves[activeVoice]=Number(value);});}if(kind==='tie')list.forEach(e=>e.tie=!!value);if(kind==='slur'){const gid=M.id();list.forEach(e=>e.slur=value==='add'?gid:'');}}
function useSymbol(kind,value,label){hideMenu();const notes=selectedList(),mis=score.measures.map((m,i)=>selectedMeasures.has(m.id)?i:-1).filter(i=>i>=0);if((measureSymbolKinds.includes(kind)&&mis.length)||(!measureSymbolKinds.includes(kind)&&(notes.length||mis.length))){commit(()=>{if(kind==='slur'||kind==='tie')mis.forEach(mi=>notes.push(...M.events(score,score.measures[mi],activeVoice)));applySymbolTo(kind,value,notes,mis);});symbolTool=null;symbolStart=null;syncTools();return;}symbolTool={kind,value,label};symbolStart=null;syncTools();}
function placeSymbol(t){const {kind,value}=symbolTool;if(measureSymbolKinds.includes(kind)){commit(()=>applySymbolTo(kind,value,[],[t.mi]));return;}if(t.type!=='note'){if(kind==='ottava'){activeVoice=t.voice||activeVoice;commit(()=>applySymbolTo(kind,value,[],[t.mi]));return;}toast('连线需要音符作为连接位置；请点击音符。');return;}const f=findNote(t.id);if(!f)return;activeVoice=f.e.voice;currentMeasure=f.mi;
  if(['ottava','slur'].includes(kind)){if(!symbolStart){symbolStart={id:f.e.id,gid:M.id()};commit(()=>{if(kind==='slur')f.e.slur=symbolStart.gid;else f.e.ottava=Number(value);});}else{const a=findNote(symbolStart.id)?.e,gid=symbolStart.gid;if(a)commit(()=>{const list=betweenNotes(a,f.e);if(kind==='slur')list.forEach(e=>e.slur=gid);else applySymbolTo(kind,value,list);});symbolStart=null;}syncTools();}else commit(()=>applySymbolTo(kind,value,[f.e]));
}
function octaveGroup(t){const f=findNote(t.id);if(!f)return [];const all=score.measures.flatMap(m=>M.events(score,m,f.e.voice)),idx=all.indexOf(f.e),value=f.e.ottava;let a=idx,b=idx;while(a>0&&all[a-1].ottava===value)a--;while(b+1<all.length&&all[b+1].ottava===value)b++;return all.slice(a,b+1);}
function removeSymbol(t){const m=score.measures[t.mi],f=findNote(t.id);if(!m)return;if(t.kind==='measureOctave'){if(m.octaves)delete m.octaves[t.id];return;}if(measureSymbolKinds.includes(t.kind)){m[t.kind]=t.kind==='repeatStart'?false:t.kind==='repeatEnd'?0:'';return;}if(!f)return;if(t.kind==='ottava')octaveGroup(t).forEach(e=>e.ottava=0);if(t.kind==='tie')f.e.tie=false;if(t.kind==='slur'){const id=f.e.slur;score.measures.flatMap(m=>m.events).filter(e=>e.slur===id).forEach(e=>e.slur='');}if(t.kind==='tuplet'){const gid=f.e.tuplet?.id;if(gid)score.measures.flatMap(m=>m.events).filter(e=>e.tuplet?.id===gid).forEach(e=>{e.tuplet=null;e.exactTicks=null;});}}
function editSymbols(value){commit(()=>selectedSymbols.forEach(t=>{if(t.kind==='measureOctave'){score.measures[t.mi].octaves[t.id]=Number(value);return;}if(measureSymbolKinds.includes(t.kind))score.measures[t.mi][t.kind]=value;else if(t.kind==='ottava')octaveGroup(t).forEach(e=>e.ottava=Number(value));}));}
function updateTupletSymbols(){const count=Number($('menuTupletCount').value),total=Number($('menuTupletTotal').value);commit(()=>{if(!Number.isInteger(count)||count<2||count>32||!Number.isFinite(total)||total<.125||total>32)throw new Error('连音数量为 2–32，总时值为 0.125–32 拍。');selectedSymbols.forEach(t=>{if(t.kind!=='tuplet')return;const gid=findNote(t.id)?.e.tuplet?.id,group=score.measures.flatMap(m=>m.events).filter(e=>e.tuplet?.id===gid);M.setTuplet(group,count,total);});});}
$('score').addEventListener('click',e=>{const t=targetAt(e.target),add=e.ctrlKey||e.metaKey;if(symbolTool&&t){placeSymbol(t);return;}if(t?.type==='symbol'){selectSymbol(t,add);showMenu(t,e.clientX,e.clientY);return;}if(t?.type==='note'){if(mode==='select'||add){select(t.id,add);showMenu(t,e.clientX,e.clientY);}else cycleNote(t.id);$('score').focus({preventScroll:true});return;}const label=e.target.closest('.voice-label');if(label){activeVoice=label.dataset.voice;clearSelection();stop();render();return;}const p=coordinates(e);if(!p||t?.type!=='measure')return;const g=geometry.find(g=>g.mi===t.mi&&g.voice===t.voice);if(!g)return;activeVoice=g.voice;currentMeasure=g.mi;
  if(mode==='select'||add){selectMeasure(g.mi,g.voice,add);showMenu(t,e.clientX,e.clientY);$('score').focus({preventScroll:true});return;}
  const pitch=Math.max(0,Math.min(66,g.bottomPitch+Math.round((g.base-p.y)/6))),at=g.positions.find(n=>!n.e.placeholder&&Math.abs(n.x-p.x)<20&&(n.e.pitch===pitch||n.e.type==='rest'&&n.e.entryAnchor));if(at){cycleNote(at.e.id);return;}const following=g.positions.find(n=>p.x<n.x&&!n.e.placeholder),n=M.event(pitch,{...defaults,voice:activeVoice,type:'note',entryAnchor:true,positionRatio:positionRatio(g,p.x),triplet:false,tie:false});clearSelection();commit(()=>{clearPlaceholders(currentMeasure,activeVoice);const arr=score.measures[currentMeasure].events,idx=following?arr.findIndex(e=>e.id===following.e.id):arr.length;arr.splice(idx,0,n);selected=n.id;selectedNotes.add(n.id);});$('score').focus({preventScroll:true});
});
$('score').addEventListener('pointermove',e=>{const t=targetAt(e.target),hover=hoverTargetAt(e);if(isSelectedTarget(hover))showMenu(hover,e.clientX,e.clientY);else scheduleHideMenu();const p=coordinates(e),ghost=$('ghost');if(!p||!ghost)return;const g=geometry.find(g=>p.x>=g.start&&p.x<g.end&&p.y>=g.offset+4&&p.y<g.rowEnd-4);if(!g||mode!=='edit'||symbolTool||t?.type!=='measure'){ghost.innerHTML='';return;}const pitch=Math.max(0,Math.min(66,g.bottomPitch+Math.round((g.base-p.y)/6))),y=g.base-(pitch-g.bottomPitch)*6;ghost.innerHTML=glyph('\uE0A4',p.x,y)+`<text x="${p.x+20}" y="${y-8}" font-size="10" fill="#38624f">${M.pitchName(pitch,M.keyMap(config(g.mi,g.voice).key)[M.letter(pitch)]||0)}</text>`;});$('score').addEventListener('pointerleave',()=>{if($('ghost'))$('ghost').innerHTML='';scheduleHideMenu();});
function deleteSelected(){const ids=new Set(selectedNotes),bars=new Set(selectedMeasures),symbols=[...selectedSymbols.values()];if(!ids.size&&!bars.size&&!symbols.length)return;const remove=()=>commit(()=>{symbols.forEach(removeSymbol);score.measures.forEach(m=>m.events=m.events.filter(e=>!ids.has(e.id)));score.measures=score.measures.filter(m=>!bars.has(m.id));if(!score.measures.length)score.measures=[M.measure()];clearSelection();});if(bars.size)confirmAction('删除小节',`将删除选中的 ${bars.size} 个小节及其所有声部内容，可撤销。`,remove);else remove();}
function movePitch(dir){const list=selectedList().filter(e=>e.type==='note');if(list.length)commit(()=>list.forEach(e=>e.pitch=Math.max(0,Math.min(66,e.pitch+dir))));}
function navigate(dir){const notes=score.measures.flatMap(m=>M.events(score,m,activeVoice)),i=notes.findIndex(e=>e.id===selected),next=notes[i+dir];if(next)select(next.id);}
function toggleMode(){if(document.activeElement?.matches('input,select,textarea'))document.activeElement.blur();mode=mode==='edit'?'select':'edit';symbolTool=null;symbolStart=null;hideMenu();syncTools();$('score').focus({preventScroll:true});}
$('modeToggle').onclick=toggleMode;
function confirmAction(title,text,fn){hideMenu();$('confirmTitle').textContent=title;$('confirmText').textContent=text;pendingConfirm=fn;$('confirmDialog').showModal();}$('cancelConfirm').onclick=()=>{$('confirmDialog').close();pendingConfirm=null;};$('acceptConfirm').onclick=()=>{const fn=pendingConfirm;pendingConfirm=null;$('confirmDialog').close();fn?.();};$('confirmDialog').addEventListener('cancel',()=>pendingConfirm=null);
function offerFix(kind='all',id=null){try{const fixed=M.repair(score,kind,id);commit(()=>{score=fixed;clearSelection();});toast('已修正，可撤销。');}catch(e){toast(e.message);}}$('fixAll').onclick=()=>offerFix();
['mode','key','clef','meter','bpm'].forEach(k=>$(k).onchange=e=>requestSetting(k,k==='meter'?e.target.value.split('/').map(Number):['key','bpm'].includes(k)?Number(e.target.value):e.target.value));$('title').onchange=e=>commit(()=>score.title=e.target.value.trim()||'未命名作品');
$('voice').onchange=e=>{stop();activeVoice=e.target.value;clearSelection();render();};$('voiceName').onchange=e=>commit(()=>part().name=e.target.value.trim()||'声部');$('muteVoice').onchange=e=>commit(()=>part().muted=e.target.checked);$('solo').onchange=stop;
function addVoice(name=null,clef='treble'){if(score.voices.length>=16)throw new Error('最多 16 个声部。');const v={id:M.id(),name:name||`声部 ${score.voices.length+1}`,clef,muted:false};score.voices.push(v);score.measures.forEach((m,mi)=>m.events.push(...M.restPieces(M.capacity(score,mi),v.id).map(e=>({...e,placeholder:true}))));return v;}
$('addVoice').onclick=()=>commit(()=>{activeVoice=addVoice().id;clearSelection();});$('removeVoice').onclick=()=>{if(score.voices.length===1)return;const v=part();confirmAction('删除声部',`将删除“${v.name}”及其音符和歌词，可撤销。`,()=>commit(()=>{score.voices=score.voices.filter(x=>x.id!==v.id);score.measures.forEach(m=>{m.events=m.events.filter(e=>e.voice!==v.id);delete m.clefs?.[v.id];delete m.octaves?.[v.id];});activeVoice=score.voices[0].id;clearSelection();}));};
document.querySelectorAll('[data-duration]').forEach(b=>b.onclick=()=>setProp('duration',+b.dataset.duration));$('dots').onchange=e=>setProp('dots',+e.target.value);
document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>useSymbol(b.dataset.symbol,b.dataset.symbol==='slur'?b.dataset.value:b.dataset.symbol==='repeatEnd'?Math.max(2,Math.min(8,Math.round(Number($('repeatTimes').value)||2))):JSON.parse(b.dataset.value),b.textContent));$('endingTool').onchange=e=>{if(e.target.value)useSymbol('ending',e.target.value==='clear'?'':e.target.value,e.target.selectedOptions[0].textContent);e.target.value='';};$('navigationTool').onchange=e=>{if(e.target.value)useSymbol('navigation',e.target.value==='clear'?'':e.target.value,e.target.selectedOptions[0].textContent);e.target.value='';};$('cancelSymbol').onclick=()=>{symbolTool=null;symbolStart=null;syncTools();};
$('tupletsToggle').onclick=()=>{$('advanced').hidden=!$('advanced').hidden;$('tupletsToggle').classList.toggle('active',!$('advanced').hidden);};$('tupletCount').oninput=e=>{$('tupletRange').value=Math.max(2,Math.min(32,+e.target.value||3));syncTuplet();};$('tupletCount').onchange=e=>{e.target.value=Math.max(2,Math.min(32,Math.round(+e.target.value)||3));syncTuplet();};$('tupletRange').oninput=e=>{$('tupletCount').value=e.target.value;syncTuplet();};$('tupletTotal').oninput=syncTuplet;
function tupletParams(){const count=Math.round(+$('tupletCount').value),total=+$('tupletTotal').value;if(count<2||count>32||!Number.isFinite(total)||total<.125||total>32)throw new Error('连音数量为 2–32，总时值为 0.125–32 个四分拍。');return {count,total};}
$('insertTuplet').onclick=()=>commit(()=>{const {count,total}=tupletParams(),f=getSelected(),v=activeVoice,pitch=f?.e.type==='note'?f.e.pitch:(config().clef==='bass'?22:34);clearPlaceholders(currentMeasure,v);const arr=score.measures[currentMeasure].events,idx=f?arr.findIndex(e=>e.id===f.e.id)+1:arr.length,list=Array.from({length:count},()=>M.event(pitch,{voice:v,accidental:defaults.accidental,ottava:defaults.ottava}));M.setTuplet(list,count,total);arr.splice(idx,0,...list);clearSelection();list.forEach(e=>selectedNotes.add(e.id));selected=list[0].id;defaults.duration=list[0].duration;defaults.dots=list[0].dots;});
$('applyTuplet').onclick=()=>commit(()=>{const f=getSelected();if(!f)throw new Error('请选中音符或休止符。');const {count,total}=tupletParams(),all=score.measures.flatMap(m=>M.events(score,m,activeVoice)),idx=all.findIndex(e=>e.id===f.e.id);let list;if(selectedNotes.size>1){list=all.filter(e=>selectedNotes.has(e.id));if(list.length!==selectedNotes.size)throw new Error('连音组应属于同一声部。');if(list.some((e,i)=>i&&all.indexOf(e)!==all.indexOf(list[i-1])+1))throw new Error('连音组应选择连续的音符或休止符。');}else if(f.e.tuplet)list=all.filter(e=>e.tuplet?.id===f.e.tuplet.id);else list=all.slice(idx,idx+count);M.setTuplet(list,count,total);defaults.duration=list[0].duration;defaults.dots=list[0].dots;});
$('removeTuplet').onclick=()=>commit(()=>{const gids=new Set(selectedList().map(e=>e.tuplet?.id).filter(Boolean));score.measures.flatMap(m=>m.events).filter(e=>gids.has(e.tuplet?.id)).forEach(e=>{e.tuplet=null;e.exactTicks=null;});selectedSymbols.forEach(t=>{if(t.kind==='tuplet')removeSymbol(t);});});
$('addMeasure').onclick=()=>commit(()=>{if(score.measures.length>=300)throw new Error('最多 300 小节。');const c=config(score.measures.length-1),clefs={};score.voices.forEach(v=>clefs[v.id]=config(score.measures.length-1,v.id).clef);score.measures.push(M.measure({key:c.key,mode:c.mode,meter:[...c.meter],bpm:c.bpm,clefs}));currentMeasure=score.measures.length-1;clearSelection();});
function history(dir){stop();const src=dir<0?undoStack:redoStack,dest=dir<0?redoStack:undoStack;if(!src.length)return;dest.push(snapshot());score=JSON.parse(src.pop());clearSelection();render();save();}$('undo').onclick=()=>history(-1);$('redo').onclick=()=>history(1);
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Tab'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();toggleMode();return;}if(e.key==='Escape'){e.preventDefault();symbolTool=null;symbolStart=null;clearSelection();render();return;}if(e.target.matches('input,select,textarea'))return;if(e.ctrlKey||e.metaKey){if(e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?1:-1);}if(e.key.toLowerCase()==='y'){e.preventDefault();history(1);}return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelected();}if(e.key==='ArrowUp'){e.preventDefault();movePitch(1);}if(e.key==='ArrowDown'){e.preventDefault();movePitch(-1);}if(e.key==='ArrowRight'){e.preventDefault();navigate(1);}if(e.key==='ArrowLeft'){e.preventDefault();navigate(-1);}if(e.code==='Space'){e.preventDefault();playSession?stop():play();}});
$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('print').onclick=()=>window.print();
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(score,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=score.title.replace(/[\\/:*?"<>|]/g,'_')+'.score.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已导出全部声部、歌词、小节设置和符号。');};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>8e6)throw new Error('文件过大。');const imported=M.sanitize(JSON.parse(await f.text()));confirmAction('打开乐谱','当前内容可撤销恢复。',()=>commit(()=>{score=imported;activeVoice=score.voices[0].id;currentMeasure=0;clearSelection();}));}catch(err){toast(err.message||'无法读取乐谱。');}e.target.value='';};
$('new').onclick=()=>confirmAction('新建乐谱','当前作品可先导出备份。新建后可撤销恢复。',()=>commit(()=>{score=M.blank();activeVoice=score.voices[0].id;currentMeasure=0;clearSelection();defaults={duration:4,dots:0,triplet:false,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false};}));
['highest','lowest'].forEach(k=>$(k+'Button').onclick=()=>{const id=M.stats(score)[k+'Id'];if(id){mode='select';select(id);$('score').querySelector(`[data-id="${id}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});}});

const sampleMidi=name=>{const m=name.match(/^(C|Ds|Fs|A)(\d)$/);return (+m[2]+1)*12+({C:0,Ds:3,Fs:6,A:9}[m[1]]);};
async function pianoBuffer(midi){const name=Object.keys(PIANO_SAMPLES).reduce((best,n)=>Math.abs(sampleMidi(n)-midi)<Math.abs(sampleMidi(best)-midi)?n:best);if(!buffers.has(name)){const bytes=Uint8Array.from(atob(PIANO_SAMPLES[name]),c=>c.charCodeAt(0));buffers.set(name,audioContext.decodeAudioData(bytes.buffer));}return {buffer:await buffers.get(name),base:sampleMidi(name)};}
function stop(){if(playSession){playSession.cancelled=true;playSession.sources.forEach(s=>{try{s.stop();}catch{}});cancelAnimationFrame(playSession.raf);playSession=null;}$('play').disabled=false;$('play').textContent='▶ 播放';$('stop').disabled=true;$('playTime').textContent='0:00';document.querySelectorAll('.playing').forEach(e=>e.classList.remove('playing'));}
async function play(){if(playSession)return;const t=M.timeline(score);if(!t.notes.length){toast('请先输入乐谱。');return;}if(t.warnings.length){toast('请先修正反复与返回标记。');return;}
  try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();const session={sources:[],cancelled:false};playSession=session;$('play').disabled=true;$('play').textContent='加载钢琴…';$('stop').disabled=false;
    const audible=score.voices.filter(v=>!v.muted&&(!$('solo').checked||v.id===activeVoice)).map(v=>v.id),samples=new Map();await Promise.all(t.notes.filter(n=>n.midi!==null&&audible.includes(n.voice)).map(async n=>{if(!samples.has(n.midi))samples.set(n.midi,pianoBuffer(n.midi));}));await Promise.all(samples.values());if(session.cancelled)return;
    const start=audioContext.currentTime+.12;session.start=start;const mix=.85/Math.sqrt(Math.max(1,audible.length));
    for(const n of t.notes){if(n.midi===null||n.continuation||!audible.includes(n.voice))continue;const sample=await samples.get(n.midi),source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=sample.buffer;source.playbackRate.value=Math.pow(2,(n.midi-sample.base)/12);let length=n.seconds,last=n;while(last.validTie){last=last.next;length+=last.seconds;}const art=last.articulation,gate=art==='staccatissimo'?.25:art==='staccato'?.48:art==='tenuto'||art==='legato'?1:.93,on=start+n.start,off=on+Math.max(.012,length*gate),level=Math.max(.01,n.volume*(['accent','marcato'].includes(n.articulation)?1.18:1)*mix);gain.gain.setValueAtTime(0,on);gain.gain.linearRampToValueAtTime(level,on+.004);gain.gain.setValueAtTime(level,Math.max(on+.004,off-.01));gain.gain.exponentialRampToValueAtTime(.001,off+.08);source.connect(gain).connect(audioContext.destination);source.start(on);source.stop(off+.1);session.sources.push(source);}
    $('play').textContent='正在播放…';function tick(){if(session.cancelled)return;const elapsed=Math.max(0,audioContext.currentTime-start);$('playTime').textContent=timeText(elapsed);document.querySelectorAll('.playing').forEach(e=>e.classList.remove('playing'));const sounding=t.notes.filter(n=>elapsed>=n.start&&elapsed<n.start+n.seconds&&audible.includes(n.voice));sounding.forEach(n=>$('score').querySelector(`[data-id="${n.e.id}"]`)?.classList.add('playing'));if(elapsed>=t.seconds+.12){stop();return;}session.raf=requestAnimationFrame(tick);}tick();
  }catch(e){stop();toast('音频启动失败：'+e.message);}
}
$('play').onclick=play;$('stop').onclick=stop;new ResizeObserver(()=>{clearTimeout(renderScore.timer);renderScore.timer=setTimeout(renderScore,80);}).observe($('score'));document.fonts.ready.then(renderScore);window.addEventListener('beforeunload',save);render();
