(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MusicCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const LETTERS=['C','D','E','F','G','A','B'],SEMITONES=[0,2,4,5,7,9,11];
  const SHARPS=['F','C','G','D','A','E','B'],FLATS=['B','E','A','D','G','C','F'];
  const MAJOR=['C♭','G♭','D♭','A♭','E♭','B♭','F','C','G','D','A','E','B','F♯','C♯'];
  const MINOR=['A♭','E♭','B♭','F','C','G','D','A','E','B','F♯','C♯','G♯','D♯','A♯'];
  const ACC={'-2':'𝄫','-1':'♭','0':'♮','1':'♯','2':'𝄪'},EPS=1e-7;
  const EXPRESSIONS=[['dolce','柔美'],['cantabile','如歌'],['espressivo','富于表情'],['leggiero','轻巧'],['energico','有力'],['sostenuto','持续'],['maestoso','庄严'],['grazioso','优雅'],['con brio','有活力'],['con moto','流动'],['affettuoso','深情'],['amoroso','柔情'],['appassionato','热情'],['agitato','激动'],['animato','活泼'],['tranquillo','宁静'],['sereno','安详'],['mesto','悲伤'],['malinconico','忧郁'],['giocoso','欢乐'],['scherzando','诙谐'],['risoluto','坚定'],['marcato','突出'],['pesante','沉重'],['brillante','辉煌'],['semplice','朴素'],['delicato','细腻'],['con fuoco','热烈'],['con spirito','精神饱满'],['sotto voce','轻声'],['doloroso','悲痛'],['solenne','庄重'],['nobile','高贵'],['calmo','平静'],['misterioso','神秘'],['teneramente','温柔'],['crescendo','渐强'],['diminuendo','渐弱']];
  const id=()=> 'n'+Math.random().toString(36).slice(2,11),close=(a,b)=>Math.abs(a-b)<EPS,fmt=n=>Number(n.toFixed(4)).toString();
  const voices=s=>s.voices?.length?s.voices:[{id:'v1',name:'旋律',clef:s.clef||'treble',muted:false}],voiceId=(s,e)=>e.voice||voices(s)[0].id;
  const events=(s,m,vid)=>m.events.filter(e=>voiceId(s,e)===vid);
  function blank(){return {version:3,title:'未命名作品',key:0,mode:'major',clef:'treble',meter:[4,4],bpm:96,voices:[{id:'v1',name:'声部 1',clef:'treble',muted:false}],measures:[measure()]};}
  function measure(extra={}){return {id:id(),events:[],key:null,mode:null,meter:null,bpm:null,clefs:{},octaves:{},dynamic:'',expression:'',articulation:'',ornament:'',repeatStart:false,repeatEnd:0,ending:'',navigation:'',...extra};}
  function settings(s,mi=0,vid=null){const m=s.measures[mi]||{},v=voices(s).find(v=>v.id===vid)||voices(s)[0];return {key:m.key??s.key,mode:m.mode??s.mode,meter:m.meter||s.meter,bpm:m.bpm??s.bpm,clef:m.clefs?.[v.id]||v.clef};}
  function event(pitch=30,extra={}){return {id:id(),voice:'v1',type:'note',pitch,duration:4,dots:0,dotted:false,triplet:false,tuplet:null,exactTicks:null,ottava:0,slur:'',ornament:'',accidental:null,lyric:'',dynamic:'',expression:'',articulation:'',tie:false,...extra};}
  const dots=e=>e.dots??(e.dotted?1:0),dotFactor=n=>2-Math.pow(2,-n);
  function ticks(e){if(e.exactTicks!==null&&e.exactTicks!==undefined)return e.exactTicks;if(e.tuplet)return e.tuplet.total*48/e.tuplet.count;return 192/e.duration*dotFactor(dots(e))*(e.triplet?2/3:1);}
  const capacity=(s,mi=0)=>{const meter=settings(s,mi).meter;return meter[0]*192/meter[1];};
  function keyMap(key){const out={};(key>=0?SHARPS:FLATS).slice(0,Math.abs(key)).forEach(l=>out[l]=Math.sign(key));return out;}
  const letter=p=>LETTERS[((p%7)+7)%7],naturalMidi=p=>(Math.floor(p/7)+1)*12+SEMITONES[((p%7)+7)%7];
  const pitchName=(p,a=0)=>letter(p)+(a===0?'':ACC[a])+Math.floor(p/7),clefShift=v=>v.clef==='treble8vb'?-1:v.clef==='treble8va'?1:0;
  function resolved(s){const out=[];
    voices(s).forEach(v=>{let previous=null,sequence=0;s.measures.forEach((m,mi)=>{const state={},config=settings(s,mi,v.id),key=keyMap(config.key);let beat=0;
      events(s,m,v.id).forEach((e,ei)=>{const shift=(e.ottava||m.octaves?.[v.id]||0)+clefShift({clef:config.clef}),prior=state[e.pitch]??key[letter(e.pitch)]??0;
        const crossTie=e.type==='note'&&ei===0&&previous?.e.tie&&previous.e.pitch===e.pitch&&previous.shift===shift&&e.accidental===null;
        const acc=crossTie?previous.acc:e.accidental===null?prior:e.accidental;if(e.type==='note'&&!crossTie)state[e.pitch]=acc;
        const n={e,voice:v.id,voiceName:v.name,mi,ei,sequence:sequence++,beat,shift,acc,prior,articulation:e.articulation||m.articulation||'',midi:e.type==='note'?naturalMidi(e.pitch)+acc+shift*12:null,name:e.type==='note'?pitchName(e.pitch+shift*7,acc):'休止符',redundant:e.type==='note'&&e.accidental!==null&&e.accidental===prior};out.push(n);beat+=ticks(e);previous=n;
      });});});return out;
  }
  const endingNumbers=m=>String(m.ending||'').split(',').map(Number).filter(n=>n>=1&&n<=8);
  function playbackRoute(s){const pairs=[],stack=[],warnings=[];
    s.measures.forEach((m,i)=>{if(m.repeatStart)stack.push(i);if(m.repeatEnd){const start=stack.length?stack.pop():0;pairs.push({start,end:i,count:m.repeatEnd});}});
    stack.forEach(i=>warnings.push({kind:'repeat',mi:i,text:`第 ${i+1} 小节的反复起点缺少反复终点`}));
    const byEnd=new Map(pairs.map(p=>[p.end,p])),pass=new Map(),route=[];
    const segno=s.measures.findIndex(m=>m.navigation==='segno'),coda=s.measures.findIndex(m=>m.navigation==='coda');
    s.measures.forEach((m,mi)=>{const nav=m.navigation||'';if(nav.startsWith('ds-')&&segno<0)warnings.push({kind:'navigation',mi,text:`第 ${mi+1} 小节的 D.S. 缺少 Segno（𝄋）`});if(nav.endsWith('-fine')&&!s.measures.some(x=>x.navigation==='fine'))warnings.push({kind:'navigation',mi,text:`第 ${mi+1} 小节的返回记号缺少 Fine 终止点`});if(nav.endsWith('-coda')&&(coda<0||!s.measures.some(x=>x.navigation==='to-coda')))warnings.push({kind:'navigation',mi,text:`第 ${mi+1} 小节的返回记号需要 To Coda 和 Coda（𝄌）`});});
    let i=0,steps=0,lingering=1,jumped=false,jumpMode='',codaTaken=false;
    while(i<s.measures.length&&steps++<5000){const m=s.measures[i],containing=pairs.filter(p=>i>=p.start&&i<=p.end).sort((a,b)=>(a.end-a.start)-(b.end-b.start))[0];
      const iteration=containing?(jumped?containing.count:pass.get(containing.end)||1):lingering,ends=endingNumbers(m),include=!ends.length||ends.includes(iteration);
      if(include)route.push({mi:i,pass:iteration});
      if(include&&jumped&&jumpMode==='fine'&&m.navigation==='fine')break;
      if(include&&jumped&&jumpMode==='coda'&&m.navigation==='to-coda'&&!codaTaken&&coda>=0){codaTaken=true;i=coda;continue;}
      const p=byEnd.get(i);if(p&&!jumped){const current=pass.get(i)||1;if(current<p.count){pass.set(i,current+1);pairs.filter(x=>x.start>=p.start&&x.end<p.end).forEach(x=>pass.delete(x.end));i=p.start;continue;}lingering=current;}
      if(include&&!jumped&&/^(dc|ds)-(fine|coda)$/.test(m.navigation)){const [where,mode]=m.navigation.split('-'),target=where==='dc'?0:segno;if(target>=0){jumped=true;jumpMode=mode;i=target;continue;}}
      if(!ends.length&&!p&&!containing)lingering=1;i++;
    }
    if(steps>=5000)warnings.push({kind:'repeat',mi:0,text:'反复组合展开超过 5000 小节，请减少反复次数。'});return {route,warnings};
  }
  function timeline(s){const rr=playbackRoute(s),source=resolved(s),out=[],byMeasure=new Map();source.forEach(n=>{if(!byMeasure.has(n.mi))byMeasure.set(n.mi,[]);byMeasure.get(n.mi).push(n);});
    let cursor=0;const volume={pppp:.12,ppp:.18,pp:.27,p:.38,mp:.5,mf:.64,f:.78,ff:.9,fff:1,ffff:1,sf:.9,sfz:.95,fp:.75,rfz:.95},dynamics={};
    rr.route.forEach((visit,occurrence)=>{const src=byMeasure.get(visit.mi)||[],m=s.measures[visit.mi],bpm=settings(s,visit.mi).bpm,length=Math.max(capacity(s,visit.mi),...voices(s).map(v=>events(s,m,v.id).reduce((a,e)=>a+ticks(e),0)));
      if(m.dynamic)voices(s).forEach(v=>dynamics[v.id]=m.dynamic);
      const holds=new Map();src.filter(n=>n.articulation==='fermata').forEach(n=>{const at=n.beat+ticks(n.e);holds.set(at,Math.max(holds.get(at)||0,ticks(n.e)*.5));});
      const mapBeat=b=>b+[...holds].reduce((a,[at,extra])=>a+(at<=b+EPS?extra:0),0);
      src.forEach(n=>{if(n.e.dynamic)dynamics[n.voice]=n.e.dynamic;const start=cursor+mapBeat(n.beat)/48*60/bpm,end=cursor+mapBeat(n.beat+ticks(n.e))/48*60/bpm;out.push({...n,occurrence,pass:visit.pass,start,seconds:end-start,volume:volume[dynamics[n.voice]||'mf']});});cursor+=mapBeat(length)/48*60/bpm;
    });
    voices(s).forEach(v=>{const part=out.filter(n=>n.voice===v.id);part.forEach((n,i)=>{const next=part[i+1];n.validTie=!!n.e.tie&&n.midi!==null&&next?.midi===n.midi&&next.sequence===n.sequence+1&&close(n.start+n.seconds,next.start);n.next=next||null;n.continuation=i>0&&part[i-1].validTie;});});
    out.sort((a,b)=>a.start-b.start||voices(s).findIndex(v=>v.id===a.voice)-voices(s).findIndex(v=>v.id===b.voice));return {notes:out,seconds:source.length?cursor:0,route:rr.route,warnings:rr.warnings};
  }
  function stats(s){const notes=resolved(s).filter(n=>n.midi!==null),sorted=[...notes].sort((a,b)=>a.midi-b.midi);return {count:notes.length,highest:sorted.at(-1)?.name||'—',lowest:sorted[0]?.name||'—',seconds:timeline(s).seconds,highestId:sorted.at(-1)?.e.id,lowestId:sorted[0]?.e.id};}
  function validate(s){const issues=[],r=resolved(s);
    voices(s).forEach(v=>{s.measures.forEach((m,mi)=>{const cap=capacity(s,mi),total=events(s,m,v.id).reduce((a,e)=>a+ticks(e),0);if(!close(total,cap))issues.push({kind:'meter',mi,voice:v.id,text:`${v.name} · 第 ${mi+1} 小节${total>cap?'超出':'不足'} ${fmt(Math.abs(total-cap)/48)} 拍（${fmt(total/48)} / ${fmt(cap/48)}）`});});
      const part=r.filter(n=>n.voice===v.id);part.forEach((n,i)=>{if(n.redundant)issues.push({kind:'accidental',mi:n.mi,voice:v.id,id:n.e.id,text:`${v.name} · 第 ${n.mi+1} 小节 ${n.name} 的升降号重复`});if(n.e.tie&&(n.midi===null||part[i+1]?.midi!==n.midi))issues.push({kind:'tie',mi:n.mi,voice:v.id,id:n.e.id,text:`${v.name} · 第 ${n.mi+1} 小节的延音线需连接同音高音符`});});
    });
    const groups=new Map();r.filter(n=>n.e.tuplet).forEach(n=>{const k=n.voice+':'+n.e.tuplet.id;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(n);});groups.forEach(g=>{const t=g[0].e.tuplet,indices=new Set(g.map(n=>n.e.tuplet.index)),total=g.reduce((a,n)=>a+ticks(n.e),0);if(indices.size!==t.count||!close(total,t.total*48)||g.some(n=>n.e.tuplet.count!==t.count||n.e.tuplet.total!==t.total))issues.push({kind:'tuplet',mi:g[0].mi,voice:g[0].voice,id:g[0].e.id,text:`${g[0].voiceName} · ${t.count} 连音组不完整（已有 ${indices.size} / ${t.count}，总 ${fmt(total/48)} / ${t.total} 拍）`});});
    const slurs=new Map();r.filter(n=>n.e.slur).forEach(n=>{if(!slurs.has(n.e.slur))slurs.set(n.e.slur,[]);slurs.get(n.e.slur).push(n);});slurs.forEach(g=>{if(g.length<2||new Set(g.map(n=>n.voice)).size>1||g.some(n=>n.e.type==='rest'))issues.push({kind:'slur',mi:g[0].mi,voice:g[0].voice,id:g[0].e.id,text:'圆滑线应连接同一声部的至少两个音符'});});return [...issues,...playbackRoute(s).warnings];
  }
  function notationFor(n,total){const target=total*48/Math.pow(2,Math.floor(Math.log2(n)));let best=null;[1,2,4,8,16,32,64,128].forEach(duration=>{for(let dots=0;dots<=3;dots++){const error=Math.abs(Math.log(192/duration*dotFactor(dots)/target));if(!best||error<best.error)best={duration,dots,error};}});return {duration:best.duration,dots:best.dots};}
  function setTuplet(list,count,total){if(list.length!==count)throw new Error(`需要 ${count} 个连续音符或休止符。`);const gid=id(),notation=notationFor(count,total);list.forEach((e,index)=>Object.assign(e,notation,{dotted:false,triplet:false,exactTicks:null,tuplet:{id:gid,count,total,index}}));}
  function fragment(t){const pool=[];[1,2,4,8,16,32,64,128].forEach(duration=>{for(let dots=0;dots<=3;dots++)pool.push({duration,dots,t:192/duration*dotFactor(dots)});});const exact=pool.find(p=>close(p.t,t));if(exact)return {...exact,exactTicks:null};const near=pool.sort((a,b)=>Math.abs(Math.log(a.t/t))-Math.abs(Math.log(b.t/t)))[0];return {...near,exactTicks:t};}
  function restPieces(t,voice){const out=[],pool=[];[1,2,4,8,16,32,64,128].forEach(duration=>{for(let dots=0;dots<=3;dots++)pool.push({duration,dots,t:192/duration*dotFactor(dots)});});pool.sort((a,b)=>b.t-a.t);let left=t;while(left>EPS){const p=pool.find(p=>p.t<=left+EPS);if(!p){out.push(event(30,{type:'rest',voice,...fragment(left)}));break;}out.push(event(30,{type:'rest',voice,duration:p.duration,dots:p.dots}));left-=p.t;}return out;}
  function repair(s,kind='all',targetId=null){const out=JSON.parse(JSON.stringify(s));if(!out.voices)out.voices=voices(out);
    if(kind==='all'||kind==='accidental')resolved(out).forEach(n=>{if(n.redundant&&(!targetId||n.e.id===targetId))n.e.accidental=null;});
    if(kind==='all'||kind==='tie')voices(out).forEach(v=>{const part=resolved(out).filter(n=>n.voice===v.id);part.forEach((n,i)=>{if(n.e.tie&&part[i+1]?.midi!==n.midi&&(!targetId||n.e.id===targetId))n.e.tie=false;});});
    if(kind==='all'||kind==='tuplet'){validate(out).filter(i=>i.kind==='tuplet'&&(!targetId||i.id===targetId)).forEach(issue=>{const e=out.measures.flatMap(m=>m.events).find(e=>e.id===issue.id),t=e?.tuplet;if(!t)return;const group=out.measures.flatMap(m=>m.events).filter(e=>voiceId(out,e)===issue.voice&&e.tuplet?.id===t.id),present=new Set(group.map(e=>e.tuplet.index)),last=group.at(-1);Array.from({length:t.count},(_,i)=>i).filter(i=>!present.has(i)).forEach(index=>{const next=group.find(e=>e.tuplet.index>index),anchor=next||last,m=out.measures.find(m=>m.events.includes(anchor)),at=m.events.indexOf(anchor)+(next?0:1),rest=event(last.pitch,{type:'rest',voice:issue.voice,duration:last.duration,dots:last.dots,tuplet:{...t,index}});m.events.splice(at,0,rest);group.push(rest);group.sort((a,b)=>a.tuplet.index-b.tuplet.index);});});}
    if(kind==='all'||kind==='slur')validate(out).filter(i=>i.kind==='slur'&&(!targetId||i.id===targetId)).forEach(i=>{const group=out.measures.flatMap(m=>m.events).find(e=>e.id===i.id)?.slur;out.measures.flatMap(m=>m.events).filter(e=>e.slur===group).forEach(e=>e.slur='');});
    if(kind==='all'||kind==='meter'){const acc=new Map(resolved(out).map(n=>[n.e.id,n.acc])),measures=[];
      out.measures.forEach((original,mi)=>{const cap=capacity(out,mi),partsByVoice=new Map();let size=1;voices(out).forEach(v=>{const parts=[[]];let used=0;
        events(out,original,v.id).forEach(e=>{let left=ticks(e),first=true;while(left>EPS){if(close(used,cap)){parts.push([]);used=0;}const take=Math.min(left,cap-used),split=!close(take,ticks(e)),notation=split?fragment(take):{duration:e.duration,dots:dots(e),exactTicks:e.exactTicks};parts.at(-1).push({...e,...notation,id:first?e.id:id(),voice:v.id,dotted:false,triplet:split?false:e.triplet,lyric:first?e.lyric:'',dynamic:first?e.dynamic:'',expression:first?e.expression:'',accidental:e.type==='rest'?null:acc.get(e.id),tie:e.type==='note'&&(left>take+EPS||e.tie),exactTicks:e.tuplet&&split?take:notation.exactTicks});first=false;left-=take;used+=take;}});partsByVoice.set(v.id,parts);size=Math.max(size,parts.length);});
        for(let pi=0;pi<size;pi++){const m=measure({...original,id:pi===0?original.id:id(),events:[],repeatStart:pi===0&&original.repeatStart,repeatEnd:pi===size-1?original.repeatEnd:0,navigation:pi===size-1?original.navigation:''});voices(out).forEach(v=>{const list=partsByVoice.get(v.id)[pi]||[];m.events.push(...list);const used=list.reduce((a,e)=>a+ticks(e),0);if(used<cap-EPS)m.events.push(...restPieces(cap-used,v.id));});measures.push(m);}
      });if(measures.length>300)throw new Error('修正后超过 300 小节，请减少内容或调整拍号。');out.measures=measures;resolved(out).forEach(n=>{if(n.redundant)n.e.accidental=null;});
    }
    if(kind==='all'||kind==='repeat'||kind==='navigation')playbackRoute(out).warnings.forEach(i=>{if(i.kind==='navigation')out.measures[i.mi].navigation='';else if(out.measures[i.mi].repeatStart)out.measures[i.mi].repeatStart=false;});return out;
  }
  function sanitize(raw){if(!raw||![1,2,3].includes(raw.version)||!Array.isArray(raw.measures)||raw.measures.length<1||raw.measures.length>300)throw new Error('乐谱文件无效（最多 300 小节）。');
    const s=blank();s.title=String(raw.title||'未命名作品').slice(0,80);s.key=Math.max(-7,Math.min(7,Math.round(Number(raw.key)||0)));s.mode=raw.mode==='minor'?'minor':'major';s.bpm=Math.max(30,Math.min(240,Number(raw.bpm)||96));if(!Array.isArray(raw.meter)||![2,4,8,16].includes(raw.meter[1])||!Number.isInteger(raw.meter[0])||raw.meter[0]<1||raw.meter[0]>12)throw new Error('拍号无效。');s.meter=raw.meter;
    const vc=['treble','bass','treble8vb','treble8va'],rawVoices=raw.version===1?[{id:'v1',name:'旋律',clef:raw.clef}]:raw.voices;if(!Array.isArray(rawVoices)||!rawVoices.length||rawVoices.length>16)throw new Error('声部数量应为 1–16。');
    const ids=new Set();s.voices=rawVoices.map((v,i)=>{const vid=String(v.id||'v'+(i+1)).slice(0,40);if(!/^[a-zA-Z0-9_-]+$/.test(vid)||ids.has(vid))throw new Error('声部标识无效。');ids.add(vid);return {id:vid,name:String(v.name||`声部 ${i+1}`).slice(0,24),clef:vc.includes(v.clef)?v.clef:'treble',muted:!!v.muted};});s.clef=s.voices[0].clef;
    const dynamicValues=['pppp','ppp','pp','p','mp','mf','f','ff','fff','ffff','sf','sfz','fp','rfz'],artValues=['staccato','staccatissimo','accent','marcato','tenuto','fermata','breath','legato','portato','pizzicato','arco'],expressValues=EXPRESSIONS.map(x=>x[0]);
    let count=0;const seen=new Set();s.measures=raw.measures.map(m=>{if(!Array.isArray(m.events)||m.events.length>2048)throw new Error('单小节音符过多。');const end=Number(m.repeatEnd)||0;if(![0,2,3,4,5,6,7,8].includes(end))throw new Error('反复次数无效。');const ending=String(m.ending||'');if(ending&&!/^[1-8](,[1-8])*$/.test(ending))throw new Error('房子编号无效。');const clefs={},octaves={};s.voices.forEach(v=>{if(vc.includes(m.clefs?.[v.id]))clefs[v.id]=m.clefs[v.id];});s.voices.forEach(v=>{if([-2,-1,1,2].includes(m.octaves?.[v.id]))octaves[v.id]=m.octaves[v.id];});let meter=null;if(m.meter){if(!Array.isArray(m.meter)||![2,4,8,16].includes(m.meter[1])||!Number.isInteger(m.meter[0])||m.meter[0]<1||m.meter[0]>12)throw new Error('小节拍号无效。');meter=[...m.meter];}return measure({key:m.key===null||m.key===undefined?null:Math.max(-7,Math.min(7,Math.round(Number(m.key)||0))),mode:['major','minor'].includes(m.mode)?m.mode:null,meter,bpm:m.bpm===null||m.bpm===undefined?null:Math.max(30,Math.min(240,Number(m.bpm)||96)),clefs,octaves,dynamic:dynamicValues.includes(m.dynamic)?m.dynamic:'',expression:expressValues.includes(m.expression)?m.expression:'',articulation:artValues.includes(m.articulation)?m.articulation:'',ornament:['trill','mordent','turn'].includes(m.ornament)?m.ornament:'',repeatStart:!!m.repeatStart,repeatEnd:end,ending,navigation:['segno','coda','to-coda','fine','dc-fine','ds-fine','dc-coda','ds-coda'].includes(m.navigation)?m.navigation:'',events:m.events.map(e=>{
      if(++count>16000||![1,2,4,8,16,32,64,128].includes(e.duration)||!Number.isInteger(e.pitch)||e.pitch<0||e.pitch>66)throw new Error('音符数据无效。');const voice=raw.version===1?s.voices[0].id:e.voice;if(!ids.has(voice))throw new Error('音符的声部不存在。');const numDots=raw.version===1?(e.dotted?1:0):Number(e.dots)||0;if(![0,1,2,3].includes(numDots))throw new Error('附点数量无效。');
      const eid=typeof e.id==='string'&&/^[a-zA-Z0-9_-]{1,40}$/.test(e.id)&&!seen.has(e.id)?e.id:id();seen.add(eid);let tuplet=null;if(e.tuplet){const t=e.tuplet;if(!/^[a-zA-Z0-9_-]{1,40}$/.test(t.id)||!Number.isInteger(t.count)||t.count<2||t.count>32||!Number.isFinite(t.total)||t.total<.125||t.total>32||!Number.isInteger(t.index)||t.index<0||t.index>=t.count)throw new Error('连音组数据无效。');tuplet={id:t.id,count:t.count,total:t.total,index:t.index};}
      const exact=e.exactTicks??null;if(exact!==null&&(!Number.isFinite(exact)||exact<=0||exact>3072))throw new Error('精确时值无效。');const n=event(e.pitch,{id:eid,voice,type:e.type==='rest'?'rest':'note',placeholder:!!e.placeholder,entryAnchor:!!e.entryAnchor,positionRatio:Number.isFinite(e.positionRatio)?Math.max(0,Math.min(1,e.positionRatio)):null,duration:e.duration,dots:numDots,triplet:!!e.triplet,tuplet,exactTicks:exact,ottava:[-2,-1,0,1,2].includes(e.ottava)?e.ottava:0,slur:typeof e.slur==='string'&&/^[a-zA-Z0-9_-]{1,40}$/.test(e.slur)?e.slur:'',ornament:['trill','mordent','turn'].includes(e.ornament)?e.ornament:'',accidental:[-2,-1,0,1,2].includes(e.accidental)?e.accidental:null,lyric:String(e.lyric||'').slice(0,80),dynamic:dynamicValues.includes(e.dynamic)?e.dynamic:'',expression:expressValues.includes(e.expression)?e.expression:'',articulation:artValues.includes(e.articulation)?e.articulation:'',tie:!!e.tie});if(!Number.isFinite(ticks(n)))throw new Error('音符时值无效。');return n;
    })});});return s;
  }
  return {LETTERS,SHARPS,FLATS,MAJOR,MINOR,ACC,EXPRESSIONS,id,EPS,close,fmt,voices,voiceId,events,blank,measure,event,settings,dots,dotFactor,ticks,capacity,keyMap,letter,naturalMidi,pitchName,clefShift,resolved,playbackRoute,timeline,stats,validate,notationFor,setTuplet,fragment,restPieces,repair,sanitize};
});

