'use strict';
let notebook=null,staffLastInputId=null,staffLastInputToneIndex=0,recentInputs=[];
function documentDefaults(){return {duration:4,dots:0,exactTicks:null,triplet:false,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false};}
function makeDocument(type,value=null){const content=value||M.blank();content.notation=type;return {id:M.id(),score:content,undo:[],redo:[],ui:{}};}
function initializeNotebook(){
  try{const raw=JSON.parse(localStorage.getItem('puji-notebook-v1')||'null');if(raw?.version===1&&Array.isArray(raw.documents)&&raw.documents.length){const documents=raw.documents.map(d=>({id:typeof d.id==='string'?d.id:M.id(),score:M.sanitize(d.score),undo:[],redo:[],ui:d.ui||{}}));notebook={version:1,activeId:raw.activeId,preferred:raw.preferred||{},documents};if(!documents.some(d=>d.id===notebook.activeId))notebook.activeId=documents[0].id;score=documents.find(d=>d.id===notebook.activeId).score;}}
  catch{setTimeout(()=>toast('多谱子保存读取失败，已保留上一份乐谱。请导出备份。'),500);}
  if(!notebook){const d=makeDocument(score.notation||'staff',score);notebook={version:1,activeId:d.id,preferred:{[d.score.notation]:d.id},documents:[d]};}
}
function currentDocument(){return notebook?.documents.find(d=>d.id===notebook.activeId);}
function stashDocument(){const d=currentDocument();if(!d)return;d.score=score;d.undo=undoStack;d.redo=redoStack;d.ui={activeVoice,currentMeasure,mode,defaults:{...defaults},jianpuCursor,jianpuOctave,jianpuRhythmOverride,revealedVoice,staffLastInputId,staffLastInputToneIndex,recentInputs,playbackRange,hideEmptyRows};}
function saveNotebook(){stashDocument();localStorage.setItem('puji-notebook-v1',JSON.stringify({version:1,activeId:notebook.activeId,preferred:notebook.preferred,documents:notebook.documents.map(d=>({id:d.id,score:d.score,ui:d.ui}))}));}
function activateDocument(id){
  const d=notebook.documents.find(d=>d.id===id);if(!d)return;cancelAltMeasure();stop();cancelGesture();closeScoreSetting();closeHelpMenu();closeScoreList();stashDocument();notebook.activeId=d.id;score=d.score;notation=score.notation||'staff';notebook.preferred[notation]=d.id;
  const ui=d.ui||{};activeVoice=score.voices.some(v=>v.id===ui.activeVoice)?ui.activeVoice:score.voices[0].id;currentMeasure=Math.max(0,Math.min(score.measures.length-1,ui.currentMeasure||0));mode=notation==='jianpu'?'select':ui.mode||'edit';defaults={...documentDefaults(),...ui.defaults};jianpuCursor=ui.jianpuCursor||null;jianpuOctave=ui.jianpuOctave||0;jianpuRhythmOverride=!!ui.jianpuRhythmOverride;revealedVoice=ui.revealedVoice||null;staffLastInputId=ui.staffLastInputId||null;staffLastInputToneIndex=ui.staffLastInputToneIndex||0;recentInputs=Array.isArray(ui.recentInputs)?ui.recentInputs:[];playbackRange=ui.playbackRange||{start:null,end:null};playbackMarkerTool=null;playbackRangeDraft=null;hideEmptyRows=!!ui.hideEmptyRows;undoStack=d.undo||[];redoStack=d.redo||[];symbolTool=null;symbolStart=null;jianpuChordTarget=null;clearSelection();render();save();$('score').focus({preventScroll:true});
}
function switchEditor(next){if(next===notation)return;finishMeasure();let d=notebook.documents.find(d=>d.id===notebook.preferred[next]&&d.score.notation===next)||notebook.documents.find(d=>d.score.notation===next);if(!d){d=makeDocument(next);notebook.documents.push(d);}activateDocument(d.id);}
function openNewScore(value=null){const d=makeDocument(value?.notation||notation,value);notebook.documents.push(d);activateDocument(d.id);}
function pristineDocument(d){const s=d?.score;return s&&s.title==='未命名作品'&&s.voices.length===1&&s.measures.length===1&&s.key===0&&s.mode==='major'&&s.bpm===96&&s.meter.join('/')==='4/4'&&s.voices[0].clef==='treble'&&s.voices[0].name==='声部 1'&&!s.voices[0].muted&&s.measures[0].events.length===0&&JSON.stringify({...s.measures[0],id:''})===JSON.stringify({...M.measure(),id:''});}
function scoreSignature(s){
  // Compare musical content, not generated identifiers, document titles or input layout.
  const resolved=new Map(M.resolved(s).map(n=>[n.e.id,n])),locations=new Map(),groups=new Map();
  s.measures.forEach((m,mi)=>s.voices.forEach((v,vi)=>M.events(s,m,v.id).forEach((e,ei)=>locations.set(e.id,[mi,vi,ei]))));
  const ref=id=>id?(locations.get(id)||['missing',id]):null,group=(kind,id)=>{if(!id)return null;const key=kind+':'+id;if(!groups.has(key))groups.set(key,groups.size);return groups.get(key);},ticks=e=>Number(M.ticks(e).toFixed(6));
  return JSON.stringify({notation:s.notation,voices:s.voices.map(v=>({name:v.name,muted:!!v.muted})),measures:s.measures.map((m,mi)=>({
    dynamic:m.dynamic||'',expression:m.expression||'',articulation:m.articulation||'',ornament:m.ornament||'',repeatStart:!!m.repeatStart,repeatEnd:m.repeatEnd||0,ending:m.ending||'',navigation:m.navigation||'',
    voices:s.voices.map(v=>{const c=M.settings(s,mi,v.id);return {key:c.key,mode:c.mode,meter:c.meter,bpm:c.bpm,clef:s.notation==='staff'?c.clef:null,hairpin:m.hairpins?.[v.id]?.kind||'',events:M.events(s,m,v.id).map(e=>{
      const n=resolved.get(e.id),tones=e.type==='rest'?[]:n.tones.map((t,i)=>[t.pitch+n.shift*7,t.acc,!!e.chord?.[i-1]?.singerLayer,Number(M.ticks(t.rhythm).toFixed(6))]);
      return {type:e.type,ticks:ticks(e),tones,graces:(n.graces||[]).map(g=>[g.pitch+n.shift*7,g.acc,g.duration,!!g.slash]),lyric:e.lyric||'',dynamic:e.dynamic||'',expression:e.expression||'',articulation:e.articulation||'',ornament:e.ornament||'',tie:!!e.tie,slur:group('slur',e.slur),beam:group('beam',e.beamGroup),beamBreak:!!e.beamBreak,
        tuplet:e.tuplet?{group:group('tuplet',e.tuplet.id),count:e.tuplet.count,total:e.tuplet.total}:null,arpeggio:e.arpeggio||'',arpeggioGroup:group('arpeggio',e.arpeggioGroup),glissando:e.glissando||'',glissTo:ref(e.glissTo),hairpin:e.hairpin||'',hairpinTo:ref(e.hairpinTo),pedal:!!e.pedal,pedalTo:ref(e.pedalTo)};
    })};})
  }))});
}
function openConvertedScore(content){
  stashDocument();const signature=scoreSignature(content),targets=notebook.documents.filter(d=>d.score.notation===content.notation),existing=targets.find(d=>d.id===notebook.preferred[content.notation]),matching=[existing,...targets.filter(d=>d!==existing)].find(d=>d&&scoreSignature(d.score)===signature);
  if(matching){activateDocument(matching.id);return;}if(pristineDocument(existing)){existing.score=content;existing.ui={};existing.undo=[];existing.redo=[];activateDocument(existing.id);}else openNewScore(content);
}
function pageScore(direction){const documents=notebook.documents.filter(d=>d.score.notation===notation);if(documents.length<2)return;const at=documents.findIndex(d=>d.id===notebook.activeId),next=documents[(at+direction+documents.length)%documents.length];activateDocument(next.id);}
function syncScoreList(){const d=currentDocument();if(d)d.score=score;const items=notebook.documents.filter(d=>d.score.notation===notation);$('chooseScore').textContent='谱子 '+(items.findIndex(d=>d.id===notebook.activeId)+1)+' / '+items.length+' ▾';$('scoreList').innerHTML=items.map((d,i)=>'<div class="score-list-row" role="none"><button class="score-list-select" role="menuitemradio" aria-checked="'+(d.id===notebook.activeId)+'" data-document="'+escapeXml(d.id)+'">'+(i+1)+'. '+escapeXml(d.score.title)+(d.id===notebook.activeId?' ✓':'')+'</button><button class="score-list-delete" role="menuitem" data-delete-document="'+escapeXml(d.id)+'" aria-label="删除谱子：'+escapeXml(d.score.title)+'" title="删除谱子"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></svg></button></div>').join('');}
function requestDeleteDocument(id){const d=notebook.documents.find(d=>d.id===id);if(!d)return;closeScoreList();$('chooseScore').focus({preventScroll:true});confirmAction('确认删除谱子？','是否确认删除《'+d.score.title+'》？',()=>deleteDocument(id),'确认删除');}
function deleteDocument(id){
  const removed=notebook.documents.find(d=>d.id===id);if(!removed)return;stashDocument();const type=removed.score.notation,wasActive=notebook.activeId===id,sameType=notebook.documents.filter(d=>d.score.notation===type),at=sameType.findIndex(d=>d.id===id);
  notebook.documents=notebook.documents.filter(d=>d.id!==id);const remaining=notebook.documents.filter(d=>d.score.notation===type);let next=remaining[Math.min(at,remaining.length-1)];
  if(wasActive&&!next){next=makeDocument(type);notebook.documents.push(next);}if(notebook.preferred[type]===id){if(next)notebook.preferred[type]=next.id;else delete notebook.preferred[type];}
  if(wasActive)activateDocument(next.id);else{syncScoreList();save();$('chooseScore').focus({preventScroll:true});}
}
function closeScoreList(){$('scoreList').hidden=true;$('chooseScore').setAttribute?.('aria-expanded','false');}
function toggleScoreList(){const list=$('scoreList');if(!list.hidden){closeScoreList();return;}closeHelpMenu();hideMenu();syncScoreList();list.hidden=false;$('chooseScore').setAttribute('aria-expanded','true');}
function changeToneTicks(e,indices,change){M.setToneRhythm(e,indices,r=>{const t=change(M.ticks(r));if(!Number.isFinite(t)||t<=M.EPS||t>3072)throw Error('时值超出支持范围。');return {...M.fragment(t),triplet:false,tuplet:null};});}
function useToneDefaults(e,index=0){const r=e.stepRhythm||M.toneRhythm(e,index);defaults.duration=r.duration;defaults.dots=r.dots;defaults.exactTicks=r.exactTicks??null;if(notation==='jianpu')jianpuRhythmOverride=false;}
function changeJianpuBeat(amount,reset=false){const selectedEvents=selectedList(),recent=selectedEvents.length?null:refreshRecentNote(),list=selectedEvents.length?selectedEvents:[recent].filter(Boolean);if(!list.length){toast('请先输入或选择音符。');return;}hideMenu();commit(()=>{detachJianpuTuplets(list);list.forEach(e=>changeToneTicks(e,selectedEvents.length?selectedIndices(e):new Set([staffLastInputToneIndex]),t=>reset?48:t+amount*48));const last=list.at(-1);useToneDefaults(last,selectedEvents.length?[...selectedIndices(last)].at(-1):staffLastInputToneIndex);},false);$('score').focus({preventScroll:true});}
function moveRecentPitch(dir){const e=refreshRecentNote();if(!e){toast('请先键入一个音符。');return;}if(e.type==='rest'){toast('休止符没有音高。');return;}const index=Math.min(staffLastInputToneIndex,M.tones(e).length-1);commit(()=>shiftEventPitch(e,dir,new Set([index])));$('score').focus({preventScroll:true});}
function scaleRecentDuration(factor){const e=refreshRecentNote();if(!e){toast('请先键入一个音符。');return;}const index=staffLastInputToneIndex;commit(()=>{detachJianpuTuplets([e]);changeToneTicks(e,new Set([index]),t=>t*factor);useToneDefaults(e,index);});$('score').focus({preventScroll:true});}
function updateSymbolHint(){const hint=$('symbolStatus');hint.hidden=!symbolTool&&!playbackMarkerTool;if(playbackMarkerTool){hint.textContent=playbackMarkerTool==='start'?'设置播放起点：点击音符或小节空白处':'设置播放终点：点击音符（包含该音符）或小节空白处';return;}if(!symbolTool)return;hint.textContent=symbolStart?'已选择起点，请选择终点':'点击谱面放置 '+symbolTool.label+(rangeSymbolKinds.includes(symbolTool.kind)?'，请选择起点':'');}
const HELP_TOPICS=[
 ['谱子与编辑器',['Shift+Tab 或谱式按钮只切换编辑器。五线谱、简谱各自保存，首次切换到另一个编辑器时打开空白谱子。','“一键转…”才进行转换。原谱保留；目标编辑器中已有内容相同的谱子时直接打开该谱子，不新增副本；没有相同谱子时才另建转换谱。简谱不支持的器乐符号会在转换前列出位置，继续后仅从转换副本中删除。','谱面右上角“谱子”按钮选择当前编辑器的谱子；PgUp／PgDn 切换。每份谱子的撤销与重做独立。新建和打开文件均新增谱子，保留已有进度。列表右侧垃圾桶删除相应谱子，确认后才删除；取消会保留内容。']],
 ['五线谱录入',['Tab 切换编辑与选择。编辑模式在空白谱位单击添加音符；再次点击音符头变为同样时值的休止符，再次点击休止符还原原来的音符或和弦；右键点击音符或休止符删除（和弦只删除所点单音）。点击同一时点的其他谱位添加和弦。','编辑模式 ←／→ 将刚输入的音符时值减半／加倍，并作为后续输入的默认时值。↑／↓ 无需选择即可将最近输入的一个音符上移／下移一个谱位，和弦只移动最近添加的那个音。空格输入一个四分音符中央 C。按 . 给最近输入的音符增加一个附点，可连续添加且不设数量上限；此操作不改变下一音符的默认时值。无选择的单音快捷键按录入顺序定位最近还存在的音符，删除、重排与符号编辑不会改变录入顺序。','悬停显示音高与落点；输入音符时不自动出现菜单。倚音工具开启后点击主音左侧谱位添加；编辑模式点击倚音或奏法符号删除。']],
 ['简谱录入与时值',['数字 1–7 连续录入音级，0 录入休止符，无需确认；默认沿用前一音符的时值，填满小节后继续到下一小节。','Enter 将上一音符延长一个四分拍，单选时延长所选音符；Shift+Enter 缩短一拍，剩余时值须大于零。空格把所选音符重置为一拍；未选择时把最近输入的音符或休止符重置为一拍。','Ctrl 多选或框选相邻同音音符，Enter 合并并精确相加时值。不同声部、音高、八度或不相邻会提示；叠放分组需选完整组。','点击已有数字再输入音级，在该时点上下叠放，可表示同声部分组演唱。点击空白处继续录入旋律。↑／↓ 改变所选音符八度；无选择时改变后续输入八度。←／→ 将所选音符时值减半／加倍；无选择时直接修改最近键入的音符或休止符，后续输入沿用修改后的时值。','数字下方每条横线减半时值；右侧延长横线每条增加一拍；长休止使用多个 0。数字上、下的点表示高、低八度，调号用 1=… 表示。']],
 ['选择、修改与撤销',['选择模式单击音符、小节空白或符号选择，再次点击取消。和弦单击选择其中一个音，双击选择整个和弦；选中单音后用 ←／→ 或“时值”菜单独立修改时值与附点，其他和弦音保持原样。双击全选后可一起调整。在八分音符上叠加全音符时，八分音符仍与后续音符正常连梁；编辑模式用 → 调整刚添加的叠加音，其时值不会改变之后继续录入旋律的默认时值。和弦各音在独立音轨上同时开始，修改单音时值只改变该音的持续时间，其他音及后续音符仍按原有起点播放；长音可以跨过后续音符和小节继续保持。完整和弦一起调整时，才一起改变该时点的节奏。Ctrl 点击多选；拖动框选，Ctrl 拖动追加。按住鼠标拖到窗口边缘后自动向该方向滚动，越靠近边缘速度越快；谱面横向溢出时也支持左右滚动。鼠标移回中间、松开、Esc 或离开窗口后停止。','五线谱编辑模式开始框选后自动转为选择模式。选择模式 ↑／↓ 移动一个谱位，←／→ 时值减半／加倍。A／D 与前一个／后一个音符交换位置；和弦单音移到相邻和弦。拖动所选音符调整位置和音高，从空白处拖动仍可框选。Ctrl+C／Ctrl+V 复制粘贴选中的音符、和弦单音、小节或符号；音符粘贴在所选音符之后，小节粘贴到当前小节，支持撤销。Delete 删除所选对象。Backspace 有选择时保留选中删除；无选择时按录入顺序删除最近的音符、和弦单音、休止符、倚音、附点、力度、表情、歌词或符号，跨音符符号作为一个整体删除；支持撤销。','选中对象后悬停约半秒出现分类菜单，悬停或点击分类展开细项；离开后收起。Ctrl+Z 撤销，Ctrl+Y 或 Ctrl+Shift+Z 重做。','复制粘贴保留音符顺序、实际音高、各音时值、歌词和演奏符号。跨调号、谱号或八度时会补足必要的音高信息。粘贴整小节时替换目标小节对应声部的内容，保留其他声部的音符，并应用源小节的调号、拍号和速度；可撤销恢复。']],
 ['调号、拍号与声部',['直接点击谱面左上角的调号、拍号与速度修改。速度可输入任意正数（含小数），无预设上下限；速度输入框支持滚轮增减，保留原来的方向键和数字输入，应用时仍选择作用小节范围。五线谱另外支持点击谱号和调式；简谱不显示这两个选项。','修改设置后选择“当前小节”或“之后所有小节（含当前）”。多选时“当前”应用到所选小节，“之后”从最早所选小节开始。','“＋ 声部”新增独立谱表，可命名为乐器或声部，支持静音与只播放当前声部。各声部独立录入，默认显示所有声部；勾选“隐藏空白行”后才隐藏未录入内容的行，关闭后恢复。删除声部后默认名称按顺序重新编号，手动名称保留。']],
 ['连线与范围符号',['“⌒ 连线”自动判断：连续同音连接为延音线，不同音高连接为圆滑线。详细菜单仍可分别修改或移除这两种线。','八度线、连线、渐强渐弱、滑音与踏板每次点按钮后都重新选择起点，不沿用已有选择；依次点起点、终点，或从起点拖到终点。谱面内显示起点／终点提示，完成即退出添加。Esc 中途取消。','琶音应用到和弦，可上行、下行或连接同时点的多个谱表；渐强渐弱线与 cresc.、dim. 独立添加。简谱反复起点、终点在每行使用固定基线对齐。']],
 ['力度、表情与歌词',['选中音符或小节并悬停后打开“力度”“表情”“奏法”等分类；标记只添加到所选对象。播放初始力度为 mp，普通力度按声部延续直到出现新标注，不自动给后续音符添加标记。','渐强／渐弱无终点标注时移动两个等级（如 p→mf、f→mp），结束后保持达到的力度；有终点标注时按标注播放。各档音量和音色差异进一步加大。瞬时强音只作用于当前位置。','渐强起点比终点更强，或渐弱起点比终点更弱时提示矛盾并提供修正。','在“歌词”输入文字，Enter 保存；歌词排在音符下方并自动保存，播放时忽略。']],
 ['连音、排版与错误',['单独按下并松开 Alt 新增一个小节；长按约半秒后连续增加，定位到新增小节。Shift+Alt 删除末尾一个小节，长按连续删除，至少保留一个小节；一次长按可一次撤销。原“＋小节”位置改为“小节数”输入框，输入总数并按 Enter 或离开输入框应用；Esc 取消输入。增加时追加空白小节，减少时删除末尾小节；涉及已有内容时需确认，支持撤销。鼠标悬停在输入框上滚轮向上增加、向下减少，涉及已有内容的减少需确认。数量随当前谱子、快捷键、滚轮和撤销同步更新；Alt+Tab 等组合不新增小节，输入文字或弹窗中暂停小节快捷键。','反复次数可直接输入正整数，没有预设上限；小节或反复终点的菜单也可修改总遍数。','连音数量 2–32，可直接输入或拖动滑条，并确定整组总时值。选中连续音符应用，也可插入新组。若均分后的时值可用普通或附点音符表示，不显示连音括号。','短音符按拍连接符梁，可手动连接或断开。未写满的小节始终留出后续录入空间，切换小节或模式不会提前整理；小节时值恰好填满后才自动排布，主动拖动的位置保留；圆滑线避开符干、符梁，简谱延时横线按拍均匀排布。','时值不符、重复升降号、无效连线、连音、反复等问题列在谱面下方，可定位、一键修正并撤销。']],
 ['播放与演奏效果',['P 播放／暂停，继续播放从暂停的位置开始；S 停止并回到 0:00。播放键在播放中显示“暂停”，暂停后显示“继续播放”。点击“部分播放”或首次按 Shift+P 后，依次点击起点和终点（音符、休止符或小节空白处）；终点包含所点击的音符，空白处指定整小节边界。谱面显示每一步提示及绿／橙色线。完成后按 Shift+P 开始或暂停部分播放，也可使用原来的播放按钮。悬停“部分播放”可“重选范围”或“恢复全曲”；Esc 取消未完成的选择并保留原范围。片段保持范围内的反复、力度、速度和奏法，各谱子独立保存播放范围，标记不参与打印。','钢琴播放体现升降、八度、力度、渐强渐弱、连音、反复、返回与踏板。力度档位采用更宽的音量差异，同时改变明亮度；渐强渐弱连续作用于音量和音色，指定终点力度时以该力度为准。琶音分先后起音，滑音经过中间音高，倚音、颤音、波音、回音实际发声。','断奏、顿音、重音、强重音、保持音、连奏、连断奏、换气及延长记号影响音长、起音或间隙；圆滑线连贯，延音线同音持续。','保持钢琴音色；pizz.／arco 采用短促拨奏与较缓连贯起音模拟。表情文字采用相应的力度、连贯度和起音处理；其具体演奏仍可由演奏者判断。']],
 ['保存、打印与参考',['所有谱子自动保存在本浏览器。导出当前谱子的 .score.json 作为备份，“打开”读入为新增谱子。桌面版和网页版可通过导出／打开交换谱子，不会自动跨地址同步。','“打印”导出整份当前谱面的打印视图。底部统计全部声部音符数、最高音、最低音和含反复的播放时长。','参考：<a href="https://ssb22.user.srcf.net/mwrhome/jianpu-ly.html" target="_blank" rel="noopener">简谱记法</a> · <a href="https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/arpeggiate/" target="_blank" rel="noopener">琶音</a> · <a href="https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/glissando/" target="_blank" rel="noopener">滑音</a>。','钢琴采样 Salamander Grand Piano，Alexander Holm，CC BY 3.0；Bravura 字体 Steinberg，SIL OFL 1.1。']]
];
function closeHelpMenu(){$('helpMenu').hidden=true;$('help').setAttribute?.('aria-expanded','false');}
function toggleHelpMenu(){const menu=$('helpMenu');if(!menu.hidden){closeHelpMenu();return;}closeScoreList();hideMenu();closeScoreSetting();menu.innerHTML='<div class="help-categories">'+HELP_TOPICS.map(([title],i)=>'<button class="menu-category-title" data-help-topic="'+i+'" aria-expanded="false">'+title+'<span aria-hidden="true">›</span></button>').join('')+'</div><section id="helpDetail" class="help-detail" hidden></section>';menu.hidden=false;$('help').setAttribute('aria-expanded','true');const b=$('help').getBoundingClientRect();menu.style.left=Math.max(8,Math.min(b.left,window.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.min(b.bottom+8,window.innerHeight-100)+'px';}
function showHelpTopic(index){const [title,items]=HELP_TOPICS[index]||HELP_TOPICS[0];$('helpDetail').hidden=false;$('helpDetail').innerHTML='<h3>'+title+'</h3><ol>'+items.map(t=>'<li>'+t+'</li>').join('')+'</ol>';$('helpMenu').querySelectorAll('[data-help-topic]').forEach(b=>{const open=+b.dataset.helpTopic===index;b.classList.toggle('active',open);b.setAttribute('aria-expanded',String(open));});const menu=$('helpMenu');menu.style.left=Math.max(8,Math.min(parseFloat(menu.style.left)||8,window.innerWidth-menu.offsetWidth-8))+'px';}
function bindNotebookControls(){$('chooseScore').onclick=toggleScoreList;$('scoreList').addEventListener('click',e=>{const trash=e.target.closest('[data-delete-document]');if(trash){requestDeleteDocument(trash.dataset.deleteDocument);return;}const item=e.target.closest('[data-document]');if(item)activateDocument(item.dataset.document);});$('help').onclick=toggleHelpMenu;$('helpMenu').addEventListener('click',e=>{const item=e.target.closest('[data-help-topic]');if(item)showHelpTopic(+item.dataset.helpTopic);});document.addEventListener('pointerdown',e=>{if(!$('helpMenu').contains(e.target)&&!$('help').contains(e.target))closeHelpMenu();if(!$('scoreList').contains(e.target)&&!$('chooseScore').contains(e.target))closeScoreList();});}

function adjustTempoWheel(event){if(!event.deltaY)return;event.preventDefault();const input=event.target,value=Number(input.value);if(!Number.isFinite(value)||value<=0)return;const step=value<1?Math.pow(10,Math.floor(Math.log10(value))):1,next=value+(event.deltaY<0?step:-step);if(next>0)input.value=Number(next.toPrecision(12));}
function deleteNoteAtContext(event){const t=targetAt(event.target),point=coordinates(event),p=t?.type==='note'?notePositions.get(t.id):null;if(!p)return;event.preventDefault();hideMenu();cancelGesture();const index=t.toneIndex??headHit(p,point)?.toneIndex??toneIndexAt(p,point);commit(()=>{const f=findNote(t.id);if(!f)return;const tones=M.tones(f.e);if(f.e.type==='note'&&tones.length>1){const remaining=tones.filter((tone,i)=>i!==index);M.setTones(f.e,remaining);}else{score.measures[f.mi].events.splice(f.ei,1);cleanRemovedNoteReferences(new Set([f.e.id]));}dropNoteSelection(t.id);refreshRecentNote();},false);$('score').focus({preventScroll:true});}
function transferInputEntries(from,to,tones){const ids=new Set(tones.map(t=>t.inputId).filter(Boolean));recentInputs.forEach(entry=>{if(entry.id===from&&ids.has(entry.toneId||entry.baseInputId))entry.id=to;});}
function splitMovingTone(e,indices){const tones=M.tones(e),moving=tones.filter((t,i)=>indices.has(i)),remaining=tones.filter((t,i)=>!indices.has(i));if(!remaining.length)return e;const copy={...JSON.parse(JSON.stringify(e)),id:M.id()};M.setTones(copy,moving,{detach:true});M.setTones(e,remaining);for(const key of ['slur','tie','beamGroup','tuplet','hairpin','glissando','pedal']){copy[key]=typeof copy[key]==='boolean'?false:key==='tuplet'?null:'';}copy.hairpinTo=copy.glissTo=copy.pedalTo='';copy.graceNotes=[];copy.lyric='';transferInputEntries(e.id,copy.id,moving);return copy;}
function moveSelectedInSequence(dir){const selectedEvents=selectedList();if(!selectedEvents.length)return;hideMenu();cancelGesture();commit(()=>{const ordered=dir>0?[...selectedEvents].reverse():selectedEvents;for(const event of ordered){const f=findNote(event.id);if(!f)continue;const all=score.measures.flatMap(m=>M.events(score,m,event.voice)).filter(e=>!e.placeholder),at=all.indexOf(event),neighbor=all[at+dir];if(!neighbor||selectedNotes.has(neighbor.id))continue;const dest=findNote(neighbor.id),indices=selectedIndices(event);if(event.type==='note'&&indices.size<M.tones(event).length){if(neighbor.type==='rest')throw Error('不能把和弦单音移动到休止符，请拖到空白谱位。');const moving=M.tones(event).filter((t,i)=>indices.has(i));if(moving.some(t=>!t.singerLayer&&M.tones(neighbor).some(n=>n.pitch===t.pitch)))throw Error('移动后的和弦音高重复。');if(M.tones(neighbor).length+moving.length>32)throw Error('单个和弦最多 32 个音。');const detached=splitMovingTone(event,indices);neighbor.chord.push(...moving);M.syncChordRhythm(neighbor);transferInputEntries(detached.id,neighbor.id,moving);clearSelection();putNoteSelection(neighbor.id,new Set(moving.map((t,i)=>M.tones(neighbor).length-moving.length+i)));}else{if(f.mi===dest.mi){const arr=score.measures[f.mi].events;[arr[f.ei],arr[dest.ei]]=[arr[dest.ei],arr[f.ei]];}else{score.measures[f.mi].events[f.ei]=neighbor;score.measures[dest.mi].events[dest.ei]=event;}event.positionRatio=null;event.manualPosition=false;neighbor.positionRatio=null;neighbor.manualPosition=false;}focusMeasure(findNote(event.id)?.mi??dest.mi,event.voice);}refreshRecentNote();},false);$('score').focus({preventScroll:true});}
function moveDraggedNotes(g,point){const first=findNote(g.first),firstPos=notePositions.get(g.first);if(!first||!firstPos)return;const candidates=geometry.filter(bar=>bar.voice===first.e.voice&&point.x>=bar.start-8&&point.x<=bar.end+8),target=candidates.sort((a,b)=>Math.abs(point.y-(a.top+a.base)/2)-Math.abs(point.y-(b.top+b.base)/2))[0];if(!target){toast('请在同一声部的谱面内松开鼠标。');render();return;}const originalTone=M.tones(first.e)[g.toneIndex],pitchDelta=notation==='staff'&&originalTone?target.bottomPitch+Math.round((target.base-point.y)/6)-originalTone.pitch:notation==='jianpu'?Math.round((g.start.y-point.y)/48)*7:0,dx=point.x-g.start.x,horizontal=target.mi!==first.mi||Math.abs(dx)>8,items=g.items||[{id:g.first,indices:[g.toneIndex]}];hideMenu();commit(()=>{const moved=[];for(const item of items){const f=findNote(item.id);if(!f)continue;const indices=new Set(item.indices),e=f.e;if(e.type==='note')shiftEventPitch(e,pitchDelta,indices);if(!horizontal){moved.push({id:e.id,indices});continue;}const moving=e.type==='note'?splitMovingTone(e,indices):e;if(moving===e)score.measures[f.mi].events.splice(f.ei,1);const dest=score.measures[target.mi];clearPlaceholders(target.mi,e.voice);const x=(notePositions.get(item.id)?.x??firstPos.x)+dx,following=target.positions.find(p=>p.x>x&&!items.some(i=>i.id===p.e.id)&&findNote(p.e.id));const at=following?dest.events.findIndex(n=>n.id===following.e.id):dest.events.length;moving.positionRatio=positionRatio(target,x);moving.manualPosition=true;dest.events.splice(at<0?dest.events.length:at,0,moving);moved.push({id:moving.id,indices:moving===e?indices:null});}clearSelection();moved.forEach(item=>putNoteSelection(item.id,item.indices));focusMeasure(target.mi,first.e.voice);refreshRecentNote();},false);}

let copiedScoreContent=null;
const scoreClipboardPrefix='PUJI_CLIPBOARD_V1\n';
const cloneContent=value=>JSON.parse(JSON.stringify(value));
function copiedMark(t){const m=score.measures[t.mi],e=findNote(t.id)?.e;if(measureSymbolKinds.includes(t.kind))return {kind:t.kind,value:m[t.kind],length:0};if(t.kind==='measureOctave')return {kind:'ottava',value:m.octaves?.[t.id],length:0,measure:true};if(t.kind==='measureHairpin')return {kind:'hairpin',value:m.hairpins?.[t.id]?.kind,length:0,measure:true};if(t.kind==='measureArticulation')return {kind:'articulation',value:m.articulation,length:0,measure:true};if(!e)return null;const all=score.measures.flatMap(m=>M.events(score,m,e.voice));let list=[e],value=e[t.kind];if(t.kind==='slur'){list=all.filter(n=>n.slur===e.slur);value='add';}if(t.kind==='ottava')list=octaveGroup(t);if(['hairpin','glissando','pedal'].includes(t.kind)){const last=findNote(e[t.kind==='hairpin'?'hairpinTo':t.kind==='pedal'?'pedalTo':'glissTo'])?.e;if(last)list=betweenNotes(e,last);}if(t.kind==='tuplet'){list=all.filter(n=>n.tuplet?.id===e.tuplet?.id);value={count:e.tuplet.count,total:e.tuplet.total};}if(t.kind==='grace')value=cloneContent(t.graceId?e.graceNotes.filter(n=>n.id===t.graceId):e.graceNotes);return {kind:t.kind,value,length:list.length};}
function clipboardPitchContext(n,indices=null){if(!n)return null;return {shift:n.shift,tones:n.tones.filter((t,i)=>!indices||indices.has(i)).map(t=>({pitch:t.pitch,acc:t.acc,written:M.tones(n.e)[t.toneIndex].accidental})),graces:n.graces.map(g=>({pitch:g.pitch,acc:g.acc,written:g.accidental}))};}
function buildScoreClipboard(){
  const copiedBars=score.measures.map((m,mi)=>({m,mi})).filter(({m})=>selectedMeasures.has(m.id)),selectedEvents=selectedList(),start=Math.min(...copiedBars.map(b=>b.mi),...selectedEvents.map(e=>findNote(e.id).mi)),resolved=new Map(M.resolved(score).map(n=>[n.e.id,n]));
  const payload={format:'puji-selection',version:1,notation,voices:cloneContent(score.voices),bars:[],notes:[],marks:[]};
  copiedBars.forEach(({m,mi})=>{const voices=selectedMeasureVoices.get(m.id)||new Set(score.voices.map(v=>v.id)),copy=cloneContent(m);copy.events=copy.events.filter(e=>voices.has(e.voice));payload.bars.push({offset:mi-start,measure:copy,settings:cloneContent(Object.fromEntries([...voices].map(v=>[v,config(mi,v)]))),contexts:Object.fromEntries(copy.events.map(e=>[e.id,clipboardPitchContext(resolved.get(e.id))]))});});
  selectedEvents.forEach(e=>{const f=findNote(e.id);if(copiedBars.some(b=>b.mi===f.mi&&(selectedMeasureVoices.get(b.m.id)||new Set(score.voices.map(v=>v.id))).has(e.voice)))return;const copy=cloneContent(e),indices=selectedIndices(e),tones=M.tones(e).filter((t,i)=>indices.has(i));if(e.type==='note'&&tones.length)M.setTones(copy,tones,{detach:tones.length<M.tones(e).length});payload.notes.push({offset:f.mi-start,event:copy,context:clipboardPitchContext(resolved.get(e.id),indices)});});
  const included=new Set([...payload.bars.flatMap(b=>b.measure.events),...payload.notes.map(n=>n.event)].map(e=>e.id));
  // Decorations already embedded in a copied note/bar must not be added twice.
  payload.marks=[...selectedSymbols.values()].filter(t=>!included.has(t.id)&&!copiedBars.some(b=>b.mi===t.mi&&(measureSymbolKinds.includes(t.kind)||t.kind.startsWith('measure')))).map(copiedMark).filter(Boolean);
  return payload.bars.length||payload.notes.length||payload.marks.length?payload:null;
}
async function copySelectedContent(){const payload=buildScoreClipboard();if(!payload){toast('请先选择要复制的音符、小节或符号。');return;}copiedScoreContent=payload;try{await navigator.clipboard?.writeText(scoreClipboardPrefix+JSON.stringify(payload));}catch{}toast('已复制所选内容。');}
function freshClipboardEvents(events,voiceMap){
  const ids=new Map(events.map(e=>[e.id,M.id()])),groups=new Map(),group=(kind,id)=>{if(!id)return id;const k=kind+':'+id;if(!groups.has(k))groups.set(k,M.id());return groups.get(k);};
  const cleanRhythm=r=>{if(!r)return;delete r.shortcutInputTicks;delete r.shortcutDotBase;if(r.tuplet)r.tuplet.id=group('tuplet',r.tuplet.id);};
  const cleanNote=e=>{delete e.baseInputId;delete e.manualPosition;e.positionRatio=null;cleanRhythm(e);cleanRhythm(e.stepRhythm);cleanRhythm(e.toneRhythm);e.chord?.forEach(t=>{delete t.inputId;cleanRhythm(t.rhythm);});e.graceNotes?.forEach(g=>g.id=M.id());for(const key of ['hairpinTo','glissTo','pedalTo']){const old=e[key];e[key]=ids.get(old)||'';if(old&&!e[key])e[key==='hairpinTo'?'hairpin':key==='glissTo'?'glissando':'pedal']=key==='pedalTo'?false:'';}for(const key of ['slur','beamGroup','arpeggioGroup'])e[key]=group(key,e[key]);};
  return events.map(raw=>{const e=cloneContent(raw);e.id=ids.get(raw.id);e.voice=voiceMap.get(raw.voice)||activeVoice;cleanNote(e);if(e.restoredNote){e.restoredNote.id=e.id;e.restoredNote.voice=e.voice;cleanNote(e.restoredNote);}return e;});
}
function restoreClipboardPitches(entries){
  // Store resolved pitch at copy time: a null accidental can depend on earlier notes.
  let resolved=new Map(M.resolved(score).map(n=>[n.e.id,n]));
  entries.forEach(({e,context})=>{if(!context)return;const shift=resolved.get(e.id)?.shift??0,delta=(context.shift-shift)*7;
    context.tones.forEach((t,i)=>{const tone=i?e.chord[i-1]:e,pitch=t.pitch+delta;if(pitch<0||pitch>66)throw Error('目标谱号或八度使粘贴音高超出支持范围。');tone.pitch=pitch;tone.accidental=t.acc;});
    context.graces.forEach((g,i)=>{if(!e.graceNotes[i])return;const pitch=g.pitch+delta;if(pitch<0||pitch>66)throw Error('倚音音高超出支持范围。');e.graceNotes[i].pitch=pitch;e.graceNotes[i].accidental=g.acc;});
  });
  resolved=new Map(M.resolved(score).map(n=>[n.e.id,n]));
  entries.forEach(({e,context})=>{if(!context)return;const n=resolved.get(e.id);context.tones.forEach((t,i)=>{if(t.written==null&&n?.tones[i]?.redundant)(i?e.chord[i-1]:e).accidental=null;});});
  // Grace accidentals do not update the bar's accidental state; test each omission.
  entries.forEach(({e,context})=>{context?.graces.forEach((g,i)=>{const grace=e.graceNotes[i];if(!grace||g.written!=null)return;grace.accidental=null;const n=M.resolved(score).find(n=>n.e.id===e.id);if(n?.graces[i]?.acc!==g.acc)grace.accidental=g.acc;});});
}
function pasteScoreClipboard(payload){
  if(payload?.format!=='puji-selection'||payload.version!==1)return;const anchor=getSelected(),baseMi=anchor?.mi??currentMeasure,baseVoice=anchor?.e.voice||activeVoice,voiceMap=new Map(),usedVoices=new Set([...payload.notes.map(n=>n.event.voice),...payload.bars.flatMap(b=>b.measure.events.map(e=>e.voice)),...payload.bars.flatMap(b=>Object.keys(b.settings||{}))]),selectedTargets=selectedList().map(e=>e.id);
  commit(()=>{
    if(payload.notation!==notation&&(payload.notes.length||payload.bars.length))throw Error('请先切换到相同谱式，再粘贴内容。');
    payload.voices.filter(v=>usedVoices.has(v.id)).forEach((v,i)=>{const target=usedVoices.size===1?score.voices.find(v=>v.id===baseVoice):score.voices[score.voices.findIndex(v=>v.id===baseVoice)+i]||addVoice(v.name,v.clef);voiceMap.set(v.id,target.id);});
    const offsets=[...payload.notes.map(n=>n.offset),...payload.bars.map(b=>b.offset)],last=baseMi+Math.max(0,...offsets);if(last>=300)throw Error('最多 300 小节。');while(score.measures.length<=last)appendEmptyMeasure();clearSelection();
    const flat=[...payload.bars.flatMap(b=>b.measure.events),...payload.notes.map(n=>n.event)],fresh=freshClipboardEvents(flat,voiceMap),eventMap=new Map(flat.map((e,i)=>[e.id,fresh[i]])),contexts=[];
    payload.bars.forEach(b=>{const mi=baseMi+b.offset,m=score.measures[mi],source=b.measure,settings=Object.entries(b.settings||{}),effective=settings[0]?.[1];
      for(const key of ['key','mode','meter','bpm'])m[key]=cloneContent(effective?.[key]??source[key]??null);
      for(const key of ['dynamic','expression','articulation','ornament','repeatStart','repeatEnd','ending','navigation'])m[key]=cloneContent(source[key]??null);
      const copiedVoices=new Set([...settings.map(([old])=>voiceMap.get(old)||baseVoice),...source.events.map(e=>voiceMap.get(e.voice)||baseVoice)]),removed=new Set(m.events.filter(e=>copiedVoices.has(e.voice)).map(e=>e.id));m.events=m.events.filter(e=>!copiedVoices.has(e.voice));cleanRemovedNoteReferences(removed);
      m.clefs??={};m.octaves??={};m.hairpins??={};settings.forEach(([old,c])=>{const voice=voiceMap.get(old)||baseVoice;m.clefs[voice]=c.clef;m.octaves[voice]=source.octaves?.[old]||0;if(source.hairpins?.[old])m.hairpins[voice]={...source.hairpins[old],id:M.id()};else delete m.hairpins[voice];});
      source.events.forEach(raw=>{const e=eventMap.get(raw.id);m.events.push(e);contexts.push({e,context:b.contexts?.[raw.id]});if(!e.placeholder)putNoteSelection(e.id);});
    });
    // Each destination voice/bar gets its own cursor, including unanchored paste.
    const cursors=new Map();payload.notes.forEach(n=>{const mi=baseMi+n.offset,e=eventMap.get(n.event.id),m=score.measures[mi],key=mi+':'+e.voice;clearPlaceholders(mi,e.voice);const previous=cursors.get(key),prior=previous?m.events.indexOf(previous):anchor?.mi===mi&&anchor.e.voice===e.voice?m.events.findIndex(e=>e.id===anchor.e.id):-1;m.events.splice(prior<0?m.events.length:prior+1,0,e);cursors.set(key,e);contexts.push({e,context:n.context});putNoteSelection(e.id);});
    restoreClipboardPitches(contexts);
    const targets=fresh.some(e=>!e.placeholder)?fresh.filter(e=>!e.placeholder):selectedTargets.map(id=>findNote(id)?.e).filter(Boolean),recent=targets[0]||refreshRecentNote();
    payload.marks.forEach(mark=>{if(mark.measure||measureSymbolKinds.includes(mark.kind)){if(mark.kind==='articulation')score.measures[baseMi][mark.kind]=mark.value;else applySymbolTo(mark.kind,mark.value,[],[baseMi]);return;}if(!recent)throw Error('粘贴符号前请选择目标音符。');const all=score.measures.flatMap(m=>M.events(score,m,recent.voice)),at=all.indexOf(recent),list=all.slice(at,at+Math.max(1,mark.length));if(list.length<mark.length)throw Error('目标音符数量不足，无法粘贴范围符号。');if(mark.kind==='grace'){recent.graceNotes.push(...mark.value.map(g=>({...g,id:M.id()})));if(recent.graceNotes.length>16)throw Error('每个音符最多 16 个倚音。');}else if(mark.kind==='articulation')recent.articulation=mark.value;else if(mark.kind==='tuplet')M.setTuplet(list,mark.value.count,mark.value.total);else applySymbolTo(mark.kind,mark.value,list);});
    focusMeasure(baseMi,baseVoice);jianpuChordTarget=null;
  });$('score').focus({preventScroll:true});
}
async function pasteSelectedContent(){let payload=copiedScoreContent;try{const text=await navigator.clipboard?.readText();if(text?.startsWith(scoreClipboardPrefix)){if(text.length>8e6)throw Error('复制内容过大。');payload=JSON.parse(text.slice(scoreClipboardPrefix.length));}}catch{}if(!payload){toast('请先复制记谱器中的内容。');return;}pasteScoreClipboard(payload);}
