'use strict';
let notebook=null,staffLastInputId=null,staffLastInputToneIndex=0,recentInputs=[];
function documentDefaults(){return {duration:4,dots:0,exactTicks:null,triplet:false,accidental:null,dynamic:'',expression:'',articulation:'',ornament:'',ottava:0,tie:false};}
function makeDocument(type,value=null){const content=value||M.blank();content.notation=type;return {id:M.id(),score:content,undo:[],redo:[],ui:{}};}
function initializeNotebook(){
  try{const raw=JSON.parse(localStorage.getItem('puji-notebook-v1')||'null');if(raw?.version===1&&Array.isArray(raw.documents)&&raw.documents.length){const documents=raw.documents.map(d=>({id:typeof d.id==='string'?d.id:M.id(),score:M.sanitize(d.score),undo:[],redo:[],ui:d.ui||{}}));notebook={version:1,activeId:raw.activeId,preferred:raw.preferred||{},documents};if(!documents.some(d=>d.id===notebook.activeId))notebook.activeId=documents[0].id;score=documents.find(d=>d.id===notebook.activeId).score;}}
  catch{setTimeout(()=>toast('多谱子保存读取失败，已保留上一份乐谱。请导出备份。'),500);}
  if(!notebook){const d=makeDocument(score.notation||'staff',score);notebook={version:1,activeId:d.id,preferred:{[d.score.notation]:d.id},documents:[d]};}
}
function currentDocument(){return notebook?.documents.find(d=>d.id===notebook.activeId);}
function stashDocument(){const d=currentDocument();if(!d)return;d.score=score;d.undo=undoStack;d.redo=redoStack;d.ui={activeVoice,currentMeasure,mode,defaults:{...defaults},jianpuCursor,jianpuOctave,jianpuRhythmOverride,revealedVoice,staffLastInputId,staffLastInputToneIndex,recentInputs};}
function saveNotebook(){stashDocument();localStorage.setItem('puji-notebook-v1',JSON.stringify({version:1,activeId:notebook.activeId,preferred:notebook.preferred,documents:notebook.documents.map(d=>({id:d.id,score:d.score,ui:d.ui}))}));}
function activateDocument(id){
  const d=notebook.documents.find(d=>d.id===id);if(!d)return;cancelAltMeasure();stop();cancelGesture();closeScoreSetting();closeHelpMenu();closeScoreList();stashDocument();notebook.activeId=d.id;score=d.score;notation=score.notation||'staff';notebook.preferred[notation]=d.id;
  const ui=d.ui||{};activeVoice=score.voices.some(v=>v.id===ui.activeVoice)?ui.activeVoice:score.voices[0].id;currentMeasure=Math.max(0,Math.min(score.measures.length-1,ui.currentMeasure||0));mode=notation==='jianpu'?'select':ui.mode||'edit';defaults={...documentDefaults(),...ui.defaults};jianpuCursor=ui.jianpuCursor||null;jianpuOctave=ui.jianpuOctave||0;jianpuRhythmOverride=!!ui.jianpuRhythmOverride;revealedVoice=ui.revealedVoice||null;staffLastInputId=ui.staffLastInputId||null;staffLastInputToneIndex=ui.staffLastInputToneIndex||0;recentInputs=Array.isArray(ui.recentInputs)?ui.recentInputs:[];undoStack=d.undo||[];redoStack=d.redo||[];symbolTool=null;symbolStart=null;jianpuChordTarget=null;clearSelection();render();save();$('score').focus({preventScroll:true});
}
function switchEditor(next){if(next===notation)return;finishMeasure();let d=notebook.documents.find(d=>d.id===notebook.preferred[next]&&d.score.notation===next)||notebook.documents.find(d=>d.score.notation===next);if(!d){d=makeDocument(next);notebook.documents.push(d);}activateDocument(d.id);}
function openNewScore(value=null){const d=makeDocument(value?.notation||notation,value);notebook.documents.push(d);activateDocument(d.id);}
function pristineDocument(d){const s=d?.score;return s&&s.title==='未命名作品'&&s.voices.length===1&&s.measures.length===1&&s.key===0&&s.mode==='major'&&s.bpm===96&&s.meter.join('/')==='4/4'&&s.voices[0].clef==='treble'&&s.voices[0].name==='声部 1'&&!s.voices[0].muted&&s.measures[0].events.length===0&&JSON.stringify({...s.measures[0],id:''})===JSON.stringify({...M.measure(),id:''});}
function scoreSignature(s){
  // Compare musical content, not generated identifiers, document titles or input layout.
  const resolved=new Map(M.resolved(s).map(n=>[n.e.id,n])),locations=new Map(),groups=new Map();
  s.measures.forEach((m,mi)=>s.voices.forEach((v,vi)=>M.events(s,m,v.id).forEach((e,ei)=>locations.set(e.id,[mi,vi,ei]))));
  const ref=id=>id?(locations.get(id)||['missing',id]):null,group=(kind,id)=>{if(!id)return null;const key=kind+':'+id;if(!groups.has(key))groups.set(key,groups.size);return groups.get(key);},ticks=e=>Number(M.ticks(e).toFixed(6));
  return JSON.stringify({notation:s.notation,voices:s.voices.map(v=>({name:v.name,muted:!!v.muted})),measures:s.measures.map((m,mi)=>({
    dynamic:m.dynamic||'',expression:m.expression||'',articulation:m.articulation||'',ornament:m.ornament||'',repeatStart:!!m.repeatStart,repeatEnd:m.repeatEnd||0,ending:m.ending||'',navigation:m.navigation||'',
    voices:s.voices.map(v=>{const c=M.settings(s,mi,v.id);return {key:c.key,mode:c.mode,meter:c.meter,bpm:c.bpm,clef:s.notation==='staff'?c.clef:null,hairpin:m.hairpins?.[v.id]?.kind||'',events:M.events(s,m,v.id).map(e=>{
      const n=resolved.get(e.id),tones=e.type==='rest'?[]:n.tones.map((t,i)=>[t.pitch+n.shift*7,t.acc,!!e.chord?.[i-1]?.singerLayer]);
      return {type:e.type,ticks:ticks(e),tones,graces:(n.graces||[]).map(g=>[g.pitch+n.shift*7,g.acc,g.duration,!!g.slash]),lyric:e.lyric||'',dynamic:e.dynamic||'',expression:e.expression||'',articulation:e.articulation||'',ornament:e.ornament||'',tie:!!e.tie,slur:group('slur',e.slur),beam:group('beam',e.beamGroup),beamBreak:!!e.beamBreak,
        tuplet:e.tuplet?{group:group('tuplet',e.tuplet.id),count:e.tuplet.count,total:e.tuplet.total}:null,arpeggio:e.arpeggio||'',arpeggioGroup:group('arpeggio',e.arpeggioGroup),glissando:e.glissando||'',glissTo:ref(e.glissTo),hairpin:e.hairpin||'',hairpinTo:ref(e.hairpinTo),pedal:!!e.pedal,pedalTo:ref(e.pedalTo)};
    })};})
  }))});
}
function openConvertedScore(content){
  stashDocument();const signature=scoreSignature(content),targets=notebook.documents.filter(d=>d.score.notation===content.notation),existing=targets.find(d=>d.id===notebook.preferred[content.notation]),matching=[existing,...targets.filter(d=>d!==existing)].find(d=>d&&scoreSignature(d.score)===signature);
  if(matching){activateDocument(matching.id);return;}if(pristineDocument(existing)){existing.score=content;existing.ui={};existing.undo=[];existing.redo=[];activateDocument(existing.id);}else openNewScore(content);
}
function pageScore(direction){const documents=notebook.documents.filter(d=>d.score.notation===notation);if(documents.length<2)return;const at=documents.findIndex(d=>d.id===notebook.activeId),next=documents[(at+direction+documents.length)%documents.length];activateDocument(next.id);}
function syncScoreList(){const d=currentDocument();if(d)d.score=score;const items=notebook.documents.filter(d=>d.score.notation===notation);$('chooseScore').textContent='谱子 '+(items.findIndex(d=>d.id===notebook.activeId)+1)+' / '+items.length+' ▾';$('scoreList').innerHTML=items.map((d,i)=>'<div class="score-list-row" role="none"><button class="score-list-select" role="menuitemradio" aria-checked="'+(d.id===notebook.activeId)+'" data-document="'+escapeXml(d.id)+'">'+(i+1)+'. '+escapeXml(d.score.title)+(d.id===notebook.activeId?' ✓':'')+'</button><button class="score-list-delete" role="menuitem" data-delete-document="'+escapeXml(d.id)+'" aria-label="删除谱子：'+escapeXml(d.score.title)+'" title="删除谱子"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></svg></button></div>').join('');}
function requestDeleteDocument(id){const d=notebook.documents.find(d=>d.id===id);if(!d)return;closeScoreList();$('chooseScore').focus({preventScroll:true});confirmAction('确认删除谱子？','是否确认删除《'+d.score.title+'》？',()=>deleteDocument(id),'确认删除');}
function deleteDocument(id){
  const removed=notebook.documents.find(d=>d.id===id);if(!removed)return;stashDocument();const type=removed.score.notation,wasActive=notebook.activeId===id,sameType=notebook.documents.filter(d=>d.score.notation===type),at=sameType.findIndex(d=>d.id===id);
  notebook.documents=notebook.documents.filter(d=>d.id!==id);const remaining=notebook.documents.filter(d=>d.score.notation===type);let next=remaining[Math.min(at,remaining.length-1)];
  if(wasActive&&!next){next=makeDocument(type);notebook.documents.push(next);}if(notebook.preferred[type]===id){if(next)notebook.preferred[type]=next.id;else delete notebook.preferred[type];}
  if(wasActive)activateDocument(next.id);else{syncScoreList();save();$('chooseScore').focus({preventScroll:true});}
}
function closeScoreList(){$('scoreList').hidden=true;$('chooseScore').setAttribute?.('aria-expanded','false');}
function toggleScoreList(){const list=$('scoreList');if(!list.hidden){closeScoreList();return;}closeHelpMenu();hideMenu();syncScoreList();list.hidden=false;$('chooseScore').setAttribute('aria-expanded','true');}
function changeJianpuBeat(amount,reset=false){const list=selectedList().length?selectedList():[reset?findNote(staffLastInputId)?.e||previousJianpuNote():previousJianpuNote()].filter(Boolean);if(!list.length){toast('请先输入或选择音符。');return;}const changes=list.map(e=>({e,ticks:reset?48:M.ticks(e)+amount*48}));if(changes.some(c=>c.ticks<=M.EPS||c.ticks>3072)){toast('缩短后时值必须大于零；要删除音符请按 Delete。');return;}hideMenu();commit(()=>{detachJianpuTuplets(list);changes.forEach(c=>setJianpuTicks(c.e,c.ticks));const last=changes.at(-1).e;defaults.duration=last.duration;defaults.dots=last.dots;defaults.exactTicks=last.exactTicks??null;jianpuRhythmOverride=false;},false);$('score').focus({preventScroll:true});}
function moveRecentPitch(dir){const e=findNote(staffLastInputId)?.e;if(!e){toast('请先键入一个音符。');return;}if(e.type==='rest'){toast('休止符没有音高。');return;}const index=Math.min(staffLastInputToneIndex,M.tones(e).length-1);commit(()=>shiftEventPitch(e,dir,new Set([index])));$('score').focus({preventScroll:true});}
function scaleRecentDuration(factor){const e=findNote(staffLastInputId)?.e;if(!e){toast('请先键入一个音符。');return;}commit(()=>{detachJianpuTuplets([e]);setJianpuTicks(e,M.ticks(e)*factor);defaults.duration=e.duration;defaults.dots=e.dots;defaults.exactTicks=e.exactTicks??null;if(notation==='jianpu')jianpuRhythmOverride=false;});$('score').focus({preventScroll:true});}
function updateSymbolHint(){const hint=$('symbolStatus');hint.hidden=!symbolTool;if(!symbolTool)return;hint.textContent=symbolStart?'已选择起点，请选择终点':'点击谱面放置 '+symbolTool.label+(rangeSymbolKinds.includes(symbolTool.kind)?'，请选择起点':'');}
const HELP_TOPICS=[
 ['谱子与编辑器',['Shift+Tab 或谱式按钮只切换编辑器。五线谱、简谱各自保存，首次切换到另一个编辑器时打开空白谱子。','“一键转…”才进行转换。原谱保留；目标编辑器中已有内容相同的谱子时直接打开该谱子，不新增副本；没有相同谱子时才另建转换谱。简谱不支持的器乐符号会在转换前列出位置，继续后仅从转换副本中删除。','谱面右上角“谱子”按钮选择当前编辑器的谱子；PgUp／PgDn 切换。每份谱子的撤销与重做独立。新建和打开文件均新增谱子，保留已有进度。列表右侧垃圾桶删除相应谱子，确认后才删除；取消会保留内容。']],
 ['五线谱录入',['Tab 切换编辑与选择。编辑模式在空白谱位单击添加音符；再次点击音符头变为同样时值的休止符，再次点击休止符删除。点击同一时点的其他谱位添加和弦。','编辑模式 ←／→ 将刚输入的音符时值减半／加倍，并作为后续输入的默认时值。↑／↓ 无需选择即可将最近输入的一个音符上移／下移一个谱位，和弦只移动最近添加的那个音。空格输入一个四分音符中央 C。按 . 给最近输入的音符增加一个附点，可连续添加且不设数量上限；此操作不改变下一音符的默认时值。','悬停显示音高与落点；输入音符时不自动出现菜单。倚音工具开启后点击主音左侧谱位添加；编辑模式点击倚音或奏法符号删除。']],
 ['简谱录入与时值',['数字 1–7 连续录入音级，0 录入休止符，无需确认；默认沿用前一音符的时值，填满小节后继续到下一小节。','Enter 将上一音符延长一个四分拍，单选时延长所选音符；Shift+Enter 缩短一拍，剩余时值须大于零。空格把所选音符重置为一拍；未选择时把最近输入的音符或休止符重置为一拍。','Ctrl 多选或框选相邻同音音符，Enter 合并并精确相加时值。不同声部、音高、八度或不相邻会提示；叠放分组需选完整组。','点击已有数字再输入音级，在该时点上下叠放，可表示同声部分组演唱。点击空白处继续录入旋律。↑／↓ 改变所选音符八度；无选择时改变后续输入八度。←／→ 将所选音符时值减半／加倍；无选择时直接修改最近键入的音符或休止符，后续输入沿用修改后的时值。','数字下方每条横线减半时值；右侧延长横线每条增加一拍；长休止使用多个 0。数字上、下的点表示高、低八度，调号用 1=… 表示。']],
 ['选择、修改与撤销',['选择模式单击音符、小节空白或符号选择，再次点击取消。和弦单击选择其中一个音，双击选择整个和弦。Ctrl 点击多选；拖动框选，Ctrl 拖动追加。','五线谱编辑模式开始框选后自动转为选择模式。选择模式 ↑／↓ 移动一个谱位，←／→ 时值减半／加倍。Delete 删除所选对象。Backspace 有选择时保留选中删除；无选择时按录入顺序删除最近的音符、和弦单音、休止符、倚音、附点、力度、表情、歌词或符号，跨音符符号作为一个整体删除；支持撤销。','选中对象后悬停约半秒出现分类菜单，悬停或点击分类展开细项；离开后收起。Ctrl+Z 撤销，Ctrl+Y 或 Ctrl+Shift+Z 重做。']],
 ['调号、拍号与声部',['直接点击谱面左上角的调号、拍号与速度修改。速度可输入任意正数（含小数），无预设上下限。五线谱另外支持点击谱号和调式；简谱不显示这两个选项。','修改设置后选择“当前小节”或“之后所有小节（含当前）”。多选时“当前”应用到所选小节，“之后”从最早所选小节开始。','“＋ 声部”新增独立谱表，可命名为乐器或声部，支持静音与只播放当前声部。各声部独立录入，整行为空的声部隐藏；选择后展开当前行。删除声部后默认名称按顺序重新编号，手动名称保留。']],
 ['连线与范围符号',['“⌒ 连线”自动判断：连续同音连接为延音线，不同音高连接为圆滑线。详细菜单仍可分别修改或移除这两种线。','八度线、连线、渐强渐弱、滑音与踏板可在多选后直接应用，也可点按钮后依次点起点、终点，或从起点拖到终点。谱面内显示起点／终点提示，完成即退出添加。Esc 中途取消。','琶音应用到和弦，可上行、下行或连接同时点的多个谱表；渐强渐弱线与 cresc.、dim. 独立添加。简谱反复起点、终点在每行使用固定基线对齐。']],
 ['力度、表情与歌词',['选中音符或小节并悬停后打开“力度”“表情”“奏法”等分类；标记只添加到所选对象。播放初始力度为 mp，普通力度按声部延续直到出现新标注，不自动给后续音符添加标记。','渐强／渐弱无终点标注时移动两个等级（如 p→mf、f→mp），结束后保持达到的力度；有终点标注时按标注播放。各档音量和音色差异进一步加大。瞬时强音只作用于当前位置。','渐强起点比终点更强，或渐弱起点比终点更弱时提示矛盾并提供修正。','在“歌词”输入文字，Enter 保存；歌词排在音符下方并自动保存，播放时忽略。']],
 ['连音、排版与错误',['单独按下并松开 Alt 新增一个小节；长按约半秒后连续增加，定位到新增小节。Shift+Alt 删除末尾一个小节，长按连续删除，至少保留一个小节；一次长按可一次撤销。原“＋小节”位置改为“小节数”输入框，输入总数并按 Enter 或离开输入框应用；Esc 取消输入。增加时追加空白小节，减少时删除末尾小节；涉及已有内容时需确认，支持撤销。鼠标悬停在输入框上滚轮向上增加、向下减少，涉及已有内容的减少需确认。数量随当前谱子、快捷键、滚轮和撤销同步更新；Alt+Tab 等组合不新增小节，输入文字或弹窗中暂停小节快捷键。','反复次数可直接输入正整数，没有预设上限；小节或反复终点的菜单也可修改总遍数。','连音数量 2–32，可直接输入或拖动滑条，并确定整组总时值。选中连续音符应用，也可插入新组。若均分后的时值可用普通或附点音符表示，不显示连音括号。','短音符按拍连接符梁，可手动连接或断开。小节填满、切换小节或退出编辑后自动排布；圆滑线避开符干、符梁，简谱延时横线按拍均匀排布。','时值不符、重复升降号、无效连线、连音、反复等问题列在谱面下方，可定位、一键修正并撤销。']],
 ['播放与演奏效果',['P 播放／暂停，继续播放从暂停的位置开始；S 停止并回到 0:00。播放键在播放中显示“暂停”，暂停后显示“继续播放”。','钢琴播放体现升降、八度、力度、渐强渐弱、连音、反复、返回与踏板。力度档位采用更宽的音量差异，同时改变明亮度；渐强渐弱连续作用于音量和音色，指定终点力度时以该力度为准。琶音分先后起音，滑音经过中间音高，倚音、颤音、波音、回音实际发声。','断奏、顿音、重音、强重音、保持音、连奏、连断奏、换气及延长记号影响音长、起音或间隙；圆滑线连贯，延音线同音持续。','保持钢琴音色；pizz.／arco 采用短促拨奏与较缓连贯起音模拟。表情文字采用相应的力度、连贯度和起音处理；其具体演奏仍可由演奏者判断。']],
 ['保存、打印与参考',['所有谱子自动保存在本浏览器。导出当前谱子的 .score.json 作为备份，“打开”读入为新增谱子。桌面版和网页版可通过导出／打开交换谱子，不会自动跨地址同步。','“打印”导出整份当前谱面的打印视图。底部统计全部声部音符数、最高音、最低音和含反复的播放时长。','参考：<a href="https://ssb22.user.srcf.net/mwrhome/jianpu-ly.html" target="_blank" rel="noopener">简谱记法</a> · <a href="https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/arpeggiate/" target="_blank" rel="noopener">琶音</a> · <a href="https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/glissando/" target="_blank" rel="noopener">滑音</a>。','钢琴采样 Salamander Grand Piano，Alexander Holm，CC BY 3.0；Bravura 字体 Steinberg，SIL OFL 1.1。']]
];
function closeHelpMenu(){$('helpMenu').hidden=true;$('help').setAttribute?.('aria-expanded','false');}
function toggleHelpMenu(){const menu=$('helpMenu');if(!menu.hidden){closeHelpMenu();return;}closeScoreList();hideMenu();closeScoreSetting();menu.innerHTML='<div class="help-categories">'+HELP_TOPICS.map(([title],i)=>'<button class="menu-category-title" data-help-topic="'+i+'" aria-expanded="false">'+title+'<span aria-hidden="true">›</span></button>').join('')+'</div><section id="helpDetail" class="help-detail" hidden></section>';menu.hidden=false;$('help').setAttribute('aria-expanded','true');const b=$('help').getBoundingClientRect();menu.style.left=Math.max(8,Math.min(b.left,window.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.min(b.bottom+8,window.innerHeight-100)+'px';}
function showHelpTopic(index){const [title,items]=HELP_TOPICS[index]||HELP_TOPICS[0];$('helpDetail').hidden=false;$('helpDetail').innerHTML='<h3>'+title+'</h3><ol>'+items.map(t=>'<li>'+t+'</li>').join('')+'</ol>';$('helpMenu').querySelectorAll('[data-help-topic]').forEach(b=>{const open=+b.dataset.helpTopic===index;b.classList.toggle('active',open);b.setAttribute('aria-expanded',String(open));});const menu=$('helpMenu');menu.style.left=Math.max(8,Math.min(parseFloat(menu.style.left)||8,window.innerWidth-menu.offsetWidth-8))+'px';}
function bindNotebookControls(){$('chooseScore').onclick=toggleScoreList;$('scoreList').addEventListener('click',e=>{const trash=e.target.closest('[data-delete-document]');if(trash){requestDeleteDocument(trash.dataset.deleteDocument);return;}const item=e.target.closest('[data-document]');if(item)activateDocument(item.dataset.document);});$('help').onclick=toggleHelpMenu;$('helpMenu').addEventListener('click',e=>{const item=e.target.closest('[data-help-topic]');if(item)showHelpTopic(+item.dataset.helpTopic);});document.addEventListener('pointerdown',e=>{if(!$('helpMenu').contains(e.target)&&!$('help').contains(e.target))closeHelpMenu();if(!$('scoreList').contains(e.target)&&!$('chooseScore').contains(e.target))closeScoreList();});}
