const assert=require('node:assert/strict'),M=require('./dist/core.js');let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('positive tempos below and above former bounds, including fractions, survive saving and control playback timing',()=>{for(const bpm of [.125,1,12.5,29.9,240.5,480,10000]){const s=M.blank();s.bpm=bpm;s.measures[0].events=[M.event(28)];s.measures.push(M.measure({bpm:bpm*2,events:[M.event(29)]}));const back=M.sanitize(JSON.parse(JSON.stringify(s)));assert.equal(back.bpm,bpm);assert.equal(back.measures[1].bpm,bpm*2);const t=M.timeline(back);near(t.notes[0].seconds,60/bpm);near(t.notes[1].seconds,30/bpm);near(t.seconds,360/bpm);}});
test('invalid nonpositive or nonfinite tempos are rejected without a silent clamp',()=>{for(const bpm of [0,-1,NaN,Infinity,-Infinity,'','abc']){const s=M.blank();s.bpm=bpm;assert.throws(()=>M.sanitize(s),/速度/);s.bpm=96;s.measures[0].bpm=bpm;assert.throws(()=>M.sanitize(s),/速度/);}const s=M.blank();delete s.bpm;assert.equal(M.sanitize(s).bpm,96);});
test('dynamic grades have distinct levels and a stronger piano to forte contrast',()=>{const grades=['pppp','ppp','pp','p','mp','mf','f','ff','fff','ffff'],s=M.blank();s.measures[0].events=grades.map(dynamic=>M.event(28,{dynamic}));const levels=M.timeline(s).notes.map(n=>n.volume);assert.ok(levels.every((v,i)=>!i||v>levels[i-1]));assert.ok(levels[6]/levels[3]>=10);assert.ok(levels[6]/levels[5]>=2);assert.ok(levels.every(v=>v>0&&v<=1));});

test('initial mp and explicit dynamics persist independently through rests and measures',()=>{const s=M.blank();s.voices.push({id:'b',name:'B',clef:'bass'});s.measures=[M.measure({events:[M.event(28),M.event(29,{dynamic:'p'}),M.event(30,{type:'rest'}),M.event(18,{voice:'b'})]}),M.measure({events:[M.event(31),M.event(19,{voice:'b'})]})];const ns=M.timeline(s).notes;near(ns.find(n=>n.voice==='v1'&&n.sequence===0).volume,M.DYNAMIC_LEVELS.mp);for(const n of ns.filter(n=>n.voice==='v1'&&n.sequence>0))near(n.volume,M.DYNAMIC_LEVELS.p);for(const n of ns.filter(n=>n.voice==='b'))near(n.volume,M.DYNAMIC_LEVELS.mp);s.measures[0].dynamic='mf';near(M.timeline(s).notes.find(n=>n.voice==='v1'&&n.sequence===2).volume,M.DYNAMIC_LEVELS.p);});

test('unlabelled hairpins move exactly two grades and continue at the attained level',()=>{for(const [kind,from,to]of [['crescendo','p','mf'],['crescendo','mp','f'],['diminuendo','f','mp'],['diminuendo','mp','pp']]){const s=M.blank(),es=Array.from({length:5},()=>M.event(28));s.measures[0].events=es;es[0].dynamic=from;es[0].hairpin=kind;es[0].hairpinTo=es[2].id;const ns=M.timeline(s).notes;near(ns[0].volume,M.DYNAMIC_LEVELS[from]);for(const n of ns.slice(2))near(n.volume,M.DYNAMIC_LEVELS[to]);}for(const [kind,grade]of [['crescendo','ffff'],['diminuendo','pppp']]){const s=M.blank(),a=M.event(28,{dynamic:grade,hairpin:kind}),b=M.event(29);a.hairpinTo=b.id;s.measures[0].events=[a,b];near(M.timeline(s).notes[1].volume,M.DYNAMIC_LEVELS[grade]);}});

test('text and measure crescendos use the same two-grade rule and explicit endpoints',()=>{const s=M.blank();s.measures[0].events=[M.event(28,{dynamic:'p',expression:'cresc.'}),M.event(29),M.event(30)];let ns=M.timeline(s).notes;near(ns.at(-1).volumeEnd,M.DYNAMIC_LEVELS.mf);s.measures[0].events[0].expression='';s.measures[0].hairpins={v1:{id:'wedge',kind:'crescendo'}};s.measures[0].events.push(M.event(31));s.measures.push(M.measure({events:[M.event(32)]}));ns=M.timeline(s).notes;near(ns.at(-1).volume,M.DYNAMIC_LEVELS.mf);s.measures[0].events.at(-1).dynamic='ff';ns=M.timeline(s).notes;near(ns[3].volumeEnd,M.DYNAMIC_LEVELS.ff);near(ns[4].volume,M.DYNAMIC_LEVELS.ff);});

test('successive unmarked hairpins and repeat jumps retain attained dynamics',()=>{const s=M.blank(),es=Array.from({length:5},()=>M.event(28));es[0].dynamic='p';es[0].hairpin='crescendo';es[0].hairpinTo=es[2].id;es[2].hairpin='crescendo';es[2].hairpinTo=es[4].id;s.measures[0].events=es;const ns=M.timeline(s).notes;near(ns[2].volume,M.DYNAMIC_LEVELS.mf);near(ns[4].volume,M.DYNAMIC_LEVELS.ff);es[0].dynamic='';es[2].hairpin='';s.measures[0].repeatStart=true;s.measures[0].repeatEnd=2;const repeated=M.timeline(s).notes;near(repeated[5].volume,M.DYNAMIC_LEVELS.f);near(repeated[7].volume,M.DYNAMIC_LEVELS.fff);});

test('repeat counts above eight and the former 5000-visit cap save and play in full',()=>{for(const count of [1,9,17,6001]){const s=M.blank();s.measures[0].repeatStart=true;s.measures[0].repeatEnd=count;s.measures[0].events=[M.event(28,{duration:1})];const back=M.sanitize(JSON.parse(JSON.stringify(s))),t=M.timeline(back);assert.equal(back.measures[0].repeatEnd,count);assert.equal(t.route.length,count);assert.equal(t.notes.length,count);assert.equal(t.warnings.length,0);near(t.seconds,count*2.5);}for(const count of [0,-1,1.5,Infinity,NaN,'abc'])assert.throws(()=>M.repeatCount(count),/正整数/);});

test('ending numbers can follow later repeat passes',()=>{const s=M.blank();s.measures=[M.measure({repeatStart:true}),M.measure({ending:'1,2,3,4,5,6,7,8',repeatEnd:9}),M.measure({ending:'9'})];const route=M.playbackRoute(M.sanitize(s)).route;assert.equal(route.at(-1).mi,2);assert.equal(route.at(-1).pass,9);});
test('unlabelled crescendo and diminuendo have clear continuous changes; explicit targets are respected',()=>{for(const kind of ['crescendo','diminuendo']){const s=M.blank(),es=Array.from({length:4},()=>M.event(28));s.measures[0].events=es;es[0].hairpin=kind;es[0].hairpinTo=es[3].id;const ns=M.timeline(s).notes,up=kind==='crescendo';assert.ok(ns.every(n=>up?n.volumeEnd>=n.volume:n.volumeEnd<=n.volume));assert.ok(up?ns[3].volume/ns[0].volume>=2:ns[0].volume/ns[3].volume>=2);es[0].dynamic=up?'p':'f';es[3].dynamic=up?'f':'p';const targeted=M.timeline(s).notes;near(targeted[0].volume,M.DYNAMIC_LEVELS[es[0].dynamic]);near(targeted[3].volume,M.DYNAMIC_LEVELS[es[3].dynamic]);}});
test('default voice naming metadata migrates legacy files and preserves manual names',()=>{const s=M.blank();s.voices.push({id:'b',name:'声部 2',clef:'bass'},{id:'c',name:'Bass 1',clef:'bass'},{id:'d',name:'声部 9',autoName:false,clef:'treble'});const back=M.sanitize(s);assert.deepEqual(back.voices.map(v=>v.autoName),[true,true,false,false]);assert.deepEqual(M.sanitize(JSON.parse(JSON.stringify(back))).voices.map(v=>v.autoName),[true,true,false,false]);});
function score(events,key=0,meter=[4,4]){const s=M.blank();s.key=key;s.meter=meter;s.measures[0].events=events;return s;}
test('all key signatures and octave accidentals',()=>{for(let k=-7;k<=7;k++)assert.equal(Object.keys(M.keyMap(k)).length,Math.abs(k));assert.deepEqual(M.resolved(score([M.event(24),M.event(31),M.event(38)],1)).map(n=>n.midi),[54,66,78]);});
test('single, double, triple augmentation dots',()=>{[0,1,2,3].forEach((dots,i)=>near(M.ticks(M.event(30,{dots}))/48,[1,1.5,1.75,1.875][i]));});
test('all 2-32 tuplets total exactly the requested beats',()=>{for(let n=2;n<=32;n++){const es=Array.from({length:n},()=>M.event());M.setTuplet(es,n,4);const s=score(es);near(es.reduce((a,e)=>a+M.ticks(e),0),192);assert.equal(M.validate(s).length,0);}});
test('parallel voices start together, duration is not summed',()=>{const s=score([M.event(30,{duration:1}),M.event(18,{duration:1,voice:'bass'})]);s.voices.push({id:'bass',name:'低音',clef:'bass',muted:false});s.bpm=120;const t=M.timeline(s);assert.deepEqual(t.notes.map(n=>n.start),[0,0]);near(t.seconds,2);assert.equal(M.stats(s).count,2);assert.equal(M.validate(s).length,0);});
test('voices with different rhythms align at shared beat points',()=>{const s=score([M.event(30),M.event(31),M.event(32,{duration:2}),M.event(18,{voice:'b',duration:2}),M.event(19,{voice:'b',duration:2})]);s.voices.push({id:'b',name:'B',clef:'bass'});s.bpm=120;const t=M.timeline(s);near(t.notes.find(n=>n.e.voice==='b'&&n.e.pitch===19).start,1);near(t.seconds,2);});
test('accidentals are separate across staves, reset each measure',()=>{const s=score([M.event(31,{accidental:0}),M.event(31),M.event(31,{voice:'a'})],1);s.voices.push({id:'a',name:'A',clef:'treble'});s.measures.push(M.measure({events:[M.event(31)]}));assert.deepEqual(M.resolved(s).map(n=>n.midi),[65,65,66,66]);});
test('ottava and tenor clef shift actual range and piano pitch',()=>{const s=score([M.event(28,{ottava:1}),M.event(28,{ottava:-1}),M.event(28,{voice:'t'})]);s.voices.push({id:'t',name:'T',clef:'treble8vb'});assert.deepEqual(M.resolved(s).map(n=>n.midi),[72,48,48]);assert.equal(M.stats(s).highest,'C5');assert.equal(M.stats(s).lowest,'C3');});
test('basic and nested repeat traversal',()=>{const s=M.blank();s.measures=[M.measure({repeatStart:true}),M.measure(),M.measure({repeatEnd:2})];assert.deepEqual(M.playbackRoute(s).route.map(x=>x.mi),[0,1,2,0,1,2]);s.measures=[M.measure({repeatStart:true}),M.measure({repeatStart:true}),M.measure({repeatEnd:2}),M.measure({repeatEnd:2})];assert.deepEqual(M.playbackRoute(s).route.map(x=>x.mi),[0,1,2,1,2,3,0,1,2,1,2,3]);});
test('first and second endings skip correctly',()=>{const s=M.blank();s.measures=[M.measure({repeatStart:true}),M.measure({ending:'1',repeatEnd:2}),M.measure({ending:'2'})];assert.deepEqual(M.playbackRoute(s).route.map(x=>x.mi),[0,1,0,2]);});
test('multi-bar endings and three passes',()=>{const s=M.blank();s.measures=[M.measure({repeatStart:true}),M.measure({ending:'1,2'}),M.measure({ending:'1,2',repeatEnd:3}),M.measure({ending:'3'})];assert.deepEqual(M.playbackRoute(s).route.map(x=>x.mi),[0,1,2,0,1,2,0,3]);});
test('DC al Fine and DS al Coda routes',()=>{const s=M.blank();s.measures=[M.measure(),M.measure({navigation:'fine'}),M.measure({navigation:'dc-fine'})];assert.deepEqual(M.playbackRoute(s).route.map(x=>x.mi),[0,1,2,0,1]);s.measures=[M.measure(),M.measure({navigation:'segno'}),M.measure({navigation:'to-coda'}),M.measure({navigation:'ds-coda'}),M.measure({navigation:'coda'})];assert.deepEqual(M.playbackRoute(s).route.map(x=>x.mi),[0,1,2,3,1,2,4]);});
test('repeats change time, not written note count',()=>{const s=score([M.event(30,{duration:1})]);s.bpm=120;s.measures[0].repeatStart=true;s.measures[0].repeatEnd=3;assert.equal(M.stats(s).count,1);near(M.stats(s).seconds,6);});
test('fermata holds delay all voices once',()=>{const s=score([M.event(30,{duration:1,articulation:'fermata'}),M.event(18,{voice:'b',duration:1,articulation:'fermata'})]);s.voices.push({id:'b',name:'B',clef:'bass'});s.bpm=120;s.measures.push(M.measure({events:[M.event(31,{duration:1}),M.event(19,{voice:'b',duration:1})]}));const t=M.timeline(s);near(t.seconds,5);t.notes.filter(n=>n.mi===1).forEach(n=>near(n.start,3));});
test('repair overflow synchronizes added bars across voices',()=>{const s=score([M.event(31,{duration:1,dots:1,accidental:-1,lyric:'唱'}),M.event(18,{voice:'b',duration:1})]);s.voices.push({id:'b',name:'B',clef:'bass'});s.measures[0].repeatEnd=2;const fixed=M.repair(s);assert.equal(fixed.measures.length,2);assert.equal(M.validate(fixed).length,0);assert.equal(fixed.measures[1].repeatEnd,2);assert.equal(M.events(fixed,fixed.measures[1],'b').every(e=>e.type==='rest'),true);assert.deepEqual(M.resolved(fixed).filter(n=>n.voice==='v1'&&n.midi!==null).map(n=>n.midi),[64,64]);});
test('arbitrary tuplets survive bar splitting with exact duration',()=>{const es=Array.from({length:7},()=>M.event(31,{accidental:1}));M.setTuplet(es,7,6);const s=score(es),fixed=M.repair(s);assert.equal(M.validate(fixed).length,0);near(M.resolved(fixed).filter(n=>n.midi!==null).reduce((a,n)=>a+M.ticks(n.e),0),288);assert.equal(fixed.measures.length,2);});
test('incomplete tuplets reported and filled without rounding errors',()=>{const es=Array.from({length:5},()=>M.event());M.setTuplet(es,5,4);es.splice(2,1);const s=score(es);assert.equal(M.validate(s).filter(i=>i.kind==='tuplet').length,1);assert.equal(M.validate(M.repair(s)).length,0);});
test('ties stay within voice and do not connect repeat jumps',()=>{const s=score([M.event(31,{duration:2,tie:true,accidental:1}),M.event(31,{duration:2})]);s.measures[0].repeatEnd=2;const t=M.timeline(s);assert.equal(t.notes[0].validTie,true);assert.equal(t.notes[1].validTie,false);assert.equal(t.notes[2].continuation,false);});
test('old single-voice files migrate without pitch or lyrics loss',()=>{const raw={version:1,title:'旧作',key:1,mode:'major',clef:'bass',meter:[4,4],bpm:90,measures:[{events:[{id:'old',type:'note',pitch:24,duration:2,dotted:true,triplet:false,accidental:null,lyric:'旧',tie:false}]}]};const s=M.sanitize(raw);assert.equal(s.version,3);assert.equal(s.voices[0].clef,'bass');near(M.ticks(s.measures[0].events[0]),144);assert.equal(M.resolved(s)[0].midi,54);assert.equal(s.measures[0].events[0].lyric,'旧');});
test('roundtrip all v2 fields and reject invalid inputs',()=>{const es=Array.from({length:7},()=>M.event(30,{ottava:2,slur:'slur1',ornament:'trill',dots:2,lyric:'歌'}));M.setTuplet(es,7,4);const s=score(es);s.measures[0].repeatEnd=2;const back=M.sanitize(JSON.parse(JSON.stringify(s)));assert.equal(M.validate(back).length,0);assert.equal(back.measures[0].events[0].ottava,2);assert.equal(back.measures[0].events[0].slur,'slur1');assert.equal(M.stats(s).seconds,M.stats(back).seconds);assert.throws(()=>M.sanitize({...s,voices:[{id:'<bad>'}]}));});
test('mixed fractional rhythms preserve pitch and total when corrected',()=>{for(let n=2;n<=32;n++){const es=[M.event(26,{dots:2}),...Array.from({length:n},()=>M.event(31,{ottava:1,accidental:-1})),M.event(30,{dots:3})];M.setTuplet(es.slice(1,n+1),n,3.125);const s=score(es);const sum=es.reduce((a,e)=>a+M.ticks(e),0),fixed=M.repair(s);assert.equal(M.validate(fixed).length,0);near(M.resolved(fixed).filter(n=>n.midi!==null).reduce((a,n)=>a+M.ticks(n.e),0),sum);assert.equal(M.resolved(fixed).filter(n=>n.e.ottava===1).every(n=>n.midi===76),true);}});
test('repair missing middle members preserves their rhythmic positions',()=>{const es=Array.from({length:7},(_,i)=>M.event(28+i));M.setTuplet(es,7,4);es.splice(2,2);const fixed=M.repair(score(es));assert.equal(M.validate(fixed).length,0);assert.deepEqual(fixed.measures[0].events.map(e=>e.type),['note','note','rest','rest','note','note','note']);assert.deepEqual(fixed.measures[0].events.map(e=>e.tuplet.index),[0,1,2,3,4,5,6]);});
test('saved placeholder rests remain replaceable after reopening',()=>{const s=score([M.event(30,{type:'rest',duration:1,voice:'a',placeholder:true})]);s.voices.push({id:'a',name:'女低音',clef:'treble',muted:true});const back=M.sanitize(JSON.parse(JSON.stringify(s)));assert.equal(back.measures[0].events[0].placeholder,true);assert.equal(back.voices[1].muted,true);});
test('cross-bar tie preserves an accidental without changing later notes',()=>{const s=score([M.event(31,{duration:1,tie:true,accidental:0})],1);s.measures.push(M.measure({events:[M.event(31,{duration:2}),M.event(31,{duration:2})]}));s.bpm=120;assert.deepEqual(M.resolved(s).map(n=>n.midi),[65,65,66]);const t=M.timeline(s);assert.equal(t.notes[0].validTie,true);assert.equal(t.notes[1].continuation,true);near(t.seconds,4);});
test('fresh measure settings and capacity support a new voice',()=>{const s=M.blank();assert.deepEqual(M.settings(s),{key:0,mode:'major',meter:[4,4],bpm:96,clef:'treble'});s.voices.push({id:'newVoice',name:'声部 2',clef:'treble',muted:false});s.measures[0].events.push(...M.restPieces(M.capacity(s,0),'newVoice'));assert.equal(M.events(s,s.measures[0],'newVoice').length,1);near(M.ticks(s.measures[0].events[0]),192);assert.doesNotThrow(()=>M.stats(s));assert.doesNotThrow(()=>M.validate(s));});
test('measure octave marks survive saving and reopening with correct pitch',()=>{const s=score([M.event(28,{duration:1})]);s.measures[0].octaves.v1=1;const back=M.sanitize(JSON.parse(JSON.stringify(s)));assert.deepEqual(back.measures[0].octaves,{v1:1});assert.equal(M.resolved(back)[0].midi,72);assert.equal(M.stats(back).highest,'C5');});
test('per-measure meter, clef, key and tempo survive reopening',()=>{const s=score([M.event(31,{duration:1})]);s.measures.push(M.measure({key:1,meter:[3,4],bpm:120,clefs:{v1:'treble8vb'},events:[M.event(31,{duration:2,dots:1})]}));const back=M.sanitize(JSON.parse(JSON.stringify(s)));assert.deepEqual(M.settings(back,1),{key:1,mode:'major',meter:[3,4],bpm:120,clef:'treble8vb'});near(M.capacity(back,1),144);assert.equal(M.resolved(back)[1].midi,54);near(M.timeline(back).seconds,4);
});
test('arbitrary augmentation-dot counts roundtrip and preserve exact playback duration',()=>{for(const dots of [4,8,32,64])for(const duration of [1,2,4,8,16,128]){const s=M.blank(),e=M.event(28,{duration,dots});s.measures[0].events=[e];const back=M.sanitize(JSON.parse(JSON.stringify(s))).measures[0].events[0];assert.equal(back.dots,dots);near(M.ticks(back),192/duration*(2-Math.pow(2,-dots)));near(M.timeline(s).notes[0].seconds,M.ticks(e)/48*60/s.bpm);}for(const dots of [-1,.5,Infinity]){const s=M.blank();s.measures[0].events=[M.event(28,{dots})];assert.throws(()=>M.sanitize(s),/附点/);}});
test('saved dot-input baseline and chord identities survive reopening without changing musical pitch',()=>{const s=M.blank(),e=M.event(28,{baseInputId:'base_note',duration:8,dots:8,shortcutInputTicks:24,shortcutDotBase:24,chord:[{pitch:30,accidental:null,inputId:'added_tone'}]});s.measures[0].events=[e];const back=M.sanitize(JSON.parse(JSON.stringify(s)));assert.equal(back.measures[0].id,s.measures[0].id);assert.equal(back.measures[0].events[0].shortcutInputTicks,24);assert.equal(back.measures[0].events[0].baseInputId,'base_note');assert.equal(back.measures[0].events[0].chord[0].inputId,'added_tone');assert.deepEqual(M.resolved(back).flatMap(n=>n.tones.map(t=>t.midi)),[60,64]);});
test('repair of a dotted exact rhythm preserves total time while removing stale fragment input baselines',()=>{const s=M.blank(),e=M.event(28,{duration:1,dots:5,shortcutInputTicks:192,shortcutDotBase:192});s.measures[0].events=[e];const fixed=M.repair(s,'all');near(fixed.measures.flatMap(m=>m.events).filter(e=>e.type==='note').reduce((sum,e)=>sum+M.ticks(e),0),M.ticks(e));assert.ok(fixed.measures.flatMap(m=>m.events).filter(e=>e.type==='note').every(e=>e.shortcutInputTicks==null));assert.equal(M.validate(fixed).length,0);});
console.log(checks+' checks passed');


